### ISSUE TITLE
Port fehlt in den Einstellungen für den Server/broker

### ISSUE THREAD

**Issue by maxtox** [ioBroker/ioBroker.mqtt#10]
Wie oben beschrieben, bin bei Admin 3.1.4.

**Comment by Apollon77** [comment]
Could it be a scrolling issue? Which browser? FF?

**Comment by maxtox** [comment]
no...it's not...tried Beta too... only with the old 2.0.7 it is visible...

soooo Found how to solve it...

i just installed 2.07, the back to 3.14 then restart... then it was visible again...

Sorry...

Please close!

**Comment by Apollon77** [comment]
The port field is defined also in the Admin3 files, but there are scrolling issues in some browsers for long config pages ... please try to update admin3 and try again with current version of mqtt please.

**Comment by maxtox** [comment]
please close...it's fixed now by 1.4.2...
Thank You !
