### ISSUE TITLE
mqtt Objekte werden manchmal nicht mehr verändert

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.mqtt#102]
**Describe the bug**  
Eigentlich habe ich die Überwachung von mqtt-Objekten für die Verfügbarkeit der Clients eingebaut.
Dabei überwacht einmal ein iobroker js Script, ob sich ein mqtt-Objekt regelmäßig ändert.
Die Clients überwachen das Objekt ebenfalls.

Seit einigen Wochen erhalte ich sowohl von dem ioBroker Script als auch von den Clients einen Alarm, dass sich
die unterschiedlichsten mqtt-Objekte nicht mehr ändern.

Ebenfalls wird manchmal (so ca. alle 14-Tage) ein mqtt-Objekt (mqtt.0.shellies.shelly1-F42B5B.relay.0.command -- shelly.0 Adapter) von dem js-Script nicht mehr verändert, d.h. der shelly Adapter schaltet nicht mehr. 

Der mqtt Adapter muß neu gestartet werden, dann funktioniert wieder alles für 1-2 Wochen.

**To Reproduce**  
Im Fehlerfall ändert sich das entsprechende mqtt-Objekt nicht mehr, andere schon.

**Expected behavior**  

**Screenshots & Logfiles**  
n.v.

**Versions:**  
 - Adapter version: 2.1.4
 - JS-Controller version: 3.1.6
 - Node version: 10.19.0
 - Operating system: raspbian Linux 4.19.97-v7l+ armv7l

**Additional context**

**Comment by Apollon77** [comment]
hm ... difficult ... I would say enable debug log (and yes this will be much log) and then check what log shows "different" when it happens. Without more details I do not see any good chance to get details here

**Comment by Hans-Zwiesel** [comment]
@Apollon77 
Ich werde debug log einschalten, wenn der Fehler vorhanden ist und dann, wenn mqtt neu gestartet wurde.
Ich hoffe nur, man sieht dann einen Hinweis.

**Comment by Hans-Zwiesel** [comment]
Gerade war der Fehler wieder da. 
Das shelly Objekt mqtt.0.shellies.shelly1-F42B5B.relay.0.command war auf on, aber der shelly Adapter hat nicht geschaltet,
auch nachdem ich das Command nochmals manuell geschrieben habe: 
(setState('mqtt.0.shellies.shelly1-F42B5B.relay.0.command','on')
Wie es aussieht, wird das ...command Objekt nicht published.
Die mqtt-Überwachung hat keine Fehler gemeldet - der Fehler ist also jedesmal bei einzelnen anderen Objekten vorhanden.

Neustart von js hat nichts bewirkt.
Nach Neustart von mqtt hat der shelly Adapter wieder geschaltet.

debug log bei mqtt jetzt eingeschaltet.

**Comment by Hans-Zwiesel** [comment]
@Apollon77
der Fehler mit shelly erscheint jetzt offensichtlich häufiger, so dass ich die Zustände im Log habe.
Die drei wesentlichen Zeilen habe ich mit  !!!!!!!!!!!!!  gekennzeichnet.
Wenn ich noch weiter behilflich sein kann, dann bitte um Nachricht.

[iobroker_mqtt_log.txt](https://github.com/ioBroker/ioBroker.mqtt/files/5128167/iobroker_mqtt_log.txt)

**Comment by Apollon77** [comment]
Was ist in der mqtt Konfig gesetzt bei "Store only on change:" ? Wenn das nämlich gesetzt ist dann lässt sih der effekt so erklären das der wert schon so ist wie er gesetzt werden soll ... und dann geht keine nachricht raus

**Comment by Hans-Zwiesel** [comment]
Den Eintrag finde ich leider nicht, hier meine Einstellung, sind die so richtig??

![grafik](https://user-images.githubusercontent.com/49147193/91378073-d72e7e00-e81f-11ea-8d83-3f95a18b32a8.png)

**Comment by Apollon77** [comment]
Dann bitte mal log wenn es nicht mehr geht

**Comment by Hans-Zwiesel** [comment]
Das log mit true habe ich ja schon gestern kopiert.
Dann schalte ich das Publish nur bei Änderung einmal aus und kopiere das log noch einmal, wenn sich der Fehler wieder
zeigt.

**Comment by Apollon77** [comment]
AM besten einmal in beide richtungen schalten

**Comment by Hans-Zwiesel** [comment]
Ich bin mir nicht sicher, ob ich Dich richtig verstehe, denn
bei dem log von gestern  (iobroker_mqtt_log.txt) war Publish nur bei Änderung auf "EIN"
brauchst Du das nochmal?

**Comment by Hans-Zwiesel** [comment]
Heute ist wieder der mqtt Fehler aufgetaucht(Publish nur bei Änderungen = aus).
Im Log fällt mir auf:
`2020-09-05 14:29:35.594  - [32minfo[39m: mqtt.0 (27701) Client [ROBONECT53C82A] connected with secret 1599308975591_8765

Dann jede Menge resend:
2020-09-05 14:29:40.445  - [34mdebug[39m: mqtt.0 (27701) Client [ROBONECT53C82A] Resend message topic: haus/outdoor/MaxGarage/RoboMax/control/mode, payload: auto

Dann wird die Überwachung aktiv:
2020-09-05 14:35:47.558  - [32minfo[39m: email.0 (27592) Send email: {"text":"Rasenroboter Max meldet sich seit 5 Minuten nicht mehr","to":"hst@datentech.de","subject":"Roboter Max meldet sich nicht mehr"
`

Hoffentlich hilft das Log weiter.
Warum um 14:29 plötzlich ein connect erscheint, weiß ich nicht.
Der Client ist jedenfalls schon tagelang angemeldet.

[mqtt_fehler.txt](https://github.com/ioBroker/ioBroker.mqtt/files/5178257/mqtt_fehler.txt)

**Comment by Hans-Zwiesel** [comment]
Problem gibt es immer noch.
Ich muß MQTT jeden Tag neu starten, sonst funktioniert irgendwann der Zigbee Bewegungsmelder nicht mehr.
Der Rasenroboter ist inzwischen in der Garage und hat Winterurlaub.

**Comment by Apollon77** [comment]
Sponan denke ich das erste Thema liegt an "Publish nur bei änderung " weil wenn value+ack gleich ist dann ist eine neue betätigung keine Änderung.
Die Massen-Resends sollten mit der neuesten GitHub version behoben sein. Bitte testen.
