### ISSUE TITLE
MQTTS: Support for Self-Signed certificates

### ISSUE THREAD

**Issue by KoMa1978** [ioBroker/ioBroker.mqtt#103]
Hi,

I'm using MQTT 2.1.4 and try to encrypt any traffic in the network.

Can you please add an option like "Accept Self-Signed Certificates" after enabling SSL.

I now solved this by adding "rejectUnauthorized: false" in line 135 (in the mqtt.connect options) of /opt/iobroker/node_modules/iobroker.mqtt/lib/client.js

Thanks a lot,
 Marco

**Comment by KoMa1978** [comment]
No one else having this issue or wants to use encrypted traffic?

**Comment by FunCyRanger** [comment]
No, but I used the same option in the client to connect to my Hisense-TV.
Therefor I inserted an option in the MQTT-client setup.
Details see https://github.com/ioBroker/ioBroker.mqtt/pull/121
