### ISSUE TITLE
errors for "mixed" type of variable!

### ISSUE THREAD

**Issue by maxtox** [ioBroker/ioBroker.mqtt#11]
Has to be changed!

**Comment by Apollon77** [comment]
Can we please have some more details? Error message? Log?

**Comment by maxtox** [comment]
yes... no pproblem.

If you create a variable as a "mixed" you get a error message, that this type of variable will not be supported in the next version of adapter....

**Comment by Apollon77** [comment]
Does this error comes from mqtt adapter or from JavaScript Adapter? Normally I only know this error from JavaScript adapter.
And in general "Mixed" is a very bad type :-) so exakt log would be helpfull

**Comment by Apollon77** [comment]
I could expect that this issue and #13 could both be because of "mixed" datatypes ...

**Comment by GermanBluefox** [comment]
Please verify with 2.0.1
