### ISSUE TITLE
payload for toggle box

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.mqtt#110]
Hi .. this is rather a short question than a feature request.
If I toggle the object checkbox besides in iobroker to set a topic true/false .. what does the payload/message look like?
Is it "true" and "false" or 1/0 .. etc?

**Comment by Apollon77** [comment]
When I understand the code correctly it should be a "true" or "false" as string... But best enable debug log and you should see it in the log

**Comment by daniel-lo** [comment]
Figured this out .. thanks
