### ISSUE TITLE
Nach update werden Fantasiewerte übermittelt

### ISSUE THREAD

**Issue by Dragon0501** [ioBroker/ioBroker.mqtt#114]
Nach dem Update von 2.1.10 auf 2.1.12 werden laut MQTT Input bei ESP Easy die richtigen Werte übertragen, das Display blendet zwischendurhc aber immer wieder Fantasiewerte ein, welche aber im MQTT input nicht nachvollziehbar sind. Ich hätte es auf den ESP mit dem Display geschoben, aber nach einem DOwngrade auf 2.1.10 und sonst keiner Veränderung ist alles wieder in Ordnung. Keine Fehlinformationen mehr auf dem Display. 

![Screenshot 2020-10-26 at 11 37 35](https://user-images.githubusercontent.com/59663011/98996152-ac0c1e80-2532-11eb-9f97-dab1ca99e496.png)

**Comment by Apollon77** [comment]
Die einzige Änderung zwischen 10 und 12 war das ein Fehler abgefangen wird wenn der Server wegen Zertifikatsproblemen nicht initialisiert werde kann. Strange

**Comment by Dragon0501** [comment]
Ja allerdings. erst wird ein richtiger Wert übermittelt und angezeigt, dann wird er in etwas geändert auf dem Display in etwas was im ganzen System als Wert nicht existiert. Könnte also schon etwas damit zu tun haben was bestätigt wird oder verarbeitet. KLingt verrückt, aber ist leider so, weil ist auch reproduzierbar.
