### ISSUE TITLE
Setup Problem

### ISSUE THREAD

**Issue by OberstVonGatow** [ioBroker/ioBroker.mqtt#118]
Hi,

maybe i just don't understand MQTT but this is what i tried to do:

- Installed the Adapter on Iobroker Raspberry Pi.
- Instance is yellow (no connection to mqtt)
- Another Raspberry Pi without iobroker but with paho-mqtt for python is running on the local network
- I tried to use two Python Scripts on the same Pi (one subscriber, one publisher) and send over the iobroker mqtt broker
 (I know that makes little sense but part two would be to publish and subscribe also from the iobroker)
- The two python scripts are running with "screen" (i don't know if that makes any difference)
- The Scripts show me "Connected with result code 0" and the iobroker shows in the log that a client is connected and has subscribed

Okay seems good but if i send a payload from my publisher script nothing happens at the subscriber.
I think i don't understand something here. Do i have to use iobroker states? And how?

Regards
Fabian

**Comment by Apollon77** [comment]
Please show your log, yellow in a first place means that nothing is connected

**Comment by OberstVonGatow** [comment]
I changed the setup a little bit.

- Setup Instanz Server
![image](https://user-images.githubusercontent.com/6384996/101000092-b633a280-355d-11eb-9055-afd3c3f7d71b.png)

- On the other raspberry i publish with
mosquitto_pub -h "ip iobroker" -t /iobroker/mqtt/0/retroradio/power -m "Test remote"
![image](https://user-images.githubusercontent.com/6384996/101004312-d022b480-3560-11eb-8cc9-a3fd7739b7f8.png)

Looking good so far

- On a second Terminal on the other Raspberry i subscribed to the channel
mosquitto_sub -h "ip iobroker" -d -t /iobroker/mqtt/0/retroradio/power

I get green instance light and i get messages from mosquitto_pub.

If i now change the state in iobroker in the Object List. Nothing is Published.
![image](https://user-images.githubusercontent.com/6384996/101006340-67880780-3561-11eb-87fc-89a7feb9708e.png)

How can i publish state changes?

**Comment by OberstVonGatow** [comment]
I got my problem/misunderstanding. I thought i just have to change the value of the object to publish a message.
Instead i need to use a javascript script 
`sendTo('mqtt.0',` 'sendMessage2Client', {topic: '/retroradio/power', message: 'on'});`

As i tough not a bug just me don`t get things right.
