### ISSUE TITLE
Why subscribe all states if subscribe pattern is empty?

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.mqtt#130]
When setting an mqtt instance to loglevel debug, I recognized, that it subscribes to all states, even though the publish pattern in the config is empty, because I currently only use it to receive messages.

Now I changed it to a non-existing pattern to avoid unnecessary subscriptions, however, I don't think the adapter should subscribe all if the publish pattern is empty. Default is `*`, then it's fine to subscribe all ;-)

So maybe just change https://github.com/ioBroker/ioBroker.mqtt/blob/556e60f30cbe5ae3571a8738eb6e927ee9c0ad98/main.js#L181-L185

**Comment by Apollon77** [comment]
This would be a breaking change, or ?!

**Comment by foxriver76** [comment]
Not fixed afaik

**Comment by GermanBluefox** [comment]
Please test 4.0.0
