### ISSUE TITLE
DP Fragmente lassen sich nicht löschen

### ISSUE THREAD

**Issue by J-Paul0815** [ioBroker/ioBroker.mqtt#131]
![image](https://user-images.githubusercontent.com/51191964/105824256-65b94e00-5fbe-11eb-99ac-1b1aaa08a74e.png)

mqtt.0.Wortuh�PWo
mqtt.0.Wort�6Wort
mqtt.0.Wor�:Wortu

Habe DP Fragmente im mqtt.0 Ordner die sich auch nicht löschen lassen.
Adapter ist, wie alles andere auch auf dem letzten Stand (Stable).
Beim Versuch einer dieser DP zu löschen kommt die Meldung:
Fehler
Das Objekt "mqtt.0.Wortuh��P�Wo" existiert nicht. Seite aktualisieren.
iobroker fix 
Your installation was fixed successfully
löste aber das Problem nicht

Wie werde ich diese Fragmente los?
Wie lässt sich das in der Zukunft vermeiden? 

Mqtt Adapter Version 2.3.3
node v12.20.1
npm 6.14.10
js-controller 3.1.6

**Comment by Apollon77** [comment]
Die "vermeidung" sollte im Adater bereits seit 2.1.6 drin, wenn danach noch solche IDs reinkommen müsste man dies neu prüfen.

Wenn es per Admin nicht löschbar ist bleibt nur das manuelle editieren der objects.json (nach Stop von ioBroker). Im Forum gibts da nen Thread zu, ggf mal suchen
