### ISSUE TITLE
Spamming PUB messages

### ISSUE THREAD

**Issue by SolarWind13** [ioBroker/ioBroker.mqtt#132]
My setup:

Platform - linux
OS - Debian 10.7
Architecture - x64
CPUs - 2
Speed - 1497 MHz
Model - AMD Turion(tm) II Neo N40L Dual-Core Processor
RAM - 3.85 GB
System uptime - 6 d. 23:15:12
Node.js - v12.20.1
NPM - 6.14.10
Disk size - 45.03 GB
Disk free - 39.52 GB
Number of adapters - 326
Uptime - 1 d. 23:37:42
Active instances - 19
Hostname - myhome
Type: js-controller - Installed: 3.2.7

mosquitto 1.5.7-1+deb10u1

MQTT Broker/Client - 2.3.2

Adapter configuration:

![IOB_35](https://user-images.githubusercontent.com/35486852/105957813-6ddac180-6082-11eb-9297-2fede3b63358.png)

![IOB_36](https://user-images.githubusercontent.com/35486852/105957863-7c28dd80-6082-11eb-97b6-aa95d5ef53ff.png)

Problem:

- sometime IOBroker begin spam to topics random data very frequntly 

Log:

![IOB_34](https://user-images.githubusercontent.com/35486852/105958094-d5910c80-6082-11eb-8799-0eb98469c0e8.png)

Video for example:

https://user-images.githubusercontent.com/35486852/105958180-f0fc1780-6082-11eb-917e-2bb923b35a10.mp4

Restart IOBroker аixes the problem for a while

P.S. This topics used in my scripti for night light - when IOBroker spam data to topic script work very bad

![IOB_37](https://user-images.githubusercontent.com/35486852/105958925-f1e17900-6083-11eb-8f1f-aad803372ea4.png)

**Comment by Apollon77** [comment]
Can you please post a debug log of that effect?

* Stop the adapter in Admin
* go to a shell
* run `DEBUG=mqtt-packet:writeToStream iobroker debug mqtt.0`

Copy the log here from the console - there should be some additional logs written. And add informations when happened what (timewise)

**Comment by Dominik-1980** [comment]
@SolarWind13 

Hello.

Did you find a solution? I have the exact same problem…

**Comment by Apollon77** [comment]
@Dominik-1980 posting on a issue closed since 2 months is not that ideal ... which version of adapter you use? Else see above and provide logs with the CURRENT version as new issue
