### ISSUE TITLE
mqtt server/broker keine Verbindung Status gelb

### ISSUE THREAD

**Issue by MarkM500** [ioBroker/ioBroker.mqtt#134]
**Describe the bug**  
Bekomme keine Verbindung zum mqtt Broker/server. In log: Zugriff auf '/dev/disk/by-id/' nicht möglich: Datei oder Verzeichnis nicht gefunden

**To Reproduce**  
1. iobroker nach Anleitung "https://smarthome.buanet.de/2019/05/iobroker-unter-docker-auf-der-synology-diskstation-v3/" installiert. Netzwerk auf Bridge!
2. Anfragen über mein Roomba mit ESP8266 (MQTT) oder MQTT-Explorer führen zu keiner Verbindung. Status mqtt gelb!
3. Im Internet nach einer Lösung nicht fündig geworden.
4. Fehler in den logs
5. Anmerkung: Vorher war mosquitto auch auf 1883 installiert. Ist aber deinstalliert.

**Expected behavior**  
Habe ich irgendeine Einstellung falsch gemacht? In mosquitto wurden meine Anfragen über den Explorer und die clients erkannt.

**Screenshots & Logfiles**  
log als Screenshot, weil ich es so in der log nichtgefunden habe:
![Bildschirmfoto 2021-02-01 um 16 54 40](https://user-images.githubusercontent.com/77006589/106482979-52225180-64ae-11eb-9436-d040f9a4a2c8.png)

[iobroker.2021-02-01.log](https://github.com/ioBroker/ioBroker.mqtt/files/5904867/iobroker.2021-02-01.log)
![Bildschirmfoto 2021-02-01 um 16 43 26](https://user-images.githubusercontent.com/77006589/106481389-acbaae00-64ac-11eb-92e5-07d19a7ff77a.png)
![Bildschirmfoto 2021-02-01 um 16 42 51](https://user-images.githubusercontent.com/77006589/106481392-adebdb00-64ac-11eb-9a58-98ee5fc79713.png)
![Bildschirmfoto 2021-02-01 um 16 41 46](https://user-images.githubusercontent.com/77006589/106481396-ae847180-64ac-11eb-89a1-37140bf89c37.png)

**Versions:**  
 - Adapter version: <last>
 - iobroker-version: <last>
 - Operating system: <synology/docker>

**Additional context**  
Mittlerweile fehlen mir die Ideen.

Hoffentlich kann jemand helfen, da ich über den Biobroker so viel gutes gelesen habe...

Gruss
Mark

**Comment by Apollon77** [comment]
Honestly? that log looks very strange like that controller ist started several times in parallel in the container and so also mqtt omehow gets started over and over again ... this should have nothing to do with the adapter itself ... ele we need to stop mqtll while container runs , go into the container and execute

iobroker debug mqtt

then post the log

**Comment by MarkM500** [comment]
Hi,
thanks. I execute it in portioner in the console over "Exec Console" 3 times. Nothing happened.
Here is the log:
[iobroker.2021-02-02.log](https://github.com/ioBroker/ioBroker.mqtt/files/5910210/iobroker.2021-02-02.log)
Thanks for your help.

**Comment by Apollon77** [comment]
Sorry But I can not help ypu on docker setup questions maybe better in Forum?
In teh attached log it sys:
> Error starting MQTT server on 0.0.0.0:1883: Error: listen EADDRINUSE: address already in use 0.0.0.0:1883

so something occupies the port

**Comment by MarkM500** [comment]
perhaps my old mosquitto installation. But how to reopen it for iobroker?
