### ISSUE TITLE
LOG floated with warnings after update to latest stable version of js-controller and node.js

### ISSUE THREAD

**Issue by friedpa** [ioBroker/ioBroker.mqtt#137]
**Describe the bug**  
After updating to latest stable version of js-controller and node.js the IOBroker LOG is floated with warnings.

**To Reproduce**  
1. update to latest version of js-controller and node.js
2. reboot system
3. view LOG

**Expected behavior**  
No warnings of this kind in the LOG in a one second circle

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 2.3.4
 - JS-Controller version: 3.20.16
 - Node version: 12.20.2
 - Operating system: Debian

**Additional context**  
`
moma.0 | 2021-02-21 10:28:09.968 | warn | (17132) State "moma.0.currentLoad.cpus.0.raw_load_system" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
moma.0 | 2021-02-21 10:28:09.961 | warn | (17132) State "moma.0.currentLoad.cpus.0.raw_load_user" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:09.908 | warn | (17132) State "moma.0.currentLoad.cpus.0.raw_load" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:09.879 | warn | (17132) State "moma.0.currentLoad.raw_currentload_idle" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:09.872 | warn | (17132) State "moma.0.currentLoad.raw_currentload_system" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:09.822 | warn | (17132) State "moma.0.currentLoad.raw_currentload_user" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:09.814 | warn | (17132) State "moma.0.currentLoad.raw_currentload" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:08.026 | warn | (17132) State "moma.0.currentLoad.cpus.3.raw_load_idle" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:08.020 | warn | (17132) State "moma.0.currentLoad.cpus.3.raw_load_system" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:08.014 | warn | (17132) State "moma.0.currentLoad.cpus.3.raw_load_user" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:08.008 | warn | (17132) State "moma.0.currentLoad.cpus.3.raw_load" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:07.981 | warn | (17132) State "moma.0.currentLoad.cpus.2.raw_load_idle" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:07.932 | warn | (17132) State "moma.0.currentLoad.cpus.2.raw_load_system" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:07.925 | warn | (17132) State "moma.0.currentLoad.cpus.2.raw_load_user" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:07.918 | warn | (17132) State "moma.0.currentLoad.cpus.2.raw_load" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:07.888 | warn | (17132) State "moma.0.currentLoad.cpus.1.raw_load_idle" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:07.882 | warn | (17132) State "moma.0.currentLoad.cpus.1.raw_load_system" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:07.835 | warn | (17132) State "moma.0.currentLoad.cpus.1.raw_load" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:07.811 | warn | (17132) State "moma.0.currentLoad.cpus.0.raw_load_idle" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:07.762 | warn | (17132) State "moma.0.currentLoad.cpus.0.raw_load_system" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:07.757 | warn | (17132) State "moma.0.currentLoad.cpus.0.raw_load_user" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:07.751 | warn | (17132) State "moma.0.currentLoad.cpus.0.raw_load" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:07.721 | warn | (17132) State "moma.0.currentLoad.raw_currentload_idle" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:07.675 | warn | (17132) State "moma.0.currentLoad.raw_currentload_system" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:07.667 | warn | (17132) State "moma.0.currentLoad.raw_currentload_user" has no existing object, this might lead to an error in future versions
moma.0 | 2021-02-21 10:28:07.659 | warn | (17132) State "moma.0.currentLoad.raw_currentload" has no existing object, this might lead to an error in future versions

`

**Comment by friedpa** [comment]
Does no one else has this problem?

**Comment by Apollon77** [comment]
why closed?
