### ISSUE TITLE
MQTT CLIENT SSL Connection via CA certification file

### ISSUE THREAD

**Issue by trackersos** [ioBroker/ioBroker.mqtt#139]
Hello,

is there no way to connect to a MQTT Broker via SSL CA certification file in client mode?
In the Admin panel is just a check box for SSL. But what does it mean?

Would be great if someone could answer me my questions. 

Kind regards

**Comment by Apollon77** [comment]
When you tick the ssl setting then the client connection is espablished to mqtts but I assume expects a valid certificate. For server the server establishs a secure server too

**Comment by chrkli7** [comment]
Of course ...but where to place the client-certificates? There is no place in the web gui...how to do that?
