### ISSUE TITLE
Server setting "Trace output for every message" has no function

### ISSUE THREAD

**Issue by endym** [ioBroker/ioBroker.mqtt#14]
The server setting "Trace output for every message" seems to have no function. I use a door sensor as MQTT client and see only the common "info" output in the Log window:
```
2018-02-23 11:42:05.529  - info: mqtt.0 starting. Version 1.4.2 in /opt/iobroker/node_modules/iobroker.mqtt, node: v6.13.0
2018-02-23 11:42:05.823  - info: mqtt.0 Starting MQTT  server on port 1883
2018-02-23 11:42:27.991  - info: mqtt.0 Client [doorsensor1] connected
```
The client publish messages arrives the broker as I can see in the "Objects" window, but I would expect some debug output as well.

Background is, that I want to investigate missing PUBACK messages for publish messages (QoS>0).
For more details please see [ioBroker forum thread](http://forum.iobroker.net/viewtopic.php?f=20&t=11869) or [heise forum thread](https://www.heise.de/forum/c-t/Kommentare-zu-c-t-Artikeln/Smarter-und-kompakter-Tuersensor-mit-WLAN/Problem-mit-iobroker/thread-5497751/) (both in German).

Environment:
- ioBroker 1.2.3
- MQTT 1.4.2 (same with 1.4.1)
- Admin 3.2.0 (same with 2.0.9)
- Firefox 52.6.0

Greetings,
endym

**Comment by Apollon77** [comment]
Do you tried to set loglevel for the instance to debug? 
Instances -expertmode ... column loglevel.

**Comment by endym** [comment]
Hi Apollon77,

that did the trick, thanks a lot!
Sorry for blaming this as an issue, but nobody answered in the forum thread...

Output with debug is now:
```
2018-02-23 18:58:29.741  - info: mqtt.0 Client [doorsensor1] connected
2018-02-23 18:58:29.745  - debug:  mqtt.0 stateChange mqtt.0.info.connection:  {"val":"doorsensor1","ack":true,"ts":1519408709744,"q":0,"from":"system.adapter.mqtt.0","lc":1519408578712}
2018-02-23 18:58:29.755  - debug:  mqtt.0 stateChange mqtt.0.stat.doorsensor1.status:  {"val":"open","ack":true,"ts":1519408709753,"q":0,"from":"system.adapter.mqtt.0","lc":1519382450019}
```
Does `"q":0` mean, the message QoS is zero? That would explain the missing PUBACK, at least from the server's point of view. Question is now, is the client sending with wrong QoS (the code says 1) or is there an error on the server side?

Is there a detailed description of the MQTT debug output?

**Comment by Apollon77** [comment]
I can not really say something about QoS with MQTT I only see in the adapter code that the "Trace output for every message:" option enables additional log messages while in debug loglevel.

The stateChange logs above - and especially the "q" in there - have nothing to do with QoS. Adapter states also have a quality level, 0 means "official good value", so highest quality.

When I see it correctly the qos of published values is never loggen at the moment

**Comment by endym** [comment]
Ok, I close this issue now, because the initial problem is solved.
Nevertheless, any help regarding the debugging of received server messages is appreciated.

endym

**Comment by endym** [comment]
@GermanBluefox 
I've have looked into the MQTT server code and didn't find the PUBACK answer handling for Publish messages with QoS>0. I would expect this handling in [server.js](https://github.com/ioBroker/ioBroker.mqtt/blob/master/lib/server.js), function `receivedTopic()` or any sub-function.
The only PUBACK code is in [writeToStream.js](https://github.com/ioBroker/ioBroker.mqtt/blob/master/lib/writeToStream.js), but if I understand it right, the task of this file is only "data conversion", not "logical" message handling.

Greetings,
endym

**Comment by Apollon77** [comment]
Please create a new issue for this

**Comment by endym** [comment]
Done: #15
