### ISSUE TITLE
No new data 

### ISSUE THREAD

**Issue by Starter4711** [ioBroker/ioBroker.mqtt#145]
**Describe the bug**  
Mqtt Master is connected to Client, Objekt Info is connected, data stays black..
Seams to be the last update of the Adapter.

**To Reproduce**  
takes a while, nothing to do

**Expected behavior**  
new data

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 2.3.4
 - JS-Controller version: 3.2.16 
 - Node version: 12.21.0 
 - Operating system: rapsi light
<img width="1242" alt="Bildschirmfoto 2021-03-10 um 12 58 04" src="https://user-images.githubusercontent.com/15359915/110625875-4e19db80-81a0-11eb-8407-dd7618972658.png">

**Additional context**  
After restart from the adapter, the data gets updated (green)

**Comment by Apollon77** [comment]
Please enable Debug log, maybe you see more what happens

**Comment by Starter4711** [comment]
Hi, now it is not active, no new value.
`

mqtt.0 | 2021-03-11 18:45:38.942 | debug | (27026) Client [AMIS] pingreq
-- | -- | -- | --
mqtt.0 | 2021-03-11 18:45:28.142 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:45:17.467 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:45:06.768 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:44:55.918 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:44:45.169 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:44:34.569 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:44:23.769 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:44:12.945 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:44:02.372 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:43:51.695 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:43:40.946 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:43:30.371 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:43:19.672 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:43:08.947 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:42:58.348 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:42:47.597 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:42:36.723 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:42:26.073 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:42:15.374 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:42:04.549 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:41:53.799 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:41:43.150 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:41:32.302 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:41:21.526 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:41:10.901 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:41:00.052 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:40:49.227 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:40:38.652 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:40:27.877 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:40:17.077 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:40:06.453 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:39:55.753 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:39:44.954 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:39:34.279 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:39:23.580 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:39:12.755 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:39:01.980 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:38:51.305 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:38:40.556 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:38:29.610 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:38:18.882 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:38:08.032 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:38:06.365 | debug | (27026) system.adapter.admin.0: logging true
mqtt.0 | 2021-03-11 18:37:57.108 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:37:46.362 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:37:35.562 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:37:24.638 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:37:13.909 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:37:03.160 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:36:52.260 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:36:41.464 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:36:30.761 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:36:19.836 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:36:13.643 | debug | (27026) system.adapter.admin.0: logging false
mqtt.0 | 2021-03-11 18:36:08.912 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:35:58.187 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:35:47.338 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:35:36.441 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:35:25.642 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:35:14.717 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:35:03.789 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:34:53.040 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:34:42.193 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:34:31.344 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:34:20.469 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:34:09.741 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:33:58.816 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:33:47.845 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:33:37.142 | debug | (27026) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:33:32.624 | debug | (27026) system.adapter.admin.0: logging true

`

**Comment by Starter4711** [comment]
after downgrade to 2.3.3
but, after a restart it always starts again, does not mean it is the sollution.
`

mqtt.0 | 2021-03-11 18:51:07.231 | debug | (23924) Client [AMIS] pingreq
-- | -- | -- | --
mqtt.0 | 2021-03-11 18:51:06.895 | debug | (23924) stateChange mqtt.0.AMIS: {"val":"{\"1.8.0\":13846746,\"2.8.0\":19496162,\"3.8.1\":10815187,\"4.8.1\":4812729,\"1.7.0\":5090,\"2.7.0\":0,\"3.7.0\":2461,\"4.7.0\":0,\"1.128.0\":0}","ack":true,"t
mqtt.0 | 2021-03-11 18:51:03.885 | debug | (23924) stateChange mqtt.0.AMIS: {"val":"{\"1.8.0\":13846742,\"2.8.0\":19496162,\"3.8.1\":10815185,\"4.8.1\":4812729,\"1.7.0\":5090,\"2.7.0\":0,\"3.7.0\":2433,\"4.7.0\":0,\"1.128.0\":0}","ack":true,"t
mqtt.0 | 2021-03-11 18:51:00.877 | debug | (23924) stateChange mqtt.0.AMIS: {"val":"{\"1.8.0\":13846738,\"2.8.0\":19496162,\"3.8.1\":10815183,\"4.8.1\":4812729,\"1.7.0\":5098,\"2.7.0\":0,\"3.7.0\":2446,\"4.7.0\":0,\"1.128.0\":0}","ack":true,"t
mqtt.0 | 2021-03-11 18:50:59.746 | debug | (23924) system.adapter.admin.0: logging true
mqtt.0 | 2021-03-11 18:50:57.875 | debug | (23924) stateChange mqtt.0.AMIS: {"val":"{\"1.8.0\":13846734,\"2.8.0\":19496162,\"3.8.1\":10815181,\"4.8.1\":4812729,\"1.7.0\":5246,\"2.7.0\":0,\"3.7.0\":2426,\"4.7.0\":0,\"1.128.0\":0}","ack":true,"
mqtt.0 | 2021-03-11 18:50:56.482 | debug | (23924) Client [AMIS] pingreq
mqtt.0 | 2021-03-11 18:50:54.873 | debug | (23924) stateChange mqtt.0.AMIS: {"val":"{\"1.8.0\":13846728,\"2.8.0\":19496162,\"3.8.1\":10815178,\"4.8.1\":4812729,\"1.7.0\":5211,\"2.7.0\":0,\"3.7.0\":2439,\"4.7.0\":0,\"1.128.0\":0}","ack":true,"
mqtt.0 | 2021-03-11 18:50:51.877 | debug | (23924) stateChange mqtt.0.AMIS: {"val":"{\"1.8.0\":13846724,\"2.8.0\":19496162,\"3.8.1\":10815176,\"4.8.1\":4812729,\"1.7.0\":5107,\"2.7.0\":0,\"3.7.0\":2449,\"4.7.0\":0,\"1.128.0\":0}","ack":true,"
mqtt.0 | 2021-03-11 18:50:48.879 | debug | (23924) stateChange mqtt.0.AMIS: {"val":"{\"1.8.0\":13846719,\"2.8.0\":19496162,\"3.8.1\":10815174,\"4.8.1\":4812729,\"1.7.0\":5097,\"2.7.0\":0,\"3.7.0\":2439,\"4.7.0\":0,\"1.128.0\":0}","ack":true,"
mqtt.0 | 2021-03-11 18:50:45.873 | debug | (23924) stateChange mqtt.0.info.connection: {"val":"AMIS","ack":true,"ts":1615485045869,"q":0,"from":"system.adapter.mqtt.0","user":"system.user.admin","lc":1615485045869}
mqtt.0 | 2021-03-11 18:50:45.846 | debug | (23924) Client [AMIS] with keepalive 15 set timeout to 22.5 seconds
mqtt.0 | 2021-03-11 18:50:45.694 | info | (23924) Client [AMIS] connected with secret 1615485045684_2430
mqtt.0 | 2021-03-11 18:50:34.931 | debug | (23924) stateChange mqtt.0.info.connection: {"val":"","ack":true,"ts":1615485034926,"q":0,"from":"system.adapter.mqtt.0","user":"system.user.admin","lc":1615485034926}
mqtt.0 | 2021-03-11 18:50:34.921 | info | (23924) Starting MQTT server on 0.0.0.0:1883
mqtt.0 | 2021-03-11 18:50:34.513 | info | (23924) starting. Version 2.3.3 in /opt/iobroker/node_modules/iobroker.mqtt, node: v12.21.0, js-controller: 3.2.16
mqtt.0 | 2021-03-11 18:50:34.272 | debug | (23924) Plugin sentry Initialize Plugin (enabled=true)
mqtt.0 | 2021-03-11 18:50:33.921 | debug | (23924) statesDB connected
mqtt.0 | 2021-03-11 18:50:33.920 | debug | (23924) States connected to redis: 127.0.0.1:9000
mqtt.0 | 2021-03-11 18:50:33.902 | debug | (23924) States create User PubSub Client
mqtt.0 | 2021-03-11 18:50:33.901 | debug | (23924) States create System PubSub Client
mqtt.0 | 2021-03-11 18:50:33.893 | debug | (23924) Redis States: Use Redis connection: 127.0.0.1:9000
mqtt.0 | 2021-03-11 18:50:33.890 | debug | (23924) objectDB connected
mqtt.0 | 2021-03-11 18:50:33.881 | debug | (23924) Objects connected to redis: 127.0.0.1:9001
mqtt.0 | 2021-03-11 18:50:33.868 | debug | (23924) Objects client initialize lua scripts
mqtt.0 | 2021-03-11 18:50:33.867 | debug | (23924) Objects create User PubSub Client
mqtt.0 | 2021-03-11 18:50:33.866 | debug | (23924) Objects create System PubSub Client
mqtt.0 | 2021-03-11 18:50:33.863 | debug | (23924) Objects client ready ... initialize now
mqtt.0 | 2021-03-11 18:50:33.809 | debug | (23924) Redis Objects: Use Redis connection: 127.0.0.1:9001
mqtt.0 | 2021-03-11 18:50:30.116 | info | (27026) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mqtt.0 | 2021-03-11 18:50:30.115 | debug | (27026) Plugin sentry destroyed
mqtt.0 | 2021-03-11 18:50:30.114 | info | (27026) terminating
mqtt.0 | 2021-03-11 18:50:29.611 | info | (27026) Got terminate signal TERMINATE_YOURSELF
mqtt.0 | 2021-03-11 18:50:28.432 | debug | (27026) Client [AMIS] pingreq

`

**Comment by Starter4711** [comment]
still running with 2.3.3
no restart of client

**Comment by Starter4711** [comment]
next day, still running with 2.3.3
I think the last version has a problem.
Regards

**Comment by Apollon77** [comment]
hm ... First of all @Starter4711 why you post oncea day? is that your way to try to add pressure to developers that take care of adapters in their free time. If yes: think about it very deep please ...

2.3.4 had exactly one error case catch and added some error logging (https://github.com/ioBroker/ioBroker.mqtt/commit/bab24fc8de4afb3eec75487fd32ca19367561524) I would not expect that to be an issue.

2.3.5 just changed the default config onwhat the adapter subscribes to mqtt.0.* instead of * ... No effect for new installations

I would not see any reason for effect that you describe. 2.3.4 is used by over 6k users and 2.3.5 runs on >1.500 installations ... noone else reported that issue so far ...

**Comment by Starter4711** [comment]
hmm... no, I just wanted to report an error I am facing. was asked to show the debug log, so I did, all other info should help the developer what is going on on my site.
I do not give pressure on it, I am very thankful to use the adapter.
Actuall 2.3.3 runs fine, tomorrow I will give it an other try to update.

**Comment by Apollon77** [comment]
We prepare an update. Can you try that please? Please install from GitHub And if it still happens please use the following to get an enhanced debug log:

* Stop the adapter in Admin
* go to a shell
* run `DEBUG=mqtt-packet:writeToStream iobroker debug mqtt.0`

When it then happens copy the log here from the console (and also include a bit from before where it was still working) - there should be some additional logs written. Maybe we see with this from where it comes.
