### ISSUE TITLE
Teste Verbindung zum Server nicht mit Username und Passwort möglich

### ISSUE THREAD

**Issue by jolu1705** [ioBroker/ioBroker.mqtt#147]
**Describe the bug**  
Bei Verwendung des mqtt Adapters als Client kann ich mich mit dem Mosquitto Broker mit Username und Passwort verbinden.
Die Funktion "Teste Verbindung zum Server" quittiert aber immer mit einem Error.
Nehme ich die authentication raus, funktioniert es.
Die Funktion kann scheinbar nicht mit Username und Passwort umgehen.

**To Reproduce**  
Install mosquitto auf Server
Install mqqt Adapter als Client
Lege im mosquitto Server Benutzer und Passwort an.
Teste Benutzer und Passwort.
Trage Benutzer und Passwort im mqtt Adapter ein
Mache tail -f auf /var/log/mosquitto/mosquitto.log und starte den Adapter.
Der Adapter verbindet sich.
Gehe auf den Adapter und drücke "Teste Verbindung zum Server"
Der Test schlägt fehl und im logfile gibt es einen Verbindungsabbruch.

**Expected behavior**  
Verbindungstest auch mit Username und Passwort möglich

**Screenshots & Logfiles**  
Siehe hier: https://forum.iobroker.net/topic/43279/mqtt-befehl-nach-alexa-sprachkommando-senden/25

**Versions:**  
 - Adapter version: 2.3.5
 - JS-Controller version: 3.2.16
 - Node version: v12.21.0
 - Operating system: Raspbian GNU/Linux 10 (buster)

**Additional context**  
n/a

**Comment by Apollon77** [comment]
Did you saved the adapter configuration before trying to use the test?

**Comment by Apollon77** [comment]
Ahhh I see it ... should be fixable

**Comment by uwesimon** [comment]
Test does not work for SSL connections (which should be used for username/password).

Error is in main.js line 119
const _url = `mqtt://${obj.message.user ? (`${obj.message.user}:${obj.message.pass}@`) : ''}${obj.message.url}${obj.message.port ? (':' + obj.message.port) : ''}?clientId=ioBroker.${adapter.namespace}`;

depending on message.ssl 'mttq:' or 'mqtts:' should be used.
