### ISSUE TITLE
Update from V2.1.14 -> 2.3.4 only with difficulties/V2.3.4->2.3.5 not working/ERR! code EINTEGRITY

### ISSUE THREAD

**Issue by WillyIoBrok** [ioBroker/ioBroker.mqtt#152]
Update from V2.1.14 -> 2.3.4 worked only after "npm cache clear --force"
Update from V2.3.4->2.3.5 not working at all

**To Reproduce**  
1. Go to 'ioBroker Adapter Overview'
2. Click on 'update to 2.3.5' on MQTT App 2.3.4

**Expected behavior**  
Update of the adapter to V2.3.5
**Screenshots & Logfiles**  

Log of ioBroker:
host.ioBroker-4	iobroker upgrade mqtt
host.ioBroker-4	iobroker Update mqtt from @2.3.4 to @2.3.5
host.ioBroker-4	iobroker NPM version: 6.14.11
host.ioBroker-4	iobroker npm install iobroker.mqtt@2.3.5 --loglevel error --prefix "/opt/iobroker" (System call)
host.ioBroker-4	info	iobroker npm
host.ioBroker-4	iobroker ERR! code EINTEGRITYnpm ERR! errno EINTEGRITY
host.ioBroker-4	iobroker npm ERR!
host.ioBroker-4	iobroker Invalid response body while trying to fetch https://registry.npmjs.org/buffer: Integrity verification failed for sha512-LU3E2pFIyHqdtYjAKQPbxFParK1I5edDjpMuKevSgQOJlsdppHAx+zlGObr+rVLkvyPKZ
host.ioBroker-4	iobroker
host.ioBroker-4	iobroker npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2021-04-02T14_38_25_543Z-debug.log
host.ioBroker-4	iobroker upload [3] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/words.js words.js application/javascript
host.ioBroker-4	iobroker upload [2] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/mqtt.png mqtt.png image/png
host.ioBroker-4	iobroker upload [1] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/index_m.html index_m.html text/html
host.ioBroker-4	iobroker upload [0] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/index.html index.html text/html
host.ioBroker-4	iobroker Adapter "mqtt" updated
host.ioBroker-4	iobroker exit 0

**Versions:**  
 - Adapter version: <2.3.4>
 - JS-Controller version: <3.1.6> 
 - Node version: <V14.16.0> 
 - Operating system: <LINUX on Raspberry 4>

**Additional context**  

tried this also with Node Version 10 before - same result.

**Comment by WillyIoBrok** [comment]
see also https://forum.iobroker.net/topic/43257/

**Comment by WillyIoBrok** [comment]
sorry, wrong button - it's the first time I am using Github ...

**Comment by Apollon77** [comment]
In fact this is no adapter issue. Please retry. It seems that there was an npm integrity check failing when downloading. Most likely solving itself. Or zog need to clear npm cache. Best ask in forum.
