### ISSUE TITLE
Invalid messageid

### ISSUE THREAD

**Issue by Bernd9000** [ioBroker/ioBroker.mqtt#154]
Hallo
Hab hier mal eine möglichkeit gefunden das leidige Thema "invalid messageid" nachzustellen.
Hab eine neue Instanz des MQTT Adapters zum testen erstellt und den Server Port auf 4883 gestellt.
Nur zwei WLAN Steckdosen mit Tasmota (Firmware 9.3.2.1) sind am Broker angemeldet.
ioBroker ist unter Windows 10 installiert
MQTT Adapter hat die Version 2.3.5 
Node.js   v12.22.0 / NPM   6.14.11 / js-controller 3.2.16

Wenn ich jetzt die WLAN Steckdosen **einzeln** neu starte (reset) ist alles gut.
Wenn ich beide aber zur gleichen Zeit neu starte kommt es relativ schnell zum "invalid messageid" Problem.
Die Log fängt da an, wo beide Clients "Steckdose-2" und "Schlauchpumpe-Keller" neu gestartet werden (connection closed)

mqtt.1 | 2021-04-07 14:07:25.644 | info | (2932) Client [DVES_B0DA3D] connection closed: Error: Invalid messageId
-- | -- | -- | --
mqtt.1 | 2021-04-07 14:07:25.644 | debug | (2932) Client [DVES_B0DA3D] Resend messages on connect: tele/Schlauchpumpe-Keller/LWT = Offline
mqtt.1 | 2021-04-07 14:07:25.606 | info | (2932) Client [DVES_B0DA3D] unsubscribes on unknown topic "homeassistant/status"
mqtt.1 | 2021-04-07 14:07:25.606 | info | (2932) Client [DVES_B0DA3D] publishOnSubscribe send all known states
mqtt.1 | 2021-04-07 14:07:25.606 | info | (2932) Client [DVES_B0DA3D] subscribes on "cmnd/DVES_B0DA3D_fb/#"  with regex /^mqtt\.1\.cmnd\.DVES_B0DA3D_fb\..*/
mqtt.1 | 2021-04-07 14:07:25.605 | info | (2932) Client [DVES_B0DA3D] subscribes on "cmnd/DVES_B0DA3D_fb/#" with regex /^cmnd\.DVES_B0DA3D_fb\..*/
mqtt.1 | 2021-04-07 14:07:25.605 | info | (2932) Client [DVES_B0DA3D] publishOnSubscribe send all known states
mqtt.1 | 2021-04-07 14:07:25.605 | info | (2932) Client [DVES_B0DA3D] subscribes on "cmnd/sonoffs/#"  with regex /^mqtt\.1\.cmnd\.sonoffs\..*/
mqtt.1 | 2021-04-07 14:07:25.605 | info | (2932) Client [DVES_B0DA3D] subscribes on "cmnd/sonoffs/#" with regex /^cmnd\.sonoffs\..*/
mqtt.1 | 2021-04-07 14:07:25.604 | info | (2932) Client [DVES_B0DA3D] publishOnSubscribe send all known states
mqtt.1 | 2021-04-07 14:07:25.604 | info | (2932) Client [DVES_B0DA3D] subscribes on "cmnd/Steckdose-2/#"  with regex /^mqtt\.1\.cmnd\.Steckdose-2\..*/
mqtt.1 | 2021-04-07 14:07:25.604 | info | (2932) Client [DVES_B0DA3D] subscribes on "cmnd/Steckdose-2/#" with regex /^cmnd\.Steckdose-2\..*/
mqtt.1 | 2021-04-07 14:07:25.539 | debug | (2932) Client [DVES_B0DA3D] with keepalive 30 set timeout to 45 seconds
mqtt.1 | 2021-04-07 14:07:25.539 | debug | (2932)  Client [DVES_B0DA3D] with last will  {"retain":true,"qos":1,"topic":"tele/Steckdose-2/LWT","payload":{"type":"Buffer","data":[79,102,102,108,105,110,101]}}
mqtt.1 | 2021-04-07 14:07:25.539 | info | (2932) Client [DVES_B0DA3D] connected with secret 1617797245538_8154
mqtt.1 | 2021-04-07 14:07:22.478 | info | (2932) Client [DVES_D8F687] connection closed: closed
mqtt.1 | 2021-04-07 14:07:19.677 | info | (2932) Client [DVES_B0DA3D] connection closed: closed

**Comment by Bernd9000** [comment]
Hab herausgefunden das der Fehler aus der folgenden Datei kommt:
node_modules/mqtt-connection/node_modules/mqtt-packet/writeToStream.js

Hier in dieser Function wird der Fehler ausgelöst:
function publish (packet, stream, opts)
'
'
In den Zeilen:
// Message ID must a number if qos > 0
  if (qos && typeof id !== 'number') {
    stream.emit('error', new Error('Invalid messageId1' + id + qos))
    return false
  } else if (qos) length += 2

Die Variable "qos" hat den Wert 1
Die Variable "id" ist undefined
Und das löst den Fehler aus.
Aber warum ist der Wert "undefined"

**Comment by Apollon77** [comment]
duplicate #129 

@Bernd9000 could you try to get sushc a debug log as asked for in https://github.com/ioBroker/ioBroker.mqtt/issues/129#issuecomment-830163223
