### ISSUE TITLE
MQTT Log-stufe debug

### ISSUE THREAD

**Issue by Bernd9000** [ioBroker/ioBroker.mqtt#155]
MQTT Adapter Version 2.3.5 / Windows 10
Node.js v12.22.1 / NPM 6.14.11 / js-controller 3.2.16

Habe zwei Instanzen vom MQTT Adapter
mqtt.0 ist als Client eingestellt (Log-Stufe "Info")
mqtt.1 ist als Server eingestellt (Log-Stufe "debug")

Fehler ? : Es mischen sich die Log-Meldungen beider Instanzen.

Beispiel aus der Log:
**mqtt.1**	2021-04-09 09:00:11.090	debug	(1920) stateChange **mqtt.0**.stat.Temperatursensor2.LOGGING: {"val":"09:00:09.163 MQT: tele/Temperatursensor2/STATE = {\"Time\":\"2021-04-09T09:00:09\",\"Uptime\":\"0T00:00:11\",\"UptimeSec\":11,\"Heap\"

**Comment by Apollon77** [comment]
zeig mal deine konfiguration. Am Ende ist es so das scheinbar du in mqtt.1 auf States subscribst wo auch mqtt.0 dabei ist und natürlich sieht der dann diese wertänderungen
