### ISSUE TITLE
MQTT läuft. Trotzdem Fehler.

### ISSUE THREAD

**Issue by LJ-Mic** [ioBroker/ioBroker.mqtt#16]
Ich habe Probleme mit dem Adapter.
Er läuft, so weit ganz gut. Es sendet und empfängt.
Unter Instanzen habe ich nach einen Neustart immer ein gelbes Licht.
Wenn ich darauf gehe, steht unter "Verbunden mit mqtt" "falsch".

Ich habe es schon gelöscht und neu Installiert.

Gehe ich auf "Teste Verbindung zum Server" ist der Adapter komplett raus.
Starte ich diesen neu, sendet er alles. Ist Grün und geht nach ein paar Sekunden wieder auf gelb.

ioBroker: 1.3.0
MQTT: 1.5.0
Pi 3

**Comment by GermanBluefox** [comment]
Was heisst komplett raus? Logs?

14 мар. 2018 г. 9:23 пользователь "Michael Schaffer" <
notifications@github.com> написал:

**Comment by LJ-Mic** [comment]
Wo finde ich die Logs?
Na das dann alles Rot ist.

**Comment by GermanBluefox** [comment]
Diese Frage ist gleich zu: wo finde ich die Tastatur

вс, 18 мар. 2018 г., 15:49 Michael Schaffer <notifications@github.com>:

**Comment by GermanBluefox** [comment]
NO answer.
