### ISSUE TITLE
After upgrade to js-controller 3.3.x 

### ISSUE THREAD

**Issue by cracyfloyd** [ioBroker/ioBroker.mqtt#160]
Warning in log file:

mqtt.0 | 2021-04-30 12:14:26.298 | warn | State value to set for "mqtt.0.ems-esp.heating_active" has wrong type "boolean" but has to be "string"
-- | -- | -- | --

**Comment by MarkSau** [comment]
mqtt.0 | 2021-04-30 19:31:43.194 | warn | State value to set for "mqtt.0.Wohnwagen.rpi2.0.temperature.soc_temp" has wrong type "number" but has to be "string"
-- | -- | -- | --
mqtt.0 | 2021-04-30 19:29:09.080 | warn | State value to set for "mqtt.0.Wohnwagen.sensor.Temp.humidity" has wrong type "number" but has to be "string"

**Comment by msiemers** [comment]
Hier auch diverse Meldungen in den Logs.

**Comment by Apollon77** [comment]
> diverse Meldungen

Bitte poste Sie mal ... meine Glaskugel ist mir die Tage leider runtergfallen

**Comment by frankbullitt** [comment]
Bei mir auch nach dem Update viele MQTT warn Meldungen:

mqtt.0 | 2021-05-01 00:21:34.660 | warn | (2275) State value to set for "mqtt.0.Stromzaehler_2.Zaehler_Halle.Time" has wrong type "number" but has to be "string"
-- | -- | -- | --
mqtt.0 | 2021-05-01 00:21:34.555 | warn | (2275) State value to set for "mqtt.0.Stromzaehler_2.Zaehler_Halle.Total" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 00:21:34.446 | warn | (2275) State value to set for "mqtt.0.Stromzaehler_2.Zaehler_Halle.Count" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 00:21:24.651 | warn | (2275) State value to set for "mqtt.0.Stromzaehler_2.Zaehler_Halle.Time" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 00:21:24.547 | warn | (2275) State value to set for "mqtt.0.Stromzaehler_2.Zaehler_Halle.Total" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 00:21:24.439 | warn | (2275) State value to set for "mqtt.0.Stromzaehler_2.Zaehler_Halle.Count" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 00:21:15.326 | warn | (2275) State value to set for "mqtt.0.Stromzaehler_1.Gas-Mieter.Time" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 00:21:15.231 | warn | (2275) State value to set for "mqtt.0.Stromzaehler_1.Gas-Mieter.Total" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 00:21:15.118 | warn | (2275) State value to set for "mqtt.0.Stromzaehler_1.Gas-Mieter.Count" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 00:21:15.017 | warn | (2275) State value to set for "mqtt.0.Stromzaehler_1.Zaehler_Mieter.Time" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 00:21:14.909 | warn | (2275) State value to set for "mqtt.0.Stromzaehler_1.Zaehler_Mieter.Total" has wrong type "number" but has to be "string"

**Comment by msiemers** [comment]
@Apollon77 

mqtt.0 | 2021-05-01 08:02:02.814 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_5.Entprellzeit" has wrong type "number" but has to be "string"
-- | -- | -- | --
mqtt.0 | 2021-05-01 08:02:02.814 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_4.Entprellzeit" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:02:02.814 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_3.Entprellzeit" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:02:02.813 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_2.Entprellzeit" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:02:02.800 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_1.Entprellzeit" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:02:02.800 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_0.Entprellzeit" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:02:02.800 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_5.Impulse" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:02:02.799 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_4.Impulse" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:02:02.799 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_3.Impulse" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:02:02.799 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_2.Impulse" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:02:02.799 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_1.Impulse" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:02:02.799 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_0.Impulse" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:01:32.804 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_5.Entprellzeit" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:01:32.804 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_4.Entprellzeit" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:01:32.804 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_3.Entprellzeit" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:01:32.804 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_2.Entprellzeit" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:01:32.800 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_1.Entprellzeit" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:01:32.800 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_0.Entprellzeit" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:01:32.800 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_5.Impulse" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:01:32.800 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_4.Impulse" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:01:32.800 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_3.Impulse" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:01:32.800 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_2.Impulse" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:01:32.799 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_1.Impulse" has wrong type "number" but has to be "string"
mqtt.0 | 2021-05-01 08:01:32.799 | warn | (2378240) State value to set for "mqtt.0.SmartHome.Sensor.Haustechnikraum.Impulszaehler.Zaehler_0.Impulse" has wrong type "number" but has to be "string"

**Comment by ThetaGamma** [comment]
das Problem betrifft aber mE nicht nur MQTT:
sonoff.0 | 2021-05-01 16:32:45.692 | warn | (820570) State value to set for "sonoff.0.avatar5.Wifi_Downtime" has wrong type "string" but has to be "number"
-- | -- | -- | --

info.0 | 2021-05-01 16:32:47.368 | warn | (819462) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
-- | -- | -- | --

**Comment by msiemers** [comment]
```
@ThetaGamma 

Das ist richtig. Das Problem besteht auch bei vielen anderen Adaptern.
```

**Comment by Apollon77** [comment]
Please test GitHub version!

**Comment by Apollon77** [comment]
Cool, will come officially soon as 2.4.0

**Comment by Apollon77** [comment]
3.3 is in Latest Beta test at the moment ... will come together with Admin 5 to stable later

**Comment by friedpa** [comment]
OK, so no need to upgrade now ... Great work so far! Thx!
