### ISSUE TITLE
Wrong typ nach Umstellung auf js-controller 3.3.4

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.mqtt#164]
lt. Community sollen Meldungen die sich aus der Umstellung des js-controller auf die Version 3.3.4 ergeben bei den entsprechenden Adaptern gemeldet werden.

Der Adapter funktioniert Augenscheinlich normla, jedoch wird das LOG mit WARN Meldungen übersäät.

`

mqtt.2 | 2021-05-01 10:21:07.095 | warn | (6344) State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has wrong type "string" but has to be "number"
-- | -- | -- | --

`

**Comment by ThetaGamma** [comment]
Hab ich auch. Das meiste ist mqtt, aber auch

info.0 | 2021-05-01 16:33:20.359 | warn | (819462) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
-- | -- | -- | --

sonoff.0 | 2021-05-01 16:32:45.692 | warn | (820570) State value to set for "sonoff.0.avatar5.Wifi_Downtime" has wrong type "string" but has to be "number"
-- | -- | -- | --

**Comment by foxriver76** [comment]
duplicate of #160
