### ISSUE TITLE
Update von V2.4.0 auf Windows mit Fehler

### ISSUE THREAD

**Issue by Hirsch-DE** [ioBroker/ioBroker.mqtt#169]
$ ./iobroker upgrade mqtt
Update mqtt from @2.3.5 to @2.4.0
NPM version: 6.11.3
npm install iobroker.mqtt@2.4.0 --loglevel error (System call)
npm ERR! code EBUSY
npm ERR! syscall rename
npm ERR! path C:\iobroker\ioBroker01\node_modules\iobroker.mqtt
npm ERR! dest C:\iobroker\ioBroker01\node_modules\.iobroker.mqtt.DELETE
npm ERR! errno -4082
npm ERR! EBUSY: resource busy or locked, rename 'C:\iobroker\ioBroker01\node_modules\iobroker.mqtt' -> 'C:\iobroker\ioBroker01\node_modules\.iobroker.mqtt.DELETE'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\iobroker\ioBroker01\env\npm-cache\_logs\2021-05-10T07_26_09_055Z-debug.log
ERROR: host.Technik-01(ioBroker01) Cannot install iobroker.mqtt@2.4.0: 4294963214
ERROR: process exited with code 25

**Comment by Apollon77** [comment]
This has nothing to do with the adapter. It seems that windows blocks acces to some resources when iobroker/theadapter is running and you try to update. Try to stop the adapter and/or iobrokernand do update then.
