### ISSUE TITLE
MQTT Topic-Scheme switching sometimes

### ISSUE THREAD

**Issue by cimba007** [ioBroker/ioBroker.mqtt#18]
Hello,

I am using the latest github version 1.5.0 and encountered a strange behavior regarding topic names.

First of all I am using https://github.com/256dpi/arduino-mqtt

The most important part I want to discuss is this:

```
client.subscribe("esp8266color/0_hsv");
```
which sometimes results in this:
```
mqtt.0 | 2018-04-04 21:49:53.153 | info | publishOnSubscribe
-- | -- | -- | --
mqtt.0 | 2018-04-04 21:49:53.152 | info | Client [ESP8266Client] subscribes on "mqtt.0.esp8266color.0_hsv"
mqtt.0 | 2018-04-04 21:49:53.141 | info | Client [ESP8266Client] connected
```

and sometimes in this

```

mqtt.0 | 2018-04-04 21:47:31.182 | info | Client [ESP8266Client] subscribes on topic "esp8266color/0_hsv"
-- | -- | -- | --
mqtt.0 | 2018-04-04 21:47:30.738 | info | Client [ESP8266Client] connected
```
![image](https://user-images.githubusercontent.com/3453121/38331245-07b7521a-3853-11e8-8888-713443005c96.png)

On the other hand if I change some stats in the iobroker admin console it (at least one time) got published to **mqtt.0.esp8266color.0_hsv** and not **esp8266color/0_hsv**

I have not fully digged into the trace-stuff but it just feels wrong. This issue might have some connection with a problem I experience with that the esp8266-client doesn't seem to recognize published messages after ~>12-24 hours of runtime of the broker but I will investigate this further tomorrow with the use of 
https://github.com/JoaoLopesF/RemoteDebug

**Comment by GermanBluefox** [comment]
Yes. If the variable does not exist you will see such a message "topic...":
https://github.com/ioBroker/ioBroker.mqtt/blob/master/lib/server.js#L878
