### ISSUE TITLE
handle # in device names

### ISSUE THREAD

**Issue by JonasGoebel** [ioBroker/ioBroker.mqtt#182]
I have devices with a "#" in it's name (Shelly SHSW-1#11490B#1) inside my ioBroker instance.
Iobroker.mqtt is configured to forward states to an external mqtt broker, but keeps restarting when I add "shelly.0" to the publish mask.  

Is there a way to mask the "#" with something different?
For example iobroker.mqtt publishes to `iobroker/shelly/0/SHSW-1_11490B_1` instead of `iobroker/shelly/0/SHSW-1#11490B#1`
Currently messages containing a # result in a disconnect (maybe because the '#' means "subscribe to every subtopic").

Log:
`Disconnected from 192.168.3.4: Error: write ECONNRESET
Subscribe on: "iobroker"
Connected to 192.168.3.4
Disconnected from 192.168.3.4: Error: write ECONNRESET
Subscribe on: "iobroker"
Connected to 192.168.3.4
Disconnected from 192.168.3.4: Error: write ECONNRESET
Subscribe on: "iobroker"
Connected to 192.168.3.4`

**Comment by Apollon77** [comment]
Are there any other characters reserved in mqtt?

**Comment by JonasGoebel** [comment]
As mentioned [here](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718109) "#" and "+" are used for wildcards, so they should not be used. A "$" at the beginning of a topic is also not allowed (4.7.2 in link). 
I wouldn't use "/" because it divides parts of a topic path (my/mqtt/topic). Other UTF-8 chars should be allowed.

**Comment by Apollon77** [comment]
Should we replace the naed chracters by _ or - ?!

**Comment by JonasGoebel** [comment]
Sounds good!
Personally I'd prefer _ because it should be used less often, but both should work.

**Comment by Apollon77** [comment]
Bt that I find the correct spot: can you please enable the "debug logging "in the adapter config and post me a log that shows what hie tries to send and such?!

**Comment by JonasGoebel** [comment]
[mqtt.log](https://github.com/ioBroker/ioBroker.mqtt/files/8145438/mqtt.log)

**Comment by Apollon77** [comment]
I checked the MQTT specs again and basically there is no real limitation fr topic names regarding # and + ... they are just special characters when you send a "subscribe" ... so my question is: What is that external mqtt broker exactly? maybe that one is implemented wrong? Could you check that?

**Comment by JonasGoebel** [comment]
I'm currently using the latest version of eclipse-mosquitto inside a docker container, docker image from [here](https://hub.docker.com/_/eclipse-mosquitto).
Using another client (for example "mqtt-explorer") has the same effect: "Client xy disconnected due to malformed packet".

**Comment by Apollon77** [comment]
Ok, in the meantime after a looooot of googling I was able to find statements from AWS and IBM brokers like

> Publishing clients can't use wildcard characters in the topic names they publish. 

This would mean we should limit/replace + and # ... (a leading $ should never happen).

I now have one "Issue" ... There is already existing logic where the topic name is scanned for  invalid (mainly non ascii) characters and then the topic is completely blocked right now ... So idea wouldbe to add these characters to these lists AND add an "repace onvalid chars rather then blocking them" which is default off but can be turned on

**Comment by JonasGoebel** [comment]
That sounds like the easiest fix for this issue. 👍🏻 
Getting a message from a topic like "iobroker/shelly/0/SHSW-1_11490B_1" is far better than no message

**Comment by Apollon77** [comment]
In the meantime I checked again and the mentioned List of forbidden characters just ignore secial charcters on incoming data on server ... So, I implement it directly ... please try GitHub version

**Comment by JonasGoebel** [comment]
I just tested this on my ioBroker instance with the Shelly devices.
Works perfectly!

Thank you very much for your development and support.
