### ISSUE TITLE
js-controller 3.3.x - State issue

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.mqtt#184]
Auch hier div. Fehlermeldungen, nach dem Js-controller Update. mqtt Adapter Version 2.4.0 / js-controller 3.3.14
`
<html>
<body>

mqtt.2 | 2021-07-18 06:07:02.210 | info | (8420) State value to set for "mqtt.2.openWB.housebattery.DailyYieldImportKwh" has to be type "string" but received type "number"
-- | -- | -- | --
mqtt.2 | 2021-07-18 06:07:02.201 | info | (8420) State value to set for "mqtt.2.openWB.system.YearGraphDatan12" has to be type "number" but received type "string"
mqtt.2 | 2021-07-18 06:07:02.201 | info | (8420) State value to set for "mqtt.2.openWB.system.YearGraphDatan11" has to be type "number" but received type "string"
mqtt.2 | 2021-07-18 06:07:02.200 | info | (8420) State value to set for "mqtt.2.openWB.system.YearGraphDatan10" has to be type "number" but received type "string"
mqtt.2 | 2021-07-18 06:07:02.200 | info | (8420) State value to set for "mqtt.2.openWB.system.YearGraphDatan9" has to be type "number" but received type "string"
mqtt.2 | 2021-07-18 06:07:02.199 | info | (8420) State value to set for "mqtt.2.openWB.system.YearGraphDatan8" has to be type "number" but received type "string"
mqtt.2 | 2021-07-18 06:07:02.198 | info | (8420) State value to set for "mqtt.2.openWB.system.YearGraphDatan7" has to be type "number" but received type "string"
mqtt.2 | 2021-07-18 06:07:02.197 | info | (8420) State value to set for "mqtt.2.openWB.system.YearGraphDatan6" has to be type "number" but received type "string"
mqtt.2 | 2021-07-18 06:07:02.196 | info | (8420) State value to set for "mqtt.2.openWB.system.YearGraphDatan3" has to be type "number" but received type "string"
mqtt.2 | 2021-07-18 06:07:02.196 | info | (8420) State value to set for "mqtt.2.openWB.system.YearGraphDatan2" has to be type "number" but received type "string"
mqtt.2 | 2021-07-18 06:07:02.195 | info | (8420) State value to set for "mqtt.2.openWB.system.MonthGraphDatan12" has to be type "number" but received type "string"
mqtt.2 | 2021-07-18 06:07:02.195 | info | (8420) State value to set for "mqtt.2.openWB.system.MonthGraphDatan11" has to be type "number" but received type "string"
mqtt.2 | 2021-07-18 06:07:02.194 | info | (8420) State value to set for "mqtt.2.openWB.system.MonthGraphDatan10" has to be type "number" but received type "string"
mqtt.2 | 2021-07-18 06:07:02.194 | info | (8420) State value to set for "mqtt.2.openWB.system.MonthGraphDatan9" has to be type "number" but received type "string"
mqtt.2 | 2021-07-18 06:07:02.193 | info | (8420) State value to set for "mqtt.2.openWB.system.MonthGraphDatan8" has to be type "number" but received type "string"
mqtt.2 | 2021-07-18 06:07:02.184 | info | (8420) State value to set for "mqtt.2.openWB.lp.8.TimeRemaining" has to be type "string" but received type "number"
mqtt.2 | 2021-07-18 06:07:02.181 | info | (8420) State value to set for "mqtt.2.openWB.lp.7.TimeRemaining" has to be type "string" but received type "number"
mqtt.2 | 2021-07-18 06:07:02.177 | info | (8420) State value to set for "mqtt.2.openWB.lp.6.TimeRemaining" has to be type "string" but received type "number"
mqtt.2 | 2021-07-18 06:07:02.174 | info | (8420) State value to set for "mqtt.2.openWB.lp.5.TimeRemaining" has to be type "string" but received type "number"
mqtt.2 | 2021-07-18 06:07:02.165 | info | (8420) State value to set for "mqtt.2.openWB.lp.4.TimeRemaining" has to be type "string" but received type "number"
mqtt.2 | 2021-07-18 06:07:02.162 | info | (8420) State value to set for "mqtt.2.openWB.lp.3.TimeRemaining" has to be type "string" but received type "number"
mqtt.2 | 2021-07-18 06:07:02.158 | info | (8420) State value to set for "mqtt.2.openWB.lp.2.TimeRemaining" has to be type "string" but received type "number"
mqtt.2 | 2021-07-18 06:07:02.153 | info | (8420) State value to set for "mqtt.2.openWB.lp.1.TimeRemaining" has to be type "string" but received type "number"
mqtt.2 | 2021-07-18 06:07:01.707 | info | (8420) Subscribe on: "#"
mqtt.2 | 2021-07-18 06:07:01.705 | info | (8420) Connected to 10.122.60.107
mqtt.2 | 2021-07-18 06:07:01.641 | info | (8420) Try to connect to mqtt://openWB:*******************@10.xxx.xxx.xxx:1883?clientId=iobroker.mqtt.2
mqtt.2 | 2021-07-18 06:07:01.254 | info | (8420) starting. Version 2.4.0 in C:/iobroker/GLT/node_modules/iobroker.mqtt, node: v14.16.0, js-controller: 3.3.14

</body>
</html>`

**Comment by Apollon77** [comment]
Mal objekte gelöscht? Danach immer noch?

**Comment by JBSullivan** [comment]
Hätte ich auch gleich drauf kommen können - ja dann sind die Melungen weg. Bei den ganzen Updates die die letzten Monate erschienen sind, weiß man ja nie wirklich ob das Löschen der Objekte notwendig ist. Steht ja meist nur "Anpassung an js-controller 3.3.x" im Change Log.

Von daher kann geschlossen werden.

**Comment by Apollon77** [comment]
Ja ich überlege gerade wie wir das dann demnächst kommunizieren :-)
