### ISSUE TITLE
MQTT Topic wird unterschiedlich gesendet

### ISSUE THREAD

**Issue by SabineTobi** [ioBroker/ioBroker.mqtt#19]
Ich hab MQTT Broker/Client als Client installiert und bei den "MQTT Einstellungen" unter "Prefix für alle Topics" iobroker/ eingestellt. "Publish nur bei Änderung" hab ich nicht ausgewählt, "Bekanntgeben eigene States beim Verbinden" schon.

Als MQTT-Server hab ich Mosquitto auf einem anderen Linuxrecher laufen und schaue dort mit "mosquitto_sub -v -t +/#" mit, was so alles an Topics daher kommt.

Nach einem Start oder Neustart werden die Topics dann in der Form "iobroker/xxx/yyy" ausgegeben, bei einem Update des zugehörigen Objects dann aber als "iobroker/iobroker/xxx/yyy".
Der Prefix wird also 2x vorgesetzt!

Wenn ich Prefix leer lasse wird übrigens immer nur "xxx/yyy" gesendet. Schaut für mich also danach aus, dass beim Posten eines Updates der Prefix 2x vorgesetzt wird, beim Bekanntgeben der States beim Verbinden aber nur 1x.

Ich hab mir mal im Verzeichnis /opt/iobroker/node_modules/iobroker.mqtt/lib die beiden Programme client.js und common.js angeschaut.

In client.js in der **function send2Server** wird u.a.:
**convertID2topic(obj._id, null, adapter.config.prefix, adapter.namespace);** aufgerufen
und später dann:
**client.publish(adapter.config.prefix + topic, null);**

In der function **publishAllStates** wird aber:
**client.publish(config.prefix + id.replace(/\./g, '/'), state2string(states[id].val), function (err)**
verwendet.

In common.js kommt in der function **convertID2topic** u.a. dann:
**topic = prefix + id;** vor.

D.h. bei send2Server wird erst durch convertID2topic der prefix vorgesetzt und dann beim publish nochmals.
Beim publishAllStates wird aber beim client.publish die id selber verwendet.

lg, Sabine

**Comment by GermanBluefox** [comment]
Danke für deine SEHR ausführlicher Bericht. 
Damit konnte ich den Fehler problem los fixen. Bitte 2.0.1 testen

**Comment by Apollon77** [comment]
@SabineTobi fixed?
