### ISSUE TITLE
client error: Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by dony71** [ioBroker/ioBroker.mqtt#192]
I have ioBroker.mqtt v.2.4.0 and I have modified "rejectUnauthorized": false in io-package.json
Why I still get this error? I thought this issue has been fix here
https://github.com/ioBroker/ioBroker.mqtt/issues/103 ?

**Comment by Apollon77** [comment]
Please provide settings screenshots and proper logs to check it ... with the provided infos I can only guess

**Comment by Apollon77** [comment]
no answer
