### ISSUE TITLE
In Version 2.0.0 "Secret Warnings"

### ISSUE THREAD

**Issue by schmupu** [ioBroker/ioBroker.mqtt#20]
Ich bekomme mit der 2.0.0 follgende Warnings:
``
`
mqtt.0 2018-06-19 14:18:00.855 warn Old client ESPClient0 with secret 1529410641752_6519 sends publish. Ignore! Actual secret is 1529410680003_8852 

mqtt.0 2018-06-19 14:18:00.854 warn Old client ESPClient0 with secret 1529410641752_6519 sends publish. Ignore! Actual secret is 1529410680003_8852 

mqtt.0 2018-06-19 14:18:00.811 warn Old client ESPClient0 with secret 1529410641752_6519 sends publish. Ignore! Actual secret is 1529410680003_8852 

mqtt.0 2018-06-19 14:18:00.013 info Client [ESPClient0] subscribes on "/thermometer/#" with regex /^mqtt\.0\.thermometer\..*/ 

mqtt.0 2018-06-19 14:18:00.013 info Client [ESPClient0] subscribes on "/thermometer/#" with regex /^thermometer\..*/ 

mqtt.0 2018-06-19 14:18:00.004 info Client [ESPClient0] reconnected. Old secret 1529410641752_6519. New secret 1529410680003_8852 
`
Als MQTT client nutze ich eine NodeMCU mit ESP Easy und als MQTT Protocoll "OpenHAB MQTT"

**Comment by GermanBluefox** [comment]
Da dein ESP baut 2 Verbindungen auf. ioBroker kann nichts dafür. 
Oder du hast 2 gleiche Client IDs

**Comment by GermanBluefox** [comment]
ok
