### ISSUE TITLE
Typ error with JS Controller 3.3

### ISSUE THREAD

**Issue by ReinWei56** [ioBroker/ioBroker.mqtt#203]
**Describe the bug**  

Habe den Adapter nach dem Update des Js Contoller installiert

**Versions:**  
 - Adapter version: 2.4.0
 - JS-Controller version: 3.3.15
 - Node version: 12.22.4
 - Operating system: linux

**Additional context**  
log nur ein Ausschnitt:
<html><body>

qtt.0 | 2021-09-17 11:50:07.685 | info | State value to set for "mqtt.0.openWB.evu.DailyYieldImportKwh" has to be type "string" but received type "number"
-- | -- | -- | --
mqtt.0 | 2021-09-17 11:30:08.961 | info | State value to set for "mqtt.0.openWB.evu.DailyYieldImportKwh" has to be type "string" but received type "number"
mqtt.0 | 2021-09-17 11:10:08.886 | info | State value to set for "mqtt.0.openWB.evu.DailyYieldImportKwh" has to be type "string" but received type "number"
mqtt.0 | 2021-09-17 10:45:08.246 | info | State value to set for "mqtt.0.openWB.evu.DailyYieldImportKwh" has to be type "string" but received type "number"
mqtt.0 | 2021-09-17 10:05:08.304 | info | State value to set for "mqtt.0.openWB.evu.DailyYieldImportKwh" has to be type "string" but received type "number"
mqtt.0 | 2021-09-17 09:50:08.806 | info | State value to set for "mqtt.0.openWB.evu.DailyYieldImportKwh" has to be type "string" but received type "number"
mqtt.0 | 2021-09-17 09:35:09.067 | info | State value to set for "mqtt.0.openWB.housebattery.DailyYieldImportKwh" has to be type "number" but received type "string"
mqtt.0 | 2021-09-17 09:30:08.213 | info | State value to set for "mqtt.0.openWB.housebattery.DailyYieldImportKwh" has to be type "number" but received type "string"
mqtt.0 | 2021-09-17 09:25:08.132 | info | State value to set for "mqtt.0.openWB.housebattery.DailyYieldImportKwh" has to be type "number" but received type "string"
mqtt.0 | 2021-09-17 09:20:07.619 | info | State value to set for "mqtt.0.openWB.housebattery.DailyYieldImportKwh" has to be type "number" but received type "string"
mqtt.0 | 2021-09-17 09:15:08.302 | info | State value to set for "mqtt.0.openWB.housebattery.DailyYieldImportKwh" has to be type "number" but received type "string"
mqtt.0 | 2021-09-17 09:10:08.263 | info | State value to set for "mqtt.0.openWB.housebattery.DailyYieldImportKwh" has to be type "number" but received type "string"
m

</body>
</html>

**Comment by Apollon77** [comment]
Bitte betroffene Objekte mal löschen und adapter neu starten

**Comment by ReinWei56** [comment]
Habe ich gerne gemacht obwohl ich den adapter erst nach dem update des js Controllers installiert hatte, es hat an der Situation auch nicht geändert, die Meldungen kommen weitderhin

**Comment by DocGame69** [comment]
Wurde das Problem weiterverfolgt?
Bei mir ist das selbe...
`
<html><body>


mqtt.0 | 2021-10-02 23:17:13.709 | info | (3670) State value to set for  "mqtt.0.lolin-esphometest.sensor.ultraschallsensor.state" has to be type  "number" but received type "string"
-- | -- | -- | --
mqtt.0 | 2021-10-02 23:17:08.698 | info | (3670) State value to set for  "mqtt.0.lolin-esphometest.sensor.ultraschallsensor.state" has to be type  "number" but received type "string"
mqtt.0 | 2021-10-02 23:17:03.713 | info | (3670) State value to set for  "mqtt.0.lolin-esphometest.sensor.ultraschallsensor.state" has to be type  "number" but received type "string"
mqtt.0 | 2021-10-02 23:16:58.703 | info | (3670) State value to set for  "mqtt.0.lolin-esphometest.sensor.ultraschallsensor.state" has to be type  "number" but received type "string"
mqtt.0 | 2021-10-02 23:16:53.699 | info | (3670) State value to set for  "mqtt.0.lolin-esphometest.sensor.ultraschallsensor.state" has to be type  "number" but received type "string"
mqtt.0 | 2021-10-02 23:16:48.698 | info | (3670) State value to set for  "mqtt.0.lolin-esphometest.sensor.ultraschallsensor.state" has to be type  "number" but received type "string"
mqtt.0 | 2021-10-02 23:16:43.711 | info | (3670) State value to set for  "mqtt.0.lolin-esphometest.sensor.ultraschallsensor.state" has to be type  "number" but received type "string"
mqtt.0 | 2021-10-02 23:16:38.693 | info | (3670) State value to set for  "mqtt.0.lolin-esphometest.sensor.ultraschallsensor.state" has to be type  "number" but received type "string"
mqtt.0 | 2021-10-02 23:16:33.686 | info | (3670) State value to set for  "mqtt.0.lolin-esphometest.sensor.ultraschallsensor.state" has to be type  "number" but received type "string"
mqtt.0 | 2021-10-02 23:16:28.726 | info | (3670) State value to set for  "mqtt.0.lolin-esphometest.sensor.ultraschallsensor.state" has to be type  "number" but received type "string"
mqtt.0 | 2021-10-02 23:16:23.693 | info | (3670) State value to set for  "mqtt.0.lolin-esphometest.sensor.ultraschallsensor.state" has to be type  "number" but received type "string"
mqtt.0 | 2021-10-02 23:16:18.695 | info | (3670) State value to set for  "mqtt.0.lolin-esphometest.sensor.ultraschallsensor.state" has to be type  "number" but received type "string"


</body>
</html>`

**Comment by Apollon77** [comment]
Could it be that the message switches type? Else try to delete the objects and they should be recreated with correct type according to first received message

**Comment by Apollon77** [comment]
Upcoming 2.6.0 (once https://github.com/ioBroker/ioBroker.mqtt/pull/256 is merged) should also fix that automatically
