### ISSUE TITLE
Adapter bleibt gelb bei Verbindung mit openWB

### ISSUE THREAD

**Issue by Gerti1972** [ioBroker/ioBroker.mqtt#209]
Ich setze den Adapter mit meiner OpenWB ein.
Starte ich den Adapter, werden alle drei Schritte grün und nach einem Augenblick wird der letzte wieder rot.
Der Adapter selbst zeigt dann ein gelbes Dreieck und grundsätzlich funktioniert auch anscheinend alles völlig korrekt. Neue Daten der openWB kommen regelmäßig rein und ich kann über den Adapter die openWB auch steuern.
Im Forum von openWB liest man von vielen Usern mit dieser Konstellation, das der Adapter bei der Verbindung mit openwB gelb bleibt, obwohl alles korrekt funktioniert.
Er war bei mir auch schon mal grün (wird es seit einem Neustart des iobroker aber nicht mehr), bei einigen wurde er nach einigen Tagen von selbst grün, andere berichten von zwei identischen Installationen vom iobroker, die beide auf dieselbe openWB zugreifen und von denen eine grün, die andere gelb ist.
Da es grundsätzlich alles funktioniert, scheint für mich hier irgendwie die Erkennung der korrekten Datenübertragung nicht zu funktionieren.

**Comment by Apollon77** [comment]
Bitte Adapter auf debug loglevel stellen und Log posten

**Comment by Apollon77** [comment]
I can not see any reasy why he should re-set the connected status ... strange. Please try again with 2.5.0

**Comment by Gerti1972** [comment]
Der Fehler tritt wohl immer auf, wenn der iobroker neu gestartet wird. Starte ich anschließend die Openwb auch neu, bleibt der Adapter auf grün.
Grundsätzlich funktioniert ja auch mit gelb alles völlig korrekt, trotzdem ist es seltsam.

**Comment by Apollon77** [comment]
Or even better: Try Github version please. Should also state 2.5.0 but is in fact way more and will be 2.6.0 soon. Then new log with it please. And manual restart adater after github update please

**Comment by Apollon77** [comment]
Please use 2.6.0 for new log

**Comment by Gerti1972** [comment]
Anbei das neue Logfile mit der 2.6.1
Nach dem Neustart des Adapters wird er wieder gelb.
Starte ich dann die OpenWB neu, wird er von selbst wieder grün.
Das sollte alles in diesem Log festgehalten sein:
[logfile.txt](https://github.com/ioBroker/ioBroker.mqtt/files/8144809/logfile.txt)

Nachdem ich den Loglevel danach wieder auf info umgestellt und der Adapter neu gestartet ist, war er wieder gelb.
Ein erneuter Neustart der OpenWB hat ihn dann wieder grün werden lassen.

**Comment by Apollon77** [comment]
Bitte zeige mal die Konfig als Screenshot und bitte auch in der mqtt.0 Adapter Konfig das extra Debug was dort ist aktivieren. Dann nochmal los senden

**Comment by Gerti1972** [comment]
Hallo,

anbei das Logfile und die Screenshots.

[log.txt](https://github.com/ioBroker/ioBroker.mqtt/files/8208147/log.txt)
![screencapture-192-168-2-20-8081-2022-03-08-17_53_50](https://user-images.githubusercontent.com/23507936/157287653-20344feb-1344-43d1-b3f5-c7e0dc2b2b5c.png)
![screencapture-192-168-2-20-8081-2022-03-08-17_53_16](https://user-images.githubusercontent.com/23507936/157287673-eda4e9b5-13ca-43b3-b447-ca47733e7cc3.png)

Gruß,
Gerti

**Comment by Apollon77** [comment]
hehe, wie ich es vermutet habe ... sich mal im Log nach "connection" ... Du subscribes "mqtt.0" im Adapter ... daher published der server die mqtt.0.info.connection = false ... und der server sendet es zurück und damit überschreibt er den Wert ... Ich baue mal ein das der eine Wert nicht geschrieben werden darf.

Bitte GitHub version versuchen
