### ISSUE TITLE
Die Channels werden nicht richtig angelegt 

### ISSUE THREAD

**Issue by MarkSau** [ioBroker/ioBroker.mqtt#210]
Nach Aussage des Jarvis Adapter Entwicklers werden die Channels nicht richtig angelegt.

Siehe dazu #https://github.com/Zefau/ioBroker.jarvis/issues/1077

Ohne die korrekte Konfig der Objekte bzw. Folder findet der Jarvis Adapter keines der "Geräte" bzw. States.

**Comment by Apollon77** [comment]
check 2.6.0
