### ISSUE TITLE
mqtt log other drivers

### ISSUE THREAD

**Issue by saykl** [ioBroker/ioBroker.mqtt#211]
Bug in screenshot.
![mqttЛог](https://user-images.githubusercontent.com/30440331/136697891-bb665615-6134-4ee3-8e1f-08a42348512e.png)
Russian:
В лог драйвер mqtt пишет все объекты, которые вообще у меня существуют Я только для drivent включил mqtt. Но в логах mqtt.2 отображает, то что не относится к mqtt

Например:

<html>
<body>

mqtt.2 | 2021-10-10 16:28:00.213 | info | send2Server zigbee.0.00124b00226781dd.state[zigbee/0/00124b00226781dd/state]
-- | -- | -- | --
mqtt.2 | 2021-10-10 16:26:00.907 | info | send2Server javascript.0.TVRainFeed.Tabelle[javascript/0/TVRainFeed/Tabelle]
mqtt.2 | 2021-10-10 16:20:03.434 | info | send2Server javascript.0.TVRainFeed.Tabelle[javascript/0/TVRainFeed/Tabelle]
mqtt.2 | 2021-10-10 16:15:56.259 | info | send2Server system.adapter.coronavirus-statistics.0.connected[system/adapter/coronavirus-statistics/0/connected]
mqtt.2 | 2021-10-10 16:14:52.508 | info | send2Server javascript.0.Speed-Test.data.server.ping[javascript/0/Speed-Test/data/server/ping]
mqtt.2 | 2021-10-10 16:14:52.409 | info | send2Server javascript.0.Speed-Test.data.speeds.orginalUpload[javascript/0/Speed-Test/data/speeds/orginalUpload]
mqtt.2 | 2021-10-10 16:14:52.401 | info | send2Server javascript.0.Speed-Test.data.speeds.orginalDownload[javascript/0/Speed-Test/data/speeds/orginalDownload]
mqtt.2 | 2021-10-10 16:14:52.389 | info | send2Server javascript.0.Speed-Test.data.speeds.upload[javascript/0/Speed-Test/data/speeds/upload]
mqtt.2 | 2021-10-10 16:14:52.380 | info | send2Server javascript.0.Speed-Test.data.speeds.download[javascript/0/Speed-Test/data/speeds/download]
mqtt.2 | 2021-10-10 16:14:52.372 | info | send2Server javascript.0.Speed-Test.ping[javascript/0/Speed-Test/ping]
mqtt.2 | 2021-10-10 16:14:52.363 | info | send2Server javascript.0.Speed-Test.json[javascript/0/Speed-Test/json]
mqtt.2 | 2021-10-10 16:14:46.708 | info | send2Server broadlink2.0.bathroom[broadlink2/0/bathroom]
mqtt.2 | 2021-10-10 16:12:43.540 | info | send2Server broadlink2.0.bathroom[broadlink2/0/bathroom]
mqtt.2 | 2021-10-10 16:12:18.360 | info | send2Server zigbee.0.00124b00226781dd.state[zigbee/0/00124b00226781dd/state]
mqtt.2 | 2021-10-10 16:10:50.799 | info | send2Server javascript.0.hallwayLight.MotionOn[javascript/0/hallwayLight/MotionOn]
mqtt.2 | 2021-10-10 16:10:50.792 | info | send2Server javascript.0.hallwayLight.MotionOn[undefined]
mqtt.2 | 2021-10-10 16:10:50.785 | info | send2Server zigbee.0.00124b00226781dd.state[zigbee/0/00124b00226781dd/state]
mqtt.2 | 2021-10-10 16:10:50.633 | info | send2Server javascript.0.hallwayLight[javascript/0/hallwayLight]
mqtt.2 | 2021-10-10 16:10:50.622 | info | send2Server javascript.0.hallwayLight[undefined]
mqtt.2 | 2021-10-10 16:07:59.573 | info | send2Server zigbee.0.00124b00226781dd.state[zigbee/0/00124b00226781dd/state]
mqtt.2 | 2021-10-10 16:07:59.543 | info | send2Server zigbee.0.00124b00226781dd.state[undefined]

</body>
</html>

Багу несколько лет.

**Comment by Apollon77** [comment]
In fact "send2Server" should mean the other patternlist that is subscribed ... please try again with recent versionsnand pot post new log

**Comment by GermanBluefox** [comment]
Please test 4.0.0
