### ISSUE TITLE
Ensure correct formatting of numbers (0.1 instead of .1)

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.mqtt#212]
As discussed in dev channel, some sources provide incorrect number formatting (like OpenWB, see issue at SourceAnalytix.

Garbo so already investigate this line of code, we suggest a Regex see feedback of @Apollon77 

https://github.com/ioBroker/ioBroker.mqtt/blob/master/lib/server.js#L559

würde daher ehrlich spezifisch wenn diesen fall abfangen mit "entweder parsed und original ist "==" oder "\.[0-9]+"

This should solve the issue as detected by an user of SourceAnalytiX

https://github.com/DrozmotiX/ioBroker.sourceanalytix/issues/468

**Comment by Apollon77** [comment]
The adapter can not differentiate between a ".whatever" as string or ".1" as "0.1", so a nummer with a mising 0 ... sorry ... mno idea how to handle that generically ... OpenWB needs to send correct values - or the user needs to conbvert the values using alias or Javascript ..
