### ISSUE TITLE
Fehler im Objektbaum, kein Senden möglich

### ISSUE THREAD

**Issue by Starter4711** [ioBroker/ioBroker.mqtt#213]
V2.4.0

ist im go-e chargere app read only deaktiviert, zeigt sich im Objektbaum ein Fehler
ein Wert wird nicht geschrieben, dh eine Eingabe wird nicht zur go-e Box übergeben.

<img width="1235" alt="Bildschirmfoto 2021-10-24 um 11 48 15" src="https://user-images.githubusercontent.com/15359915/138597471-c79d9533-8d69-4271-bd07-9c15bbaae454.png">
<img width="1209" alt="Bildschirmfoto 2021-10-24 um 11 50 44" src="https://user-images.githubusercontent.com/15359915/138597475-042de683-763d-4c6d-8002-b416dc738809.png">

**Comment by Apollon77** [comment]
Please provide a debug log ... and inm fcat I do not understand the issue ...?! Is it about the error mesaage in the first post? Seems that a datafield is an invalid json. We need more details

**Comment by Starter4711** [comment]
Debug log is empty, no entry during changing the value. Via mqtt.fx it is possible to write a value on amp.
Via objects in ioBroker it does not work, the set value is not transmitted, seams to be a fault on data declaration.
Can you read german? did you look into the linked iobroker thread?
thx

**Comment by Apollon77** [comment]
Ja ich verstehe auch Deutsch, und auch der Thread hilft mir nicht weiter. Erkläre es mir wie jemandem der keine Ahnung von MQTT hat :-) Und "Debug log ist empty" kann an sich nicht sein ... Zur sicherheit: Admin, Expertenmodus aktivieren, Instanzen, mqtt.0 aufklappen. Loglevel von info auf debug ändern ... dann im Log schauen

**Comment by Starter4711** [comment]
Habs wieder aktiviert und nachgestellt.
Im Objektbaum setze ich SET von amp auf 10 oder 11
[debug.pdf](https://github.com/ioBroker/ioBroker.mqtt/files/8141087/debug.pdf)
<img width="1367" alt="Bildschirmfoto 2022-02-25 um 13 21 12" src="https://user-images.githubusercontent.com/15359915/155714993-d1047eb1-5c1c-4819-9aab-84b011ab0ebf.png">

**Comment by Starter4711** [comment]
[debut.txt](https://github.com/ioBroker/ioBroker.mqtt/files/8143191/debut.txt)

**Comment by Apollon77** [comment]
Ok, the log shows the following:
* you changes value to 10 where it was 10 already before ... this is not seen as change and so not send out. YOu can change the config to always send out values also if unchanged.
* your change with "12\n" was seen as change and should also had been sent out but most likely rejected invalid and so ignored
I also saw some cases where you set the vlues with ack-flag (Bestätigt) from Admin ... with this you make chaos in the logic as described above, so do not do that!

makes that sense?

So please check again.

**Comment by Starter4711** [comment]
Yes, that way around.

Today it works as it should, don't know why?
[iobroker.current.log](https://github.com/ioBroker/ioBroker.mqtt/files/8146036/iobroker.current.log)

I open the input window on clicking the value.
<img width="238" alt="Bildschirmfoto 2022-02-26 um 07 09 47" src="https://user-images.githubusercontent.com/15359915/155832395-67d6354c-6832-40fa-a029-7b0dc3a97a60.png">
<img width="1315" alt="Bildschirmfoto 2022-02-26 um 07 10 33" src="https://user-images.githubusercontent.com/15359915/155832396-a75282f4-4568-4b42-9a6c-7454d3f5774f.png">

**Comment by Apollon77** [comment]
then we can close here?

**Comment by Starter4711** [comment]
I don‘t know what has changed that it works right now. 
Will try a view days, after and it works, it van be closed of course. 
But selfhealing is unlikely.

**Comment by Apollon77** [comment]
:-) Please make sure to never set state with ack/bestätigt=true
