### ISSUE TITLE
Object of state is missing the required property "common.type"

### ISSUE THREAD

**Issue by gidhap** [ioBroker/ioBroker.mqtt#214]
Im Bestreben das Log sauber zu bekommen ist mir folgende Meldung aufgefallen
`<html>
<body>

mqtt.1 | 2021-10-31 10:50:27.191 | warn | Object of state "mqtt.1.solaranzeige.box1.batterie_ladung" is missing the required property "common.type"
-- | -- | -- | --

</body>
</html>
`
Ist "nur" warning, kann ich das einfach ignorieren oder muss/kann ich da selbst was fixen?

**Comment by Apollon77** [comment]
Please delete the object so that it gets recreated ... does it then still happen?

**Comment by Apollon77** [comment]
Upcoming 2.6.0 (once https://github.com/ioBroker/ioBroker.mqtt/pull/256 is merged) should also fix that automatically

**Comment by Gatam4U** [comment]
Object of state "mqtt.0.shellies.shellyplug-s-E3ED15.relay.0" is missing the required property "common.type"
After I switched the MQTT Broker in Shelly Plug S. Away from Shelly Adapter to MQTT Adapter.

MQTT Version 3.06

I delete all objects but still get the same issue.

**Comment by Apollon77** [comment]
Current mqtt Beta is at 4.x and it is already fixed there ...
