### ISSUE TITLE
MQTT Server/broker startet nicht

### ISSUE THREAD

**Issue by DeSpo0108** [ioBroker/ioBroker.mqtt#22]
Hallo,

ich möchte für die Kommunikation mit einer NodeMCU einen MQTT Server auf meiner ioBroker Raspberry betreiben. Jetzt habe ich den Adapter MQTT Server/broker installiert und die Instanz als Server/broker und Standardeinstellungen versucht zu starten.

Jedoch spuckt der Log immer die gleichen fehler aus:

host.ioBroker-Pi | 2018-08-23 22:44:48.129 | info | Restart adapter system.adapter.mqtt.0 because enabled
-- | -- | -- | --
host.ioBroker-Pi | 2018-08-23 22:44:48.128 | error | instance system.adapter.mqtt.0 terminated with code 0 (OK)
Caught | 2018-08-23 22:44:48.128 | error | by controller[0]: at Connection.emit (events.js:211:7)
Caught | 2018-08-23 22:44:48.128 | error | by controller[0]: at emitOne (events.js:116:13)
Caught | 2018-08-23 22:44:48.128 | error | by controller[0]: at Object.onceWrapper (events.js:315:30)
Caught | 2018-08-23 22:44:48.128 | error | by controller[0]: at Connection.<anonymous> (/opt/iobroker/node_modules/mqtt-connection/connection.js:53:12)
Caught | 2018-08-23 22:44:48.128 | error | by controller[0]: at Connection.emit (events.js:211:7)
Caught | 2018-08-23 22:44:48.128 | error | by controller[0]: at emitOne (events.js:116:13)
Caught | 2018-08-23 22:44:48.127 | error | by controller[0]: at Connection.emitPacket (/opt/iobroker/node_modules/mqtt-connection/connection.js:10:8)
Caught | 2018-08-23 22:44:48.127 | error | by controller[0]: at Connection.emit (events.js:211:7)
Caught | 2018-08-23 22:44:48.127 | error | by controller[0]: at emitOne (events.js:116:13)
Caught | 2018-08-23 22:44:48.127 | error | by controller[0]: at Connection.client.on.packet (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:839:34)
Caught | 2018-08-23 22:44:48.126 | error | by controller[0]: TypeError: Cannot read property 'forEach' of undefined
mqtt.0 | 2018-08-23 22:44:48.087 | info | terminating
mqtt.0 | 2018-08-23 22:44:47.576 | error | at Connection.emit (events.js:211:7)
mqtt.0 | 2018-08-23 22:44:47.576 | error | at emitOne (events.js:116:13)
mqtt.0 | 2018-08-23 22:44:47.576 | error | at Object.onceWrapper (events.js:315:30)
mqtt.0 | 2018-08-23 22:44:47.576 | error | at Connection.<anonymous> (/opt/iobroker/node_modules/mqtt-connection/connection.js:53:12)
mqtt.0 | 2018-08-23 22:44:47.576 | error | at Connection.emit (events.js:211:7)
mqtt.0 | 2018-08-23 22:44:47.576 | error | at emitOne (events.js:116:13)
mqtt.0 | 2018-08-23 22:44:47.576 | error | at Connection.emitPacket (/opt/iobroker/node_modules/mqtt-connection/connection.js:10:8)
mqtt.0 | 2018-08-23 22:44:47.576 | error | at Connection.emit (events.js:211:7)
mqtt.0 | 2018-08-23 22:44:47.576 | error | at emitOne (events.js:116:13)
mqtt.0 | 2018-08-23 22:44:47.576 | error | at Connection.client.on.packet (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:839:34)
mqtt.0 | 2018-08-23 22:44:47.576 | error | TypeError: Cannot read property 'forEach' of undefined
mqtt.0 | 2018-08-23 22:44:47.574 | error | uncaught exception: Cannot read property 'forEach' of undefined

Habe es jetzt schon mehrfach mit neustart, neuinstallation (auch direkt von GitHub) und allen möglichen verschiedenen Einstellungen in der Instanz probiert leider ohne Erfolg.

Ich hoffe ihr könnt mir weiter Helfen und ich sage schon mal Danke für alle Antworten,

Gruß,
DeSpo0108

**Comment by Apollon77** [comment]
Please check again with 2.0.4 from Github? Still happening?

**Comment by MrMadracer** [comment]
I have the same issue and same log file errors. I´m on 2.0.4.

**Comment by Carmenpl** [comment]
Ich habe mit allen Versionen das gleiche Problem,
und nach etwas recherche siehe da IPV6 und Ports klappt nicht
netstat -a | grep 1883
tcp6       0      0 [::]:<font color="#EF2929"><b>1883</b></font>               [::]:*                  LISTEN

Hat jemand eine idee für einen Workaround ?

**Comment by aleks-83** [comment]
With adapter 2.0.4 i had the same issue.
Now with 2.1.1 it is gone.

The LED status is still yellow because of "no connection to mqtt" but this seems to be another issue.
I just installed this adapter for the first time.

**Comment by bjoernbusch** [comment]
Ich habe das gleiche Problem, gibt es eine Chance, dass jemand Zeit hat, das mal zu debuggen?

**Comment by bjoernbusch** [comment]
Wenn ich vor dem foreach ein _if(client._messages)_ einfüge, crashed der Adapter wenigstens nicht mehr. Wieso das messages array aber nicht initialisiert ist, verstehe ich nicht.

**Comment by Apollon77** [comment]
@bjoernbusch Danke für die Lösungsidee, geht es denn trotzdem alles? Wenn ja wäre das eine Simple lösung

**Comment by bjoernbusch** [comment]
Also soweit ich das beurteilen kann, gehen die Sachen, die ich verwende immernoch. Das Problem tritt aber bei mir nur auf, wenn ich über Websockets zugreife, also irgendwie ist da das Verhalten vom Client anders. Auch wenn das _messages array ja eigentlich immer in `startServer` initialisiert wird.
