### ISSUE TITLE
Obwohl sich der Wert eines States nicht ändert wird der Wert alle ca. 30Sek zum Server gesendet.

### ISSUE THREAD

**Issue by effello** [ioBroker/ioBroker.mqtt#227]
Obwohl sich der Wert eines States nicht ändert wird eine Nachricht ca. alle 30 Sekunden zum mqtt Server publiziert. 
Ich habe bereits versucht einen Haken bei "ändert sich nur" zu setzten, jedoch hat das keine Änderung zu folge

Wie ist es möglich wirklich nur bei Änderung des Wertes eine Nachricht zu senden?

 - Adapter version: 1.4.0

**Comment by Apollon77** [comment]
Bitte Loglevel auf Debug stellen und Log ansehen bzw zeigen ...

**Comment by effello** [comment]
Es sieht aus als würde sich der adapter von selber resetten und neu starten ??
![log](https://user-images.githubusercontent.com/8028591/145811774-0a9d973c-ad51-4393-8aab-fd8e9185d239.png)
?

**Comment by effello** [comment]
Es sieht aus als würde sich er Adapter von selbst ständig resetten und neu starten ???
![log](https://user-images.githubusercontent.com/8028591/145812243-e3117935-5290-4c83-87a8-391894464d0b.png)

**Comment by Apollon77** [comment]
Wenn DU das aus diesem Log Teil als Screenshot rausliesst siehst Du mehr als ich ... Wäre ja aweseome das in vollständig und textform zu haben :-)

**Comment by effello** [comment]
[iobroker.2021-12-13.log](https://github.com/ioBroker/ioBroker.mqtt/files/7704399/iobroker.2021-12-13.log)
Gerne doch!
Ich ziehe meine erste Vermutung zurück! ;-) Wundere mich eher warum es ein erneutes "publish" eines Datenpunkts gibt obwohl der wert sich nicht geändert hat. z.B. "*/setting.temperature" (Ein sollwert der sich innerhalb dieses Zeitpunkts nicht änderte).

**Comment by Apollon77** [comment]
Ok, drei Dinge dazu :-)

1.) müsste das Issue nicht im "mqtt-client" adapter sein ... das hier ist der mqtt adapter :-)
2.) leider nur "Info" log. Debug Log: Admin - Expertemnodus aktivieren - Instanzen - Loglevel bei der Inatnz auf "debug" stellen (von info)
3.) Wie schaffst Du es das als HTML zu kriegen ... krass :-)) Logfile wäre auf der Platte unter /op/iobroker/log/...

**Comment by effello** [comment]
1. Sorry mein Fehler!
2. werde drüben nachfragen bzw. gleich euren adapter mal testen :-)
3. Wenn ich diesen Knopf "Log Herunterladen" drücke öffnet sich wie von Geisterhand ein Tab was den Log als HTML enthält ...Farblich!!! :-0 Fands nicht falsch ;-)
![logb](https://user-images.githubusercontent.com/8028591/145831359-8e88b6a9-efc1-4bc4-bdf9-12c91cd187b5.png)
