### ISSUE TITLE
Adapter läuft nicht stabiel

### ISSUE THREAD

**Issue by xxa92** [ioBroker/ioBroker.mqtt#23]
Hallo
Mein Adapter verbindet sich in einer Sekunde mehrmals neu.

mqtt.0 | 2018-09-22 18:54:53.055 | info | Connected to 192.168.2.106
-- | -- | -- | --
mqtt.0 | 2018-09-22 18:54:53.031 | info | Disconnected from 192.168.2.106
mqtt.0 | 2018-09-22 18:54:53.009 | info | Connected to 192.168.2.106
mqtt.0 | 2018-09-22 18:54:52.985 | info | Disconnected from 192.168.2.106
mqtt.0 | 2018-09-22 18:54:52.963 | info | Connected to 192.168.2.106
mqtt.0 | 2018-09-22 18:54:52.941 | info | Disconnected from 192.168.2.106
mqtt.0 | 2018-09-22 18:54:52.919 | info | Connected to 192.168.2.106
mqtt.0 | 2018-09-22 18:54:52.897 | info | Disconnected from 192.168.2.106
mqtt.0 | 2018-09-22 18:54:52.875 | info | Connected to 192.168.2.106
mqtt.0 | 2018-09-22 18:54:52.853 | info | Disconnected from 192.168.2.106
mqtt.0 | 2018-09-22 18:54:52.832 | info | Connected to 192.168.2.106
mqtt.0 | 2018-09-22 18:54:52.810 | info | Disconnected from 192.168.2.106
mqtt.0 | 2018-09-22 18:54:52.788 | info | Connected to 192.168.2.106
mqtt.0 | 2018-09-22 18:54:52.766 | info | Disconnected from 192.168.2.106

und das ständig

Habe schon ein neues System aufgesetzt und auch ältere Versionen probiert.

Was kann ich tun?

Danke schon mal für hilfe

**Comment by GermanBluefox** [comment]
Nicht Adapter läuft nicht stabil, sondern dein Client verbindet sich unstabil.

Hast du mehr Info? esp8266?

**Comment by xxa92** [comment]
Der MQTT Server läuft auf einem anderen Pi.
Dort kommen werte von Sonoffs, ESPs, Node Red und FHEM rein und das läuft alles seit längerem.
Wenn ich nun mit IoBroker mich anmelden will geht nichts mehr und nur vereinzelnd.

Es ist kein Passwort oder so drinne

ein paar werte gehen auch noch durch und auf einem anderem System ging es.
(Sind auch 2 verschiedene IDs)

dort aber noch mit dauernd gelb leuchtend aber keine probleme

**Comment by PrivatHomeServer** [comment]
Bin relativ neu bei iobroker und komme von hass.io. Hier habe ich aktuell auch noch zwei PIs auf denen ich MQTT Broker laufen habe. Bei mir geschieht im Endeffekt genau das selbe Verhalten (gelb/grün) und htop liefert mir astronomische CPU Werte wenn ich MQTT starte. MQTT client 2.0.2 und 2.0.0 getestet. Leider findet sich die Lösung nicht so einfach. Jemand noch ein Lösungsansatz für uns? Danke!

**Comment by GermanBluefox** [comment]
@xxa92 Kann es sein, dass du ALLE Events an dein MQTT Broker sendest und Broker ist einfach überlastet?
ioBroker kann schon VIEL senden wenn das auch gewollt ist. 
Sicher, dass "sende am start" nicht aktiviert ist? Dass kein "*" bei Pattern steht?

**Comment by xxa92** [comment]
ja das wars anscheinend danke ;)
