### ISSUE TITLE
ioB unter Windows - seit letztem Win Update MQTT Warnung

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.mqtt#230]
Bei mir läuft ioB unter Windows10. Microsoft hat die Tage mehrere Updates ausgerollt, welche auch einen PC Neustart nach sich gezogen haben. PC Neustart bedeutet somit auch ioB Neustart.

Die Tage wurde ja auch der MQTT Adapter auf die Version 2.4.1 angehoben. Eigentlich lief nach dem Adapter Update alles normal. Nun, nach dem Windows und somit auch ioBroker Neustart, bekommt der MQTT Adapter keine Verbindung mehr zu den Geräten.

Ob das  nun an dem Windows Update oder an dem MQTT Adapter Update liegt, vermag ich nicht zu sagen.

Außer "einem Sack voll" falscher Typ Meldungen (siehe unten) gibt das Debug keine weiteren Fehlermeldungen aus.

MQTT Broker/Client 2.4.1
Admin 5.2.1
js-controller 3.3.21

Ich habe auch den Adapter auf Version 2.3.5 zurück gerollt, aber das Phänomen bleibt das gleiche. Alle MQTT Instanzen bleiben im Warnmodus und haben keine Verbindung zum Gerät - evtl. doch ein  Win Problem?

EDIT: Ich habe jetzt nochmal ein bisschen herum probiert. Augenscheinlich funktioniert die Kommunikation mit den Geräten und es werden Werte in die Objekte geschrieben. Leider wird aber der info Datenpunkt auf False gesetzt. Ich habe genau diesen info Datenpunkt in der VIS als Trigger für ein "Gerät verbunden" Icon auf die Funktion sichtbar/unsichtbar gelegt. Dadurch das der DP auf False steht, wird in der VIS das Gerät natürlich als nicht erreichbar / Funktionstüchtig angezeigt.

![image](https://user-images.githubusercontent.com/44617472/146502367-60a602fe-fad8-4d9d-837e-decb1442cbe1.png)

<html>
<body>

mqtt.2 | 2021-12-17 07:48:02.660 | info | State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has to be type "string" but received type "number"
-- | -- | -- | --
mqtt.2 | 2021-12-17 07:47:52.657 | info | State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has to be type "string" but received type "number"
mqtt.2 | 2021-12-17 07:47:46.108 | info | State value to set for "mqtt.2.openWB.set.lp.1.%Soc" has to be type "number" but received type "string"
mqtt.2 | 2021-12-17 07:47:46.042 | info | State value to set for "mqtt.2.openWB.set.lp.1.ForceSoCUpdate" has to be type "number" but received type "string"
mqtt.2 | 2021-12-17 07:47:46.027 | info | State value to set for "mqtt.2.openWB.config.set.sofort.lp.1.socToChargeTo" has to be type "number" but received type "string"
mqtt.2 | 2021-12-17 07:47:46.025 | info | All states published
mqtt.2 | 2021-12-17 07:47:45.958 | info | State value to set for "mqtt.2.openWB.set.system.reloadDisplay" has to be type "number" but received type "string"
mqtt.2 | 2021-12-17 07:47:45.927 | info | State value to set for "mqtt.2.openWB.set.lp1.DirectChargeAmps" has to be type "number" but received type "string"
mqtt.2 | 2021-12-17 07:47:45.927 | info | State value to set for "mqtt.2.openWB.set.lp1.ChargePointEnabled" has to be type "boolean" but received type "string"
mqtt.2 | 2021-12-17 07:47:45.915 | info | State value to set for "mqtt.2.openWB.set.lp.1.manualSoc" has to be type "number" but received type "string"
mqtt.2 | 2021-12-17 07:47:45.906 | info | State value to set for "mqtt.2.openWB.set.lp.1.ChargePointEnabled" has to be type "number" but received type "string"
mqtt.2 | 2021-12-17 07:47:45.896 | info | State value to set for "mqtt.2.openWB.set.ChargeMode" has to be type "number" but received type "string"
mqtt.2 | 2021-12-17 07:47:45.799 | info | State value to set for "mqtt.2.openWB.lp.2.W" has to be type "number" but received type "string"

</body>
</html>

Heute Morgen habe ich dann doch noch zwei Fehler im LOG gefunden.

<html>
<body>

host.GLTGLT) |   | 2021-12-18 07:23:20.399 | warn | host.GLT(GLT) instance system.adapter.mqtt.2 terminated due to SIGTERM
-- | -- | -- | -- | --
host.GLTGLT) |   | 2021-12-18 07:22:43.529 | warn | host.GLT(GLT) instance system.adapter.mqtt.0 terminated due to SIGTERM

</body>
</html>

**Comment by Apollon77** [comment]
Could it be that it was just an not current info in admin? Is it stull an issue?

**Comment by JBSullivan** [comment]
Ja, es ist leider immer noch ein Problem, trotz Aktualisierung auf MQTT Adapter 2.5.0

<html>
<body>


Zeit | info | Nachricht
-- | -- | --
mqtt.2 | 2022-02-25 10:10:54.409 | info | State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:10:54.314 | info | State value to set for "mqtt.2.openWB.set.evu.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:10:53.279 | info | State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:10:53.127 | info | State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:10:34.498 | info | State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:10:34.417 | info | State value to set for "mqtt.2.openWB.set.evu.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:10:33.361 | info | State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:10:33.207 | info | State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:10:13.810 | info | State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:10:13.751 | info | State value to set for "mqtt.2.openWB.set.evu.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:10:12.571 | info | State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:10:12.406 | info | State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:09:53.793 | info | State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:09:53.694 | info | State value to set for "mqtt.2.openWB.set.evu.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:09:52.606 | info | State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:09:52.482 | info | State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:09:33.783 | info | State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:09:33.726 | info | State value to set for "mqtt.2.openWB.set.evu.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:09:32.538 | info | State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:09:32.383 | info | State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:09:14.110 | info | State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:09:14.051 | info | State value to set for "mqtt.2.openWB.set.evu.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:09:12.952 | info | State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:09:12.793 | info | State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:08:54.217 | info | State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:08:54.216 | info | State value to set for "mqtt.2.openWB.set.evu.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:52.929 | info | State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:08:52.928 | info | State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:08:49.224 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.Device1.device_manual_control" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:49.219 | info | All states published
mqtt.2 | 2022-02-25 10:08:49.217 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.Devices.1.device_homeConsumtion" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:49.196 | info | State value to set for "mqtt.2.openWB.set.evu.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:49.154 | info | State value to set for "mqtt.2.openWB.set.system.reloadDisplay" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:49.136 | info | State value to set for "mqtt.2.openWB.set.lp1.DirectChargeAmps" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:49.127 | info | State value to set for "mqtt.2.openWB.set.lp1.ChargePointEnabled" has to be type "boolean" but received type "string"
mqtt.2 | 2022-02-25 10:08:49.100 | info | State value to set for "mqtt.2.openWB.set.lp.1.manualSoc" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:49.097 | info | State value to set for "mqtt.2.openWB.set.lp.1.ForceSoCUpdate" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:49.091 | info | State value to set for "mqtt.2.openWB.set.lp.1.ChargePointEnabled" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:49.086 | info | State value to set for "mqtt.2.openWB.set.lp.1.%Soc" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:49.071 | info | State value to set for "mqtt.2.openWB.set.evu.0.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:49.065 | info | State value to set for "mqtt.2.openWB.set.ChargeMode" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.991 | info | State value to set for "mqtt.2.openWB.lp.2.W" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.866 | info | State value to set for "mqtt.2.openWB.config.set.sofort.lp.1.socToChargeTo" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.866 | info | State value to set for "mqtt.2.openWB.config.set.sofort.lp.1.energyToCharge" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.855 | info | State value to set for "mqtt.2.openWB.config.set.sofort.lp.1.current" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.843 | info | State value to set for "mqtt.2.openWB.config.set.sofort.lp.1.chargeLimitation" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.829 | info | State value to set for "mqtt.2.openWB.config.set.pv.stopDelay" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.819 | info | State value to set for "mqtt.2.openWB.config.set.pv.startDelay" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.811 | info | State value to set for "mqtt.2.openWB.config.set.pv.socStopChargeAtMinPv" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.800 | info | State value to set for "mqtt.2.openWB.config.set.pv.socStartChargeAtMinPv" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.795 | info | State value to set for "mqtt.2.openWB.config.set.pv.priorityModeEVBattery" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.790 | info | State value to set for "mqtt.2.openWB.config.set.pv.minFeedinPowerBeforeStart" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.782 | info | State value to set for "mqtt.2.openWB.config.set.pv.minCurrentMinPv" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.776 | info | State value to set for "mqtt.2.openWB.config.set.pv.minBatteryDischargeSocAtBattPriority" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.769 | info | State value to set for "mqtt.2.openWB.config.set.pv.minBatteryChargePowerAtEvPriority" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.765 | info | State value to set for "mqtt.2.openWB.config.set.pv.maxPowerConsumptionBeforeStop" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.757 | info | State value to set for "mqtt.2.openWB.config.set.pv.lp.1.maxSocToChargeTo" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.754 | info | State value to set for "mqtt.2.openWB.config.set.pv.batteryDischargePowerAtBattPriority" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.747 | info | State value to set for "mqtt.2.openWB.config.set.global.maxEVSECurrentAllowed" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.744 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.maxBatteryPower" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.740 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.logLevel" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.734 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.Devices.1.mode" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.726 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.Devices.1.device_startupDetection" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.717 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.Devices.1.device_speichersocbeforestop" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.714 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.Devices.1.device_speichersocbeforestart" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.703 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.Devices.1.device_mineinschaltdauer" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.697 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.Devices.1.device_maxeinschaltdauer" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.684 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.Devices.1.device_einschaltverzoegerung" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.679 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.Devices.1.device_einschaltschwelle" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.672 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.Devices.1.device_differentMeasurement" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.667 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.Devices.1.device_deactivateWhileEvCharging" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.663 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.Devices.1.device_configured" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.657 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.Devices.1.device_canSwitch" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.656 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.Devices.1.device_ausschaltverzoegerung" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:48.650 | info | State value to set for "mqtt.2.openWB.config.set.SmartHome.Devices.1.device_ausschaltschwelle" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:47.535 | info | State value to set for "mqtt.2.openWB.evu.DailyYieldImportKwh" has to be type "string" but received type "number"
mqtt.2 | 2022-02-25 10:08:46.287 | info | State value to set for "mqtt.2.openWB.lp.1.TimeRemaining" has to be type "number" but received type "string"
mqtt.2 | 2022-02-25 10:08:45.811 | info | Subscribe on: "#"


</body>
</html>

**Comment by Apollon77** [comment]
Aahhh es geht um die Typ-Warnungen? Ja, die kommen vor wenn die gegenstelle keinen einheitlichen Datentyp sendet :-( Hier kommen scheinbar mal Strings und mal Zahlen und damit entsteht ein chaos :-( DU kannst die Objekte mal löschen, dann sollten soie neu korrekt angelegt werden ... dann mal schauen ob es wieder passiert

**Comment by JBSullivan** [comment]
Oh löschen .... :( ...... oder habt ihr in den neuen js-controller oder wo auch immer schon etwas drin, das die Benutzer definierten Einstellungen erhalten bleiben, so lange der Adapter nicht endgültig löscht wurde.

Gerade bei so großen Adapter (groß im Bezug auf die Anzahl der Datenpunkte), hat man (ich) doch dutzende DP`s mit Inlfuxdb oder sourceanalytix verknüpft. Das ist beim löschen ja auch immer alles weg und muss neu angelegt werden.

Das Thema hatte wir in der Vergangenheit ja schon öfter mal. Ist halt immer nervig, wenn man Objekte löscht, das dann alles wieder händisch Benutzer definiert eingestellt werden muss. Da vergisst man gerne mal was, was dann erst später in den Diagrammen  (Lücke) bemerkt wird.

Ganz davon abgesehen, das dass auch immer ein Hemmschuh ist, so eine Objekt Löschung mal schnell zu testen ;)

**Comment by Apollon77** [comment]
naja alternativ kannst duin den angemeckerten Objekten dn "common.type" selbst korrigieren ... Die Frageist ob danach ruhe ist oder ob das MQTT Gerät lustig hin und her wechselt

**Comment by Apollon77** [comment]
@JBSullivan STOP!! Wait ... I will implement somthing in the next version ... so stay tuned and you can check

**Comment by Apollon77** [comment]
Upcoming 2.6.0 (once https://github.com/ioBroker/ioBroker.mqtt/pull/256 is merged) should also fix that automatically

**Comment by Apollon77** [comment]
Ok, managed it ... it is in https://github.com/ioBroker/ioBroker.mqtt/pull/256

**Comment by Apollon77** [comment]
check 2.6.0

**Comment by JBSullivan** [comment]
Version 2.6.1 ist installiert, aber leider.....

![image](https://user-images.githubusercontent.com/44617472/155834517-31bea4df-c21c-4703-a2b0-f2316b2bb637.png)

**Comment by Apollon77** [comment]
Could I please see a debug log? (as text)

**Comment by Apollon77** [comment]
and better open a new issue. thx

**Comment by Apollon77** [comment]
AND: Please enable the additional debug in the adapter settings too
