### ISSUE TITLE
aus ioBroker ausgesperrt

### ISSUE THREAD

**Issue by stefanhoelscher** [ioBroker/ioBroker.mqtt#239]
Hallo an alle die helfen können, ich habe das gleiche Problem wie schon jemand anderes. Ich habe das Password in meiner Safari Passwortdatei überschrieben und komme nicht mehr in meinen iobroker rein. wenn ich hier was über developer Tools lese verstehe ich nur noch Bahnhof. Ich kann mir vorstellen das es für euch Profis sicherlich sehr müssig ist sich mit mir zu befassen, mit mir, einem der noch ganz am Anfang steht und noch kaum was weiß. Der braucht eine Schritt für Schritt Anleitung für "Doofe".
Ich würde mich sehr freuen, wenn ihr Zeit finden würdet, es mal einfach für Anfänger zu erklären.
Vielen Dank im voraus für die Mühen

**Comment by Apollon77** [comment]
Bitte hierzu am bestne im Forum melden ...
