### ISSUE TITLE
sendTo("mqtt.0", "sendMessage2Client", ... funktioniert nicht

### ISSUE THREAD

**Issue by Wally0** [ioBroker/ioBroker.mqtt#240]
Folgendes Ziel:
Ich möchte mit einem Skript ein Topic im MQTT-Broker erstellen, welches es noch nicht gibt.

Ich betreibe eine MQTT-Server-Instanz v2.4.0 in ioBroker.
Mit Blockly führe ich unter anderem folgendes aus:
`sendTo("mqtt.0", "sendMessage2Client", {
     "topic": 'ccc/ist',
     "message": '2'
  });`

Nochmal: Das Topic ccc/ist existiert nicht. Mit diesem Befehl wird es aber auch nicht erstellt - zumindest sehe ich im Objektbaum nichts neues. Auch das Ändern von existierenden Topics klappt nicht - wo ist mein Denkfehler? Welche Möglichkeiten habe ich automatisiert / dynamisch Topics mit einem Script anzulegen? (Message kann ruhig String sein).

**Comment by Apollon77** [comment]
Diese Message sendet wirklich nur diese Daten an die Clients raus ... am besten mal das Loglevel auf debug stellen, dann sieht man sehr gut was passiert. Hilft das vllt schon?

**Comment by Wally0** [comment]
Vielen Dank für die superschnelle Antwort 👍 

Tatsache - mit MQTT Explorer beobachtet. Ich bitte um Verzeihung, dass ich pauschal behauptet habe, dass es nicht geht.

Dennoch ein kleines Issue für mich:
Wie kann ich per Skript Topics dynamisch anlegen bzw. eine Art setup / init eines frischen MQTT-Brokers ausführen? Sodass quasi ein Set an bestimmten Topics automatisch angelegt wird?

Die Idee war sendTo zu verwenden, um direkt diese Topics erstellen zu lassen - vielleicht gibt es einen eleganteren Weg bzw. die Möglichkeit den Adapter upzudaten, sodass auch ein Objekt angelegt wird?

Ein Stupser in die richtige Datei und Funktion die anzupassen wäre, wäre sehr nett. Dann könnte ich mich evtl. auch an der Weiterentwicklung beteiligen :)

**Comment by Wally0** [comment]
Habe das jetzt (erstmal) folgendermaßen gelöst:

`const instance = "mqtt.0"
const topic = "abc/def"

var id = instance + "." + topic.replace("/", ".");
 
var obj = {
"type":"state",
"common": {
    "name": topic,
    "role": "variable",
    "type": "string",
    "read": true,
    "write": true,
    "desc": "created by Wally's Script",
    "def": "uninitialized"}
};
 
setObject(id, obj, function() {
    setState(id, obj.common.def,true);
});`

Kombiniere das dann später noch mit dem sendTo-Befehl.
Muss mir mal daraus eine "universelle" (oder mehrere) Funktion(en) bauen (die von allen JavaScripts aufgerufen werden kann)

Aber vielleicht geht's ja eleganter?

PS: Für alle Interessierten: Um das funktionsfähig und nicht die Fehlermeldung
`javascript.0 | 2022-01-21 15:43:34.469 | error | Function "setObject" is not allowed. Use adapter settings to allow it.`
zu bekommen, muss man den Haken unter **Instanzen -> javascript.0 -> Einstellungen (Schraubenschlüssel) -> Enable command "setObject"** setzen.

**Comment by Apollon77** [comment]
Da bin ich gerade ehrlich und kann nur sagen "keine Ahnung" ... vllt eine bessere Frage mal fürs Forum?

**Comment by Diginix** [comment]
Damit sendTo ein Topic erzeugt muss die im JS/Blockly verwendete mqtt Instanz als Client laufen, nicht als Server.
