### ISSUE TITLE
Warnings after update to JS-Controller version: 4.0.3

### ISSUE THREAD

**Issue by lonsimbt** [ioBroker/ioBroker.mqtt#251]
Warning after update:

`
mqtt.0	2022-02-05 21:37:51.901	warn	This object will not be created in future versions. Please report this to the developer.
mqtt.0	2022-02-05 21:37:51.899	warn	Object mqtt.0.info.connection is invalid: Default value has to be type "string" but received type "boolean"
`

**Comment by Apollon77** [comment]
I will take care
