### ISSUE TITLE
mqtt Adapter Meldung: has to be type "string" but received type "number" 

### ISSUE THREAD

**Issue by Bernd9000** [ioBroker/ioBroker.mqtt#254]
Ich sende mit node-red ioBroker-out einen Text vom Typ `string` der einen Text und manchmal auch eine Zahl enthält.
Immer wenn ich eine reine Zahl sende interpretiert der mqtt Adapter das als `number` und nicht als `string`.
Ist das ein Fehler ?
Oder wird der Wert tatsächlich auf Zahlen untersucht und wenn nur Zahlen vorkommen wir das als Typ `number` interpretiert ?

**Comment by Apollon77** [comment]
naja ist es wirjlich ein String? also "1" und 1 sind andere Dinge.

**Comment by Bernd9000** [comment]
Der Datenpunkt ist als string angelegt.

Debug Log:
![Unbenannt](https://user-images.githubusercontent.com/77005685/154821098-627bdf27-d3d5-46dd-ab07-0f4bbba72d17.jpg)

Mit Anführungsstriche gibt es keine Probleme, aber ich will ja eben nur eine Zahl als `string` speichern.
Die Info kommt auch wenn ich die Zahl direkt im ioBroker eintrage.

![Animation](https://user-images.githubusercontent.com/77005685/154821359-a70aeeca-259e-4d33-9297-6a5524cddd90.gif)

**Comment by Apollon77** [comment]
Es ist erstmal egal wie der Stat angelegt ist: Was gernau schreibt dein node-red da rein? Schreibt eine Zahl oder einen String rein? Stelle sicher das da ein String rauskommt

**Comment by Bernd9000** [comment]
node-red Log meldet string:

![Unbenannt](https://user-images.githubusercontent.com/77005685/154821727-ddb77ade-e29b-497c-af05-871e915e9820.jpg)

ioBroker out Einstellungen:
![Unbenannt](https://user-images.githubusercontent.com/77005685/154821790-518ea24b-7362-4e95-921c-322db7a4f21e.jpg)

**Comment by Bernd9000** [comment]
Ich glaube ich habs.
Bei den oberen Bild gab es kein Fehler, das hat mich verwundert.
Wenn ich aber im node-red ioBroker-out den Type auf `command` stelle kommt der Fehler (ack).
Also mit Bestätigung beim Datenpunkt kommt die Info.

**Comment by Bernd9000** [comment]
Damit hat sich das wohl erledigt?

**Comment by Apollon77** [comment]
ich denke das ist dann wenn eher ein node-red thema oder?! Ich habe aber in node-red code geschaut und ich kann nur sagen das der msg-payload exakt so genommen wird wie er kommt ... Da findet keine number zu String oder andersrum konvertierung statt bei einer OutNode ... ?!

**Comment by Bernd9000** [comment]
stimmt
