### ISSUE TITLE
mqtt falscher State Typ - keine Debug Ausgaben.

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.mqtt#257]
Wie gewünscht hier nochmal ein neues Issue.

BS: Win10
Admin: 5.3.1
js-controller: 4.0.15
mqtt Adapter: 2.6.1
Alle Instanzen stehen im DEBUG Mode, es werden aber keine Debug Meldungen ausgegeben - sondern nur Info oder Error Meldungen.

Für mich in diesem Zusammenhang wichtig und unerklärlich die Meldungen des snmp Adapter. Dieser lief Monatelange ohne Problem. Exakt mit dem einspielen des mqtt Adapter Update auf 2.6.1, beglückt mich auch dieser Adapter mit Timeout Meldungen. 
AUCH deshalb, weil die mqtt.0 Instanz ebenfalls hin und wieder timeout Meldungen verursacht. 

Gibt es ggf. zwischen dem MQTT und dem snmp Adapter irgend welche gemeinsam genutzten Abhängigkeiten? 

`<html>
<body>

 
--
mqtt.2 | 2022-02-28 08:38:46.276 | info | State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 08:38:46.175 | info | State value to set for "mqtt.2.openWB.set.evu.faultState" has to be type "number" but received type "string"
snmp.0 | 2022-02-28 08:38:45.467 | error | [10.122.60.87] Error session.get: RequestTimedOutError: Request timed out
mqtt.2 | 2022-02-28 08:38:45.199 | info | State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 08:38:45.031 | info | State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "number" but received type "string"
mqtt.0 | 2022-02-28 08:38:37.193 | info | Client [Poolsteuerung] connection closed: timeout
mqtt.2 | 2022-02-28 08:38:36.299 | info | State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 08:38:36.198 | info | State value to set for "mqtt.2.openWB.set.evu.faultState" has to be type "number" but received type "string"
snmp.0 | 2022-02-28 08:38:35.468 | error | [10.122.60.87] Error session.get: RequestTimedOutError: Request timed out
mqtt.2 | 2022-02-28 08:38:35.190 | info | State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 08:38:35.027 | info | State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 08:38:27.847 | info | State value to set for "mqtt.2.openWB.set.system.reloadDisplay" has to be type "string" but received type "number"
mqtt.2 | 2022-02-28 08:38:26.402 | info | State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 08:38:26.294 | info | State value to set for "mqtt.2.openWB.set.evu.faultState" has to be type "number" but received type "string"
web.0 | 2022-02-28 08:38:25.691 | info | <== Disconnect system.user.admin from ::ffff:10.122.60.87 vis.0
snmp.0 | 2022-02-28 08:38:25.445 | error | [10.122.60.87] Error session.get: RequestTimedOutError: Request timed out
mqtt.2 | 2022-02-28 08:38:25.252 | info | State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 08:38:25.087 | info | State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "number" but received type "string"
mqtt.0 | 2022-02-28 08:38:22.007 | info | Client [Poolsteuerung] connected with secret 1646033902005_6473
mqtt.2 | 2022-02-28 08:38:16.219 | info | State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 08:38:16.097 | info | State value to set for "mqtt.2.openWB.set.evu.faultState" has to be type "number" but received type "string"
snmp.0 | 2022-02-28 08:38:15.457 | error | [10.122.60.87] Error session.get: RequestTimedOutError: Request timed out
mqtt.2 | 2022-02-28 08:38:15.108 | info | State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 08:38:14.949 | info | State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "number" but received type "string"
mqtt.0 | 2022-02-28 08:38:05.957 | info | Client [Poolsteuerung] connection closed: timeout
mqtt.2 | 2022-02-28 08:38:05.520 | info | State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 08:38:05.415 | info | State value to set for "mqtt.2.openWB.set.evu.faultState" has to be type "number" but received type "string"
snmp.0 | 2022-02-28 08:38:05.313 | error | [10.122.60.87] Error session.get: RequestTimedOutError: Request timed out
mqtt.2 | 2022-02-28 08:38:04.349 | info | State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 08:38:04.186 | info | State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 08:37:57.901 | info | All states published
mqtt.2 | 2022-02-28 08:37:55.683 | info | Changed type of "openWB.set.lp.1.socFaultState" from "string" to "number"
mqtt.2 | 2022-02-28 08:37:55.461 | info | State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 08:37:55.460 | info | State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 08:37:55.459 | info | Changed type of "openWB.set.evu.faultState" from "string" to "number"
snmp.0 | 2022-02-28 08:37:55.452 | error | [10.122.60.87] Error session.get: RequestTimedOutError: Request timed out
mqtt.2 | 2022-02-28 08:37:55.461 | info | State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 08:37:55.460 | info | State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 08:37:55.459 | info | Changed type of "openWB.set.evu.faultState" from "string" to "number"
snmp.0 | 2022-02-28 08:37:55.452 | error | [10.122.60.87] Error session.get: RequestTimedOutError: Request timed out

</body>
</html>`

**Comment by Apollon77** [comment]
Nur zur Klarstellung:
* Debug LOGLEVEL bei der instanz geht unter Admin - Instanzen - Expertenmodus - Instanz aufklappen, dort loglevel setzen
* Und dann hat mqtt in seinen adapter-Settings noch extra debug settings

Interessant im Log ist das er an einigen Stellen das erwartete Loggt:
>  mqtt.2 | 2022-02-28 08:37:55.459 | info | Changed type of "openWB.set.evu.faultState" from "string" to "number"

Er macht diese Konvertierung ggf einmalig nach Adapterstart ... wenn natürlichjetzt ein gerät hier ständig Datentypen wechselt dann geht das dann direkt wieder schieff. Wie hier. es war string dann kam ne zahl, Adapter hat also angepasst beim ersten Datenpaket was kam. Und schwupp kam das nächste Datenpaket und plötzlich wars wieder ein String. grmpf ... Naja ich überlege mal


Zur Frage wegen SNMP: Keine AHnung, sollte nicht - ausser das Gerät kann nur eine Netzwerkverbindung gleichzeitig akzeptieren oder so ... dann wäre mit mqtt diese "voll" und snmp hat keine chance. Aber da müsstest Du eher den Hersteller befragen

**Comment by JBSullivan** [comment]
Ich denke, ich weiß schon wie man ein Loglevel setzt. Aber es kommt keine DEBUG Ausgabe, auch wenn ich das LogLevel auf Debug stelle. Es kommen nur Info Eintragungen im Protokoll.

![image](https://user-images.githubusercontent.com/44617472/155961213-49e11967-4c9b-42a2-b9dd-6a434ae5f29d.png)

Zum Thema SNMP - es handelt sich NICHT um das gleiche Gerät wie die mqqt.2. oder.0 Instanz. Es handelt sich dabei um eine USV, die nicht über mqtt abgefragt wird, die aber in der Tat nur einen Zugriff erlaubt. 
Melde ich mich auf dem Webinterface der USV an, bekomme ich keine Daten über SNMP - das ist mir bekannt. Ich bin aber an allen Rechnern NICHT mehr über das Webinterface an der USV angemeldet - das ist sicher. Die Datenaufzeichnung der SNMP Daten endet aber genau zu dem Zeitpunkt als der MQTT Adapter auf 2.6.1 installiert wurde.

Daher meine Idee, das vielleicht MQTT und SNMP irgend einen "Kanal" gleichzeitig nutzen, was bei SNMP zur der Blockade und somit zum Timeout führt. 


`<html>
<body>


snmp.0 | 2022-02-28 10:46:18.628 | error | [10.122.60.87] Error session.get: RequestTimedOutError: Request timed out
-- | -- | -- | --
mqtt.2 | 2022-02-28 10:46:15.774 | info | State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-28 10:46:15.689 | info | State value to set for "mqtt.2.openWB.set.evu.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-28 10:46:14.545 | info | State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-28 10:46:14.388 | info | State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "string" but received type "number"
snmp.0 | 2022-02-28 10:46:08.619 | error | [10.122.60.87] Error session.get: RequestTimedOutError: Request timed out
mqtt.0 | 2022-02-28 10:46:08.387 | info | Client [Poolsteuerung] connection closed: timeout
mqtt.2 | 2022-02-28 10:46:06.049 | info | State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-28 10:46:05.949 | info | State value to set for "mqtt.2.openWB.set.evu.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-28 10:46:04.807 | info | State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-28 10:46:04.705 | info | State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "string" but received type "number"
mqtt.2 | 2022-02-28 10:46:01.469 | info | All states published
mqtt.2 | 2022-02-28 10:46:01.414 | info | State value to set for "mqtt.2.openWB.set.evu.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 10:46:01.395 | info | Changed type of "openWB.set.evu.faultState" from "number" to "string"
mqtt.2 | 2022-02-28 10:46:01.313 | info | State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 10:46:01.303 | info | Changed type of "openWB.set.pv.1.faultState" from "number" to "string"
mqtt.2 | 2022-02-28 10:46:01.273 | info | State value to set for "mqtt.2.openWB.set.lp.1.socFaultState" has to be type "number" but received type "string"
mqtt.2 | 2022-02-28 10:46:01.266 | info | Changed type of "openWB.set.lp.1.socFaultState" from "number" to "string"
mqtt.2 | 2022-02-28 10:46:01.222 | info | State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "nu


</body>
</html>`

**Comment by JBSullivan** [comment]
Holla die Waldfee - was für ein krasser Scheiß. Also das SNMP Problem ist behoben. Ursache es waren zwei Windows Dienste für die USV Verwaltungssoftware APC BusinessPowerChute aktiv. Da ich gestern zum Zeitpunkt des Adapter Updates mich mit einem zweiten Benutzer auf den ioBroker Rechner eingewählt habe wurde offensichtlich ein zweiter USV Dienst angelegt.

Das interessante daran - im Logging ist die timeout Meldung natürlich verschwunden und der SNMP Adapter liefert wieder Daten ABER - nun kommen auch beim MQTT Adapter DEBUG Meldungen ?!?!?

Hier male ein Auszug aus diesen Meldungen (nicht alle - sind sooo viele)

`2022-02-28 11:15:58.928  - [34mdebug[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.housebattery.WhImported: {"val":110742.94624661955,"ack":true,"ts":1646043358894,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646043358894}
2022-02-28 11:15:58.929  - [34mdebug[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.global.cpuUse: {"val":89.4,"ack":true,"ts":1646043358894,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646043358894}
2022-02-28 11:15:58.932  - [34mdebug[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.global.cpuTemp: {"val":42.93,"ack":true,"ts":1646043358894,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646043358894}
2022-02-28 11:15:58.955  - [34mdebug[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.global.memUse: {"val":353,"ack":true,"ts":1646043358952,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646043358952}
2022-02-28 11:15:58.957  - [34mdebug[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.global.memFree: {"val":451,"ack":true,"ts":1646043358952,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646043358952}
2022-02-28 11:16:01.065  - [34mdebug[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.SmartHome.Status.uberschuss: {"val":1362,"ack":true,"ts":1646043361062,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646043361062}
2022-02-28 11:16:01.108  - [34mdebug[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.SmartHome.Status.uberschussoffset: {"val":-3638,"ack":true,"ts":1646043361105,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646043361105}
2022-02-28 11:16:01.122  - [32minfo[39m: javascript.0 (14500) script.js.Aktiv.Gaszaehler: 2208.98
2022-02-28 11:16:03.981  - [34mdebug[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.pv.WHExport_temp: {"val":6799264266.780572,"ack":true,"ts":1646043363979,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646043363979}
2022-02-28 11:16:04.020  - [32minfo[39m: mqtt.2 (8416) State value to set for "mqtt.2.openWB.set.pv.1.faultState" has to be type "string" but received type "number" 
2022-02-28 11:16:04.023  - [34mdebug[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.set.pv.1.faultStr: {"val":"\"Kein Fehler.\"","ack":true,"ts":1646043364020,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646043364020}
2022-02-28 11:16:04.024  - [34mdebug[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.set.pv.1.faultState: {"val":0,"ack":true,"ts":1646043364020,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646043364020}
2022-02-28 11:16:04.027  - [34mdebug[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.set.pv.1.faultStr: {"val":"","ack":true,"ts":1646043364021,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646042904050}
2022-02-28 11:16:04.062  - [34mdebug[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.set.pv.1.faultState: {"val":"","ack":true,"ts":1646043364060,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646043364060}
2022-02-28 11:16:04.139  - [34mdebug[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.housebattery.WHImported_temp: {"val":398688276.974416,"ack":true,"ts":1646043364137,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646043364137}
2022-02-28 11:16:04.178  - [32minfo[39m: mqtt.2 (8416) State value to set for "mqtt.2.openWB.set.houseBattery.faultState" has to be type "string" but received type "number" 
2022-02-28 11:16:04.181  - [34mdebug[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.set.houseBattery.faultStr: {"val":"\"Kein Fehler.\"","ack":true,"ts":1646043364179,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646043364179}
2022-02-28 11:16:04.182  - [34mdebug[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.set.houseBattery.faultState: {"val":0,"ack":true,"ts":1646043364179,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646043364179}
2022-02-28 11:16:04.184  - [34mdebug[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.set.houseBattery.faultStr: {"val":"","ack":true,"ts":1646043364179,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646042934211}
2022-02-28 11:16:04.226  - [34mdebug[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.set.houseBattery.faultState: {"val":"","ack":true,"ts":1646043364223,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646043364223}`

**Comment by Apollon77** [comment]
Ja seht mal sehr schön das sich das gerät nicht einig ist was es senden will ... wtf

> 2022-02-28 11:16:04.182  - �[34mdebug�[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.set.houseBattery.faultState: {"val":0,"ack":true,"ts":1646043364179,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646043364179}
> 2022-02-28 11:16:04.226  - �[34mdebug�[39m: mqtt.2 (8416) stateChange mqtt.2.openWB.set.houseBattery.faultState: {"val":"","ack":true,"ts":1646043364223,"q":0,"from":"system.adapter.mqtt.2","user":"system.user.admin","lc":1646043364223}

Innerhalb von 24ms zwei Datentypen ... heul ... 

Ja ich überlege mal. Eine Idee wäre bei zu regelmäßigen Datentyp Änderungen den Datentyp auf "mixed" zu setzen dann ist ruhe ... wäre unschon, aber wenn sich das gerät nicht an DInge halten kann ists halt so

**Comment by JBSullivan** [comment]
Kleiner Hinweis zu dem Gerät, welches die Daten liefert. Es handelt sich dabei um eine openWB Wallbox. Ich habe im dortigen Forum die Problematik angesprochen, woraufhin eine Diskussion darüber entbrannt ist, das mehrere Leute der Meinung sind, das diese Art des MQTT Daten Stream nicht OK ist und wohl nicht dem Standard entspricht.

Die Aussage von openWB ist, das sich daran für die bestehenden Wallboxen mit Software 1.9.x nichts mehr ändern wird.

> Der leere String wird bei allen Set-Topics genutzt, um die als retained gesendete Nachricht zu löschen. So kann es schon sein, dass einmal eine Zahl und danach das "Nichts" als String interpretiert werden kann.

Das noch in 1.9 anders zu handhaben, verursacht reichlich Nebenwirkungen und Inkonsistenzen. In 2.0 werden alle Topics mit JSON Daten gesendet, sodass das Problem dort nicht auftreten sollte.

**Comment by Apollon77** [comment]
Interessant ... :-)) Aber ich denke OpenWB ist da nicht "alleine". Ich denke die oben genannte Idee macht am meisten sinn. Melde mich wenn ich es mal eingebaut habe

**Comment by Apollon77** [comment]
Ok, dann bitte mal GitHub version installieren (versionsnummer ändert sich nicht, nach nstall bitte manuell neu starten).
Am besten (sicher ist sicher vorher mal die Objekte von mqtt.X sichern ...

Dann am besten VORHErRschonmal wieder alles debug einschalten und dann das log .. am besten gleich vom ersten start an.

Die Logik versucht jetzt einmalig den Datentyp richtig zu korrigieren und setzt sie danach ggf auf "Mixed" und ab dann sollte ruhe sein :-) Jeweils müsste einmalig ein "type mismatch" log kommen. sollte aber auch nur für die kommen wo es so einen mismatch gibt ... alle anderen sollten nichts loggen.

**Comment by Apollon77** [comment]
Das sieht doch gut aus :-) Und auch nach einem restart kommt dann "gar nix mehr"??

**Comment by JBSullivan** [comment]
Ja, korrekt, nach dem Neustart kommt nur noch das hier, sonst nichts mehr. Also perfekt gelöst - Vielen Dank.

`<html>
<body>


mqtt.2 | 2022-03-03 12:17:16.441 | info | All states published
-- | -- | -- | --
mqtt.2 | 2022-03-03 12:17:12.671 | info | Subscribe on: "#"
mqtt.2 | 2022-03-03 12:17:12.668 | info | Connected to 10.122.60.107
mqtt.2 | 2022-03-03 12:17:12.527 | info | Try to connect to mqtt://openWB:*******************@10.122.60.107:1883?clientId=iobroker.mqtt.2
mqtt.2 | 2022-03-03 12:17:11.803 | info | starting. Version 2.6.1 (non-npm: ioBroker/ioBroker.mqtt) in C:/iobroker/GLT/node_modules/iobroker.mqtt, node: v14.16.0, js-controller: 4.0.15


</body>
</html>`

**Comment by Apollon77** [comment]
Perfekt, Update kommt später
