### ISSUE TITLE
Feature request: Ignore New Objects

### ISSUE THREAD

**Issue by Goersch** [ioBroker/ioBroker.mqtt#260]
Hi,

I ran into an issue here, which is running me crazy.

Because the WiFi connection to one of the clients is bad, it happens from time to time that the provided object names are not OK. Instead of "Valve_1" I get a lot of other objects like _val1, balfe1, _vale_1, .... takes some time to clean up all the unused objects.

What would fix this, is an option like "Ignore New Objects" (default: false), which one can set to true after adding a new client and all "real" objects are available.

May be there is another solution I don't see/know?

Thanks :)
Georg

**Comment by cap-blackbeard** [comment]
I like that idea!
I also have the same difficulty with a client via wifi.


Thanks
Christian

**Comment by GermanBluefox** [comment]
Please test 4.0.0

**Comment by cap-blackbeard** [comment]
sorry for my newbie question.
How do I update to 4.0.0?
The beta repository does´t show version 4.0.0

Do i need to open ssh?
And then with `npm i iobroker.mqtt@4.0.0`?

I´m using docker.

**Comment by Apollon77** [comment]
4.0.0 is in the beta repo. maybe reload on adapter page? Other then that you can enable expert mode and use the curom install dialog with select mqtt on "from npm"  tab

**Comment by cap-blackbeard** [comment]
Für mich funktioniert es sehr gut! Keine neuen "Geister-"Zustände mehr.
Herzlichen Dank!
