### ISSUE TITLE
Falsche Maske zum Bekanntgeben eigener States bei Mqtt Broker/client

### ISSUE THREAD

**Issue by SurfGargano** [ioBroker/ioBroker.mqtt#261]
Wenn man mehrere Instanzen vom Mqtt -Adapter mit Einstellung Server/Broker hat, wird in allen Instanzen unter Maske zum Bekanntgeben eigener States `mqtt.0` als  Standard eingetragen, auch bei Instanz 1 , 2 usw.  Das führt dazu , daß keine subscribed States dem Slave mitgeteilt werden kann. Nur wenn man z,B, bei der Instanz  1 dann `mqtt.1` einträgt geht es.

**Comment by Apollon77** [comment]
Yes, the default is currently "hard coded", thats right ...

**Comment by GermanBluefox** [comment]
Das Verhalten wird geändert. In 4.0.0
Beim Start wird geprüft ob die Instanz nicht 0 ist und "publish" wird angepasst.
