### ISSUE TITLE
Default value has to be type "string" but received type "boolean"

### ISSUE THREAD

**Issue by 4358haltern** [ioBroker/ioBroker.mqtt#262]
Hi

ich habe den mqtt adapter im broker installiert und bekomme folgende meldung ausgeworfen.

mqtt.0 | 24707 | 2022-03-20 15:23:22.690 | warn | This object will not be created in future versions. Please report this to the developer.

mqtt.0 | 24707 | 2022-03-20 15:23:22.689 | warn | Object mqtt.0.info.connection is invalid: Default value has to be type "string" but received type "boolean"

so das leider auch eine verbindung zustande kommt..

habe den "issus" #251 gelesen doch weisss nicht ob das die "lösung" ist und wo ich das finden kann

**Comment by Apollon77** [comment]
Welche Version des Adapters nutzt du? Der Fix ist denke ich noch in den aktuelleren Version die im Beta Repo sind

**Comment by 4358haltern** [comment]
Hallo

Der Adapter is 2.4.1

Mit dem aktuellen controller

**Comment by friedpa** [comment]
Die aktuelle Adapzter Version ist 2.7.4, einzuspielen über Adapter -> Symbol Katze -> Github -> MQTT

**Comment by 4358haltern** [comment]
die katze gibt es nicht mehr ;)
aber ich weiss was du meinst

**Comment by 4358haltern** [comment]
läuft mit version 2.7.4.

**Comment by Apollon77** [comment]
@friedpa Kleine Korrektur: NIEMALS GitHub Installs empfehlen es sei denn der Entwickler hat es gesagt oder es ist wirklich ein Fix der gerade auf GitHub getestet wird!!

Bitte IMMER den "Npm install" (Admin 5 - Custom Install - erster Tab) vorziehen - das eentspricht der Beta version

**Comment by friedpa** [comment]
OK! Sorry!

**Comment by fruehwi** [comment]
> @friedpa Kleine Korrektur: NIEMALS GitHub Installs empfehlen es sei denn der Entwickler hat es gesagt oder es ist wirklich ein Fix der gerade auf GitHub getestet wird!!
> 
> Bitte IMMER den "Npm install" (Admin 5 - Custom Install - erster Tab) vorziehen - das eentspricht der Beta version

@Apollon77 
Ich haben meinen iobroker von einem MacMini auf meine Synology (Docker) erfolgreich umgezogen.
Nur machen mir jetzt noch die Shelly probleme mit dem mqtt.

Nun habe ich das selbe Problem wie in diesem Issue. 
bei anderen Adapter konnte ich die Version auswählen.
Wenn ich auf "Beta" im Resp... umstelle hilft das leider auch nichts. 
Bitte um eine erklärung was du mit :


> Bitte IMMER den "Npm install" (Admin 5 - Custom Install - erster Tab) vorziehen - das eentspricht der Beta version

meinst.

danke 
VG Fruehwi

**Comment by Apollon77** [comment]
Naja was da steht. Öffne Admin, aktiviere den expertenmodus, gehe auf Adapter, klicke den github Button Bzw custom install und dann wähle dort das erste Tab wo es heißt "install von npm"

**Comment by Apollon77** [comment]
> Cannot parse /opt/iobroker/node_modules/iobroker.mqtt/io-package.json: /opt/iobroker/node_modules/iobroker.mqtt/io-package.json: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.mqtt/io-package.json'Cannot find io-package.json in /opt/iobroker/node_modules/iobroker.mqtt

This should NEVER happen! Check your filesystem please

**Comment by Apollon77** [comment]
But I still do not understand why you had that issue when you installed 2.7.4 from npm ... because the broken version was never there. Which version is in the package.json in the above dir???

**Comment by fruehwi** [comment]
I never installed 2.7.4 ... I would like. 
My system had mqtt 2.4.1.
Yesterday I tried unfortunately like  above the the second way github (not NPM).  Maybe the problems start with that.

in /opt/iobroker/node_modules I can´t find one.
in /opt/iobroker/package.json 👍 
![image](https://user-images.githubusercontent.com/68781082/161987438-5c4378a9-5ec1-4d1b-b4c8-d84c5b6b601b.png)

**Comment by fruehwi** [comment]
![image](https://user-images.githubusercontent.com/68781082/161999974-58b4c757-3661-4596-848f-17f43afe1903.png)

I got this result. 
But after install over Admin , mqtt is now work again . 
Thank you very much !

**Comment by Apollon77** [comment]
@fruehwi you'r welceome and thank you very much!

**Comment by Apollon77** [comment]
should never happen. Please create a new issue and attach a deug log of adapter start till when these logs came

**Comment by Groej77** [comment]
Moin,
ich hab das gleiche Problem hatte bis jetzt gerade 2.4.1 drauf und mit 2.7.4 ist das Problem auch. Der Shelly Adapter hat auch ein Problem. Das einzige was ich vor ein paar Tagen gemacht habe ist ein Update von Node.js v14.19.0 auf v14.19.1. Ich habe aber gestern erst einen Neustart des Systems gemacht. Das der Shelly Adapter ja auch mit MQTT arbeitet nur auf einen anderen Port als der MQTT Adapter denke ich das es da irgendwie einen Zusammenhang gibt. Beim Shelly Adapter kommt aber leider keine Fehlermeldung was ich sehen konnte. Auch nicht im DEBUG. 
Bin jetzt nicht der große Linux Experte. Wie kann ich die alte Node.js Version installieren um zu testen ob es daran liegt?

**Comment by Groej77** [comment]
Hallo,

ich hab das gleiche Problem.
![2022-04-10_070740](https://user-images.githubusercontent.com/74791791/162602311-f8bb0335-e72b-4a67-8d15-d884df542ec4.png)
Ich habe es auch schon mit der Version 2.7.4 probiert. Fehler bleibt. Ich hatte neulich auf Node.js 14.19.1 hochgerüstet und dachte vielleicht es hängt damit zusammen. Tut es aber nicht weil ich wieder auf 14.19.0 zurückgegangen bin.
Der Shelly Adapter geht aber leider auch nicht auf Grün. Leider spuckt der keine Fehler aus. Scheint dann wohl ein allgemeines Problem mit MQTT zu sein. 
Beide Adapter benutzen ja MQTT aber auf verschiedenen Ports bei mir. Geht ja auch nicht anders. Ich hatte vor kurzen ein Update des Raspi gemacht aber gestern erst einen Neustart des Systems weil ich zu Hause einen neuen Switch eingebaut habe. Seit dem habe ich den Fehler beim MQTT und Shelly Adapter. 
Gruß
Jörg

**Comment by Apollon77** [comment]
Also der info-connection Fehler ist an sich seit der 2.7.0 behoben ... AM besten mal das info-connection objekt löschen und dann adapter neu drüber installieren
