### ISSUE TITLE
invalid pass or username since version 3.0.4

### ISSUE THREAD

**Issue by Schimi1983** [ioBroker/ioBroker.mqtt#272]
`<html>
<body>

mqtt.0 | 2022-04-07 13:21:43.097 | warn | Client [szymon] has invalid password(teet) or username(test)
-- | -- | -- | --
mqtt.0 | 2022-04-07 13:21:42.652 | warn | Client [szymon] has invalid password(teet) or username(test)

</body>
</html>`

seit dem upgrade auf Version 3.0.4 kommt keine verbindung zu stande sobald ein username und pass vergeben wird....

Ohne funktioniert es... habe auch schon verschiedene ausprobiert

**Comment by Garfonso** [comment]
Habe das gleiche Problem mit mqtt als client. Passwort mehrfach neueingegeben.

**Comment by Schimi1983** [comment]
ich probiere es mal... mir ist auch aufgefallen das es mit einem neuen passwort auch nicht in einer früheren version funktioniert (habe das pass seit "Jahren" nicht geändert ;-)

Ich check mal deine version

**Comment by Schimi1983** [comment]
> Ich habe das Problem bei mir gelöst @Schimi1983 , wenn du magst versuch mal von folgender Github URL zu installieren:
> 
> https://github.com/Garfonso/ioBroker.mqtt

deine version funktioniert einwansfrei!!!
Kann ich dann auf dieser bleiben oder bekomme ich keine zukünftigen "offiziellen" updates? (Bin da nicht soooo bewandert :-))

**Comment by intruder7777** [comment]
same here!!!!

**Comment by Apollon77** [comment]
Grmppffff ... @Garfonso Could I get a PR please?

**Comment by Apollon77** [comment]
thx, got it ... on it, release comes soon

**Comment by Apollon77** [comment]
3.0.5 on the way to github

**Comment by kraus-wagner** [comment]
@Garfonso Mein Lebensretter! Vielen Dank. 
Anleitung: Expertenmodus einschalten - Im Reiter Adapter auf die Github Katze klicken - Ganz rechts auf Benutzerdefiniert (Weltkugel) - Link von Garfonso einfügen - Und installieren

**Comment by amg666** [comment]
> 3.0.5 on the way to npm

works fine, no more issues with username or password, thx 👍

**Comment by friedpa** [comment]
tested 3.0.5 now, works fine again! thx!
