### ISSUE TITLE
mqtt 3.0.5: Connection setting  not selectable with old admin UI

### ISSUE THREAD

**Issue by stmiko** [ioBroker/ioBroker.mqtt#274]
**Describe the bug**  
With this version of the mqtt Adapter it is not possible to set/change the connection settings.
According to some users in the iobroker forum this seems to be only a problem if one uses the old admin UI!
See: https://forum.iobroker.net/topic/54057/mqtt-3-0-5-verbindungstyp-nicht-einstellbar

Tested with Chrome and MS Edge. 

(If the old ui is not longer supported, please appologize)

**To Reproduce**  
1. install 3.0.5 and open the connection settings

**Versions:**  
 - Adapter version: 3.0.5
 - JS-Controller version: 4.0.21
 - Node version: 14.19.1
 - Operating system: linux (Debian X64)

**Comment by Apollon77** [comment]
Yes, this adapter only supports the new Admin UI ... Please use this one
