### ISSUE TITLE
Can't save settings

### ISSUE THREAD

**Issue by Reventrop** [ioBroker/ioBroker.mqtt#276]
**Describe the bug**  
pressing save and close does nothing 

**To Reproduce**  
1. Go to 'instances '
2. Click on 'settings'
4. click on save and close... nothing.

**Expected behavior**  
save settings and close window.

**Screenshots & Logfiles**  
<img width="1123" alt="Bildschirmfoto 2022-04-18 um 22 49 52" src="https://user-images.githubusercontent.com/7107581/163875897-5d2d4514-a779-4a2f-b4bc-200e6a22195b.png">

**Versions:**  
 - Adapter version: 3.0.5

 - JS-Controller version: 4.0.21 
 - Node version: v14.19.0
 - Operating system: linux

**Comment by Apollon77** [comment]
oes it work when you change something? or just nor when changing nothing?

**Comment by Reventrop** [comment]
changing settings from client to server and back is enough for nothing to work.

**Comment by Apollon77** [comment]
Ok, this is then in fact an admin issue. WOuld you pleas be so kind and open one and link it with this one? We leave both open

**Comment by GermanBluefox** [comment]
I can see, that even translation does not work. What is shown in the browser console? Or is there any link to issue on admin?

**Comment by Apollon77** [comment]
@curana Any errors in browser error console?

**Comment by curana** [comment]
`[Error] TypeError: undefined is not an object (evaluating 'value.length')
	encrypt (index_m.html:20)
	(anonyme Funktion) (adapter-settings.js:299)
	(anonyme Funktion) (socket.io.js:258)
	(anonyme Funktion) (socket.io.js:166)`

This is the error from the console (Safari). I hope that help, @Apollon77

**Comment by Apollon77** [comment]
Does non safari work?

**Comment by curana** [comment]
No.

> Used Chrome and Safari but both browsers don't work.

**Comment by curana** [comment]
admin adapter is 5.3.8

**Comment by GermanBluefox** [comment]
> admin adapter is 5.3.8

but interface is not React. Isn't it?

**Comment by curana** [comment]
> but interface is not React. Isn't it?

How can I check? I don't know.

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/168267769-1c21917a-24cf-4496-8a91-745ea4a31606.png)

**Comment by curana** [comment]
Ok, that fixed it.
But I like the old interface more :(

Thanks for your help.
