### ISSUE TITLE
Can´t update from 2.4.1 to 2.7.4

### ISSUE THREAD

**Issue by cap-blackbeard** [ioBroker/ioBroker.mqtt#279]
Hey there,
I´m using the buanet docker image.
But I can´t update to 2.7.4

The Process looks like:
$ iobroker upgrade mqtt@2.7.4
Update mqtt from @2.4.1 to @2.7.4
NPM version: 6.14.16
Installing iobroker.mqtt@2.7.4... (System call)
upload [3] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/index.html index.html text/html
upload [2] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/index_m.html index_m.html text/html
upload [1] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/mqtt.png mqtt.png image/png
upload [0] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/words.js words.js application/javascript
Process exited with code 0

And after all the adapter is still updatable.

Can someone help me with an idea?

**Comment by Apollon77** [comment]
Starnge ... please try manually
* open ssh
* cd /opt/iobroker
* npm i mqtt@2.7.4
* iob upload mqtt
*

**Comment by cap-blackbeard** [comment]
Thank´s. But if I try:
npm i mqtt@2.7.4!

I get:
sudo: unable to resolve host 1adec49c25d3: Name or service not known
npm ERR! code ETARGET
npm ERR! notarget No matching version found for mqtt@2.7.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/iobroker/.npm/_logs/2022-04-28T18_56_32_890Z-debug.log


A package version that doesn´t exist?  Seems like some data cannot be read. But I successfully updated several adapters yesterday.

**Comment by Apollon77** [comment]
sorry "npm i iobroker.mqtt@2.7.4" :-)

**Comment by cap-blackbeard** [comment]
Everything is working fine now.

I had to delete these three files:

- mqtt_pub
- mqtt_sub
- mqtt

Thanks alot!
