### ISSUE TITLE
IOBroker: Version 4.03 not working

### ISSUE THREAD

**Issue by friedpa** [ioBroker/ioBroker.mqtt#295]
After upgrading from 4.01 to 4.03 on my test system, MQTT is not starting.
Log-File:

![grafik](https://user-images.githubusercontent.com/42890695/169223911-afff706b-0801-4fa2-90d7-efbd0310988a.png)

`host.RaspberryPi-Office | 2022-05-19 07:39:58.071 | error | startInstance  system.adapter.mqtt.0 Adapter dependency not fulfilled on any host:  required adapter "admin" has wrong version. Installed "5.3.8", required  ">=5.4.3"!`

I cannot find version 5.4.3 of the admin Adapter

Also:
- "Verbunden mit Host": status red
-  "Lebenszeichen": status red
-  "Verbindung: Client A, Client B, ...": stating status geen, but no updates received

**Comment by Apollon77** [comment]
The Current Admin beta verison is 5.4.9 ... use this one. Mqtt is also "only" in Beta

**Comment by Apollon77** [comment]
PS: How you installed mqtt btw? Because if you install via beta repository then Admin should prevent the update with a proper error message. That would mean you installed via GitHub or such ... if yes ... wwwhhhyyyyyyyyyyyy ;-)

**Comment by friedpa** [comment]
I am also testing the Beta Versions on my Test System... btw it makes fun to see how things are progressing.

**Comment by Apollon77** [comment]
Thank you, important side note: Please alwys try to install oficial neta versions from npm via admin and not GitHub ... this is really for "testing stuff before an release"
