### ISSUE TITLE
 connection closed: Error: read ECONNRESET

### ISSUE THREAD

**Issue by mikewolf** [ioBroker/ioBroker.mqtt#30]
https://forum.iobroker.net/viewtopic.php?f=22&t=15325&p=207999#p207999
mqtt.0	2018-07-08 16:09:28.515	info	Client [ESP32Client] connection closed: Error: read ECONNRESET
mqtt.0	2018-07-08 16:09:23.081	warn	Client [ESP32Client] Message 22 deleted after 11 retries
mqtt.0	2018-07-08 16:09:00.964	warn	Client [ESPClient_B4:E6:2D:29:29:F2] Message 2 deleted after 11 retries
"Mit der von Bluefox erwähnten Chunking Option funktioniert es" finde diese option nicht
mfg
mikewolf

**Comment by Robobauer** [comment]
Habe dasselbe Problem. Gibt es eine Lösung?

**Comment by BenAhrdt** [comment]
Ich hatte heute auch den mqqt adapter installiert und hatte verbindung zu einem Gerät.
Dann habe ich es spöter wieder versucht und bekomme diese meldung.
Auch bei funktionierenden shelly geräten kommt diese meldung. mit dem shelly adapter funktionieren diese.

**Comment by Apollon77** [comment]
ECONRESET bedeutet das das Gerät (also nicht der adapter) die verbindung beendet hat ... also bitte beim Gerät suchen

**Comment by BenAhrdt** [comment]
Danke… plötzlich ging es wieder…. Es ging gestern komischerweise mit keinem Gerät und auf einmal ging es wieder.
