### ISSUE TITLE
Semver missing?

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.mqtt#304]
After a bug report in the [iobroker forums](https://forum.iobroker.net/topic/55920/mqtt-adapter-startet-nicht-mehr-nach-update) I‘ve checked the dependencies. Semver is missing in package.json?!

https://github.com/ioBroker/ioBroker.mqtt/blob/c39e287d9c4c19c88f68bdbf32954c15ac958770/package.json#L17-L23

But used in main.js

https://github.com/ioBroker/ioBroker.mqtt/blob/c39e287d9c4c19c88f68bdbf32954c15ac958770/main.js#L13

**Comment by klein0r** [comment]
Semver was added to package.json in 1a24860b902c686914a077aadcb1c060c3d5b414 and removed in 56a3cdc2e4d6ff0c86e86de77dd318e89262784c

**Comment by klein0r** [comment]
Looks like semver isn‘t used anymore, but still required. So … main.js line 13 has to be removed

**Comment by Apollon77** [comment]
fixed in 4.0.7
