### ISSUE TITLE
mqtt connection closes

### ISSUE THREAD

**Issue by kuckuckmann** [ioBroker/ioBroker.mqtt#306]
Hi,

I have a stupid issue within my skript that causes that the mqtt connection closes what seems to be similar to a adapter restart.

![grafik](https://user-images.githubusercontent.com/99131208/178151370-26e1defa-776c-470b-98be-9e429786c614.png)
[NSPANEL_LUI_TV.txt](https://github.com/ioBroker/ioBroker.mqtt/files/9079350/NSPANEL_LUI_TV.txt)

Attached the Blockly script in XML.

Can you help me with that please?

Thx ahead

**Comment by Apollon77** [comment]
Please post the blockly script as image or the generated javascript code (click in JS adapter on the Blockly|JS button).

In fact the device seems to close the connection and then we do a reconnection ... SO I think you need to find out why the device does that

**Comment by Apollon77** [comment]
No answer, closed
