### ISSUE TITLE
4.0.7 Abstürze

### ISSUE THREAD

**Issue by Klaus-Lucas** [ioBroker/ioBroker.mqtt#310]
**Describe the bug**  
Hatte das Problem, dass keine Daten mehr von den Puls Countern im iobroker ankam, nachdem ich Version 4.0.7 installiert hatte.
Daraufhin habe ich Queues gelöscht, in der Hoffnung, dass sie neu angelegt werden. Bekomme jetzt aber Abstürze, wenn ich auf
Instanzen > mqtt.0 > Einstellungen klicke bzw. den Adapter reinstalliere.

Meine Umgebeung:
PlatformBetriebssystem:linux
Architektur:arm
CPUs:4
Geschwindigkeit:1500 MHz
Modell:ARMv7 Processor rev 3 (v7l)
RAM:7.7 GB
System-Betriebszeit:21 T. 02:37:16
Node.js:v16.16.0
time:1659096563640
timeOffset:-120
Adapter-Anzahl:423
NPM:8.15.1
Datenträgergröße:234.5 GB
Freier Festplattenspeicher:216.1 GB
Betriebszeit:14:03:37
Aktive Instanzen:19
Pfad:/opt/iobroker/
aktiv:true
_nodeCurrent:16.16.0
_nodeNewest:16.16.0
_nodeNewestNext:16.16.0
_npmCurrent:8.15.1
_npmNewest:8.15.0
_npmNewestNext:8.15.0

Fehlermeldung:
![klu_008](https://user-images.githubusercontent.com/36620907/181820011-4c13baf4-f51b-4bd0-9bce-715ff4d3ad5f.jpg)
`If in the second line you will see at :3000/static/js/main.chunk.js:36903 and not the normal file name,
please try to reproduce an error with opened browser console. In this case the special "map" files will be loaded and the developers can see the real name of functions and files.
this.state.tempValue is undefined

Zeile in Rot:
renderItem@http://192.168.178.41:8081/static/js/5710.7d75fb68.chunk.js:74:150619($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))render@http://192.168.178.41:8081/static/js/5710.7d75fb68.chunk.js:74:40920($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))Wi@http://192.168.178.41:8081/static/js/3961.a98ff7ab.chunk.js:16:6209($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))Rs@http://192.168.178.41:8081/static/js/3961.a98ff7ab.chunk.js:16:6006($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))oa@http://192.168.178.41:8081/static/js/3961.a98ff7ab.chunk.js:16:44992($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))ra@http://192.168.178.41:8081/static/js/3961.a98ff7ab.chunk.js:16:39834($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))Jc@http://192.168.178.41:8081/static/js/3961.a98ff7ab.chunk.js:16:39765($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))ml@http://192.168.178.41:8081/static/js/3961.a98ff7ab.chunk.js:16:39622($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))iu@http://192.168.178.41:8081/static/js/3961.a98ff7ab.chunk.js:16:36004($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))bs@http://192.168.178.41:8081/static/js/3961.a98ff7ab.chunk.js:16:34957($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))Ln@http://192.168.178.41:8081/static/js/3961.a98ff7ab.chunk.js:24:1615($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))Gn@http://192.168.178.41:8081/static/js/3961.a98ff7ab.chunk.js:24:2007($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))EventHandlerNonNull*41196@http://192.168.178.41:8081/static/js/3961.a98ff7ab.chunk.js:24:2193($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))n@http://192.168.178.41:8081/static/js/main.0193d507.js:1:293($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))72851@http://192.168.178.41:8081/static/js/3961.a98ff7ab.chunk.js:24:4006($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))n@http://192.168.178.41:8081/static/js/main.0193d507.js:1:293($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))57799@http://192.168.178.41:8081/static/js/3961.a98ff7ab.chunk.js:9:24($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))n@http://192.168.178.41:8081/static/js/main.0193d507.js:1:293($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))73961@http://192.168.178.41:8081/static/js/3961.a98ff7ab.chunk.js:16:57785($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))n@http://192.168.178.41:8081/static/js/main.0193d507.js:1:293($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))n.I/</</<@http://192.168.178.41:8081/static/js/main.0193d507.js:1:7532($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))n.f.consumes/</o/n.m[t]@http://192.168.178.41:8081/static/js/main.0193d507.js:2:2438($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))n@http://192.168.178.41:8081/static/js/main.0193d507.js:1:293($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))24470@http://192.168.178.41:8081/static/js/9759.172be61e.chunk.js:104:7129($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))n@http://192.168.178.41:8081/static/js/main.0193d507.js:1:293($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))52898@http://192.168.178.41:8081/static/js/5710.7d75fb68.chunk.js:1:11352($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))n@http://192.168.178.41:8081/static/js/main.0193d507.js:1:293($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))promise callback*72063@http://192.168.178.41:8081/static/js/main.0193d507.js:1:157($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))n@http://192.168.178.41:8081/static/js/main.0193d507.js:1:293($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))@http://192.168.178.41:8081/static/js/main.0193d507.js:4:460($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))@http://192.168.178.41:8081/static/js/main.0193d507.js:4:469($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))`

Wie in der Meldung vorgeschrieben, habe ich mit F12 die Firefox Browser Console geöffnet und den Adapter neu installiert:
`iobroker.admin@6.2.6 bootstrap.jsx:19:8
[2022-07-29T12:17:50.971Z] Try to connect instrument.ts:124:32
Stored version: , new version: 6.2.6 instrument.ts:124:32
Connected: true instrument.ts:124:32
Translate: time instrument.ts:124:32
Translate: timeOffset instrument.ts:124:32
Translate: _nodeCurrent instrument.ts:124:32
Translate: _nodeNewest instrument.ts:124:32
Translate: _nodeNewestNext instrument.ts:124:32
Translate: _npmCurrent instrument.ts:124:32
Translate: _npmNewest instrument.ts:124:32
Translate: _npmNewestNext instrument.ts:124:32
[ADAPTERS] getAdapters instrument.ts:124:32
[ADAPTERS] getAdaptersInfo instrument.ts:124:32
[ADAPTERS] admin instrument.ts:124:32
[ADAPTERS] admin instrument.ts:124:32
Execute: del mqtt --debug instrument.ts:124:32
STARTED: del mqtt --debug instrument.ts:124:32
cmdStdout 14 instrument.ts:124:32
[ADAPTERS] admin instrument.ts:124:32
[ADAPTERS] admin instrument.ts:124:32
timeout instrument.ts:124:32
cmdStdout 2 instrument.ts:124:32
cmdExit instrument.ts:124:32
198560050 instrument.ts:124:32
0 instrument.ts:124:32
Execute: add mqtt auto --host iobroker --debug instrument.ts:124:32
STARTED: add mqtt auto --host iobroker --debug instrument.ts:124:32
cmdStdout 2 instrument.ts:124:32
timeout instrument.ts:124:32
cmdStdout 37 instrument.ts:124:32
[ADAPTERS] admin instrument.ts:124:32
Translate: Non-NPM-Version: instrument.ts:124:32
GEThttp://192.168.178.41:8081/.undefined
[HTTP/1.1 404 Not Found 60ms]

[ADAPTERS] admin instrument.ts:124:32
Uncaught TypeError: this is undefined
    onError AdapterTile.jsx:34
    React 10
    f1 helpers.ts:99
    fe trycatch.ts:227
    f5 instrument.ts:536
    React 8
    Ln scheduler.production.min.js:13
    Gn scheduler.production.min.js:14
    41196 scheduler.production.min.js:14
    Webpack 18
AdapterTile.jsx:34:63
cmdExit instrument.ts:124:32
92228383 instrument.ts:124:32
0 instrument.ts:124:32
system.adapter.admin.0 instrument.ts:124:32
system.adapter.backitup.0 instrument.ts:124:32
system.adapter.chromecast.0 instrument.ts:124:32
system.adapter.device-reminder.0 instrument.ts:124:32
system.adapter.discovery.0 instrument.ts:124:32
system.adapter.doorbird.0 instrument.ts:124:32
system.adapter.echarts.0 instrument.ts:124:32
system.adapter.fritzdect.0 instrument.ts:124:32
system.adapter.fullybrowser.0 instrument.ts:124:32
system.adapter.hm-rega.0 instrument.ts:124:32
system.adapter.hm-rpc.0 instrument.ts:124:32
system.adapter.hm-rpc.2 instrument.ts:124:32
system.adapter.hm-rpc.4 instrument.ts:124:32
system.adapter.ical.0 instrument.ts:124:32
system.adapter.influxdb.0 instrument.ts:124:32
system.adapter.info.0 instrument.ts:124:32
system.adapter.javascript.0 instrument.ts:124:32
system.adapter.mqtt.0 instrument.ts:124:32
system.adapter.nut.0 instrument.ts:124:32
system.adapter.openweathermap.0 instrument.ts:124:32
system.adapter.ping.0 instrument.ts:124:32
system.adapter.sainlogic.0 instrument.ts:124:32
TypeError: this.state.tempValue is undefined
    renderItem ConfigText.jsx:36
    render ConfigGeneric.jsx:514
    React 8
    Ln scheduler.production.min.js:13
    Gn scheduler.production.min.js:14
    41196 scheduler.production.min.js:14`

Starte ich den Adapter, kommt im Log:
<html><body>

2022-07-29 20:21:42.715  - info: host.iobroker "system.adapter.mqtt.0" enabled
--
2022-07-29 20:21:43.095  - info: host.iobroker instance system.adapter.mqtt.0 started with pid 5520
2022-07-29 20:21:45.774  - error: mqtt.0 (5520) Client error:Error: connect ECONNREFUSED 127.0.0.1:1883
2022-07-29 20:21:55.790  - error: mqtt.0 (5520) Client error:Error: connect ECONNREFUSED 127.0.0.1:1883
2022-07-29 20:22:05.804  - error: mqtt.0 (5520) Client error:Error: connect ECONNREFUSED 127.0.0.1:1883
2022-07-29 20:22:15.814  - error: mqtt.0 (5520) Client error:Error: connect ECONNREFUSED 127.0.0.1:1883
2022-07-29 20:22:25.829  - error: mqtt.0 (5520) Client error:Error: connect ECONNREFUSED 127.0.0.1:1883
2022-07-29 20:22:34.122  - info: host.iobroker "system.adapter.mqtt.0" disabled
2022-07-29 20:22:34.125  - info: host.iobroker stopInstance system.adapter.mqtt.0 (force=false, process=true)
2022-07-29 20:22:34.259  - info: host.iobroker stopInstance system.adapter.mqtt.0 send kill signal
2022-07-29 20:22:35.312  - info: host.iobroker instance system.adapter.mqtt.0 terminated with code 0 (NO_ERROR)

</body>
</html>

Ganze Logfile:
[iobroker.2022-07-29.log](https://github.com/ioBroker/ioBroker.mqtt/files/9222474/iobroker.2022-07-29.log)

klu@iobroker:~ $ iobroker update && iobroker upgrade
Used repository: beta
Adapter    "admin"        : 6.2.10   , installed 6.2.6  [Updatable]
Adapter    "backitup"     : 2.4.10   , installed 2.4.10
Adapter    "chromecast"   : 2.3.1    , installed 2.3.1
Adapter    "device-reminder": 1.2.9  , installed 1.2.9
Adapter    "discovery"    : 3.0.5    , installed 3.0.5
Adapter    "doorbird"     : 0.1.5    , installed 0.1.5
Adapter    "echarts"      : 1.0.12   , installed 1.0.12
Adapter    "fritzdect"    : 2.2.3    , installed 2.2.3
Adapter    "fullybrowser" : 2.1.2    , installed 2.1.2
Adapter    "hm-rega"      : 3.0.43   , installed 3.0.43
Adapter    "hm-rpc"       : 1.15.12  , installed 1.15.12
Adapter    "ical"         : 1.13.1   , installed 1.13.1
Adapter    "influxdb"     : 3.1.7    , installed 3.1.7
Adapter    "info"         : 1.9.19   , installed 1.9.19
Adapter    "javascript"   : 6.0.0    , installed 6.0.0
Controller "js-controller": 4.0.23   , installed 4.0.23
Adapter    "mobile"       : 1.0.1    , installed 1.0.1
Adapter    "mqtt"         : 4.0.7    , installed 4.0.7
Adapter    "nut"          : 1.5.1    , installed 1.5.1
Adapter    "openweathermap": 0.3.0   , installed 0.3.0
Adapter    "ping"         : 1.5.3    , installed 1.5.3
Adapter    "rpi2"         : 1.3.2    , installed 1.3.2
Adapter    "sainlogic"    : 0.9.0    , installed 0.9.0
Adapter    "sayit"        : 1.12.6   , installed 1.12.6
Adapter    "shelly"       : 6.0.0    , installed 6.0.0
Adapter    "simple-api"   : 2.7.0    , installed 2.7.0
Adapter    "socketio"     : 6.1.8    , installed 6.1.8
Adapter    "sourceanalytix": 0.4.14  , installed 0.4.14
Adapter    "tankerkoenig" : 2.1.1    , installed 2.1.1
Adapter    "telegram"     : 1.14.1   , installed 1.14.1
Adapter    "tr-064"       : 4.2.16   , installed 4.2.16
Adapter    "trashschedule": 2.0.3    , installed 2.0.3
Adapter    "upnp"         : 1.0.21   , installed 1.0.21
Adapter    "vis"          : 1.4.15   , installed 1.4.15
Adapter    "web"          : 5.2.4    , installed 5.2.4
Adapter    "wiffi-wz"     : 2.2.1    , installed 2.2.1
Adapter    "wolf-smartset": 1.0.0    , installed 1.0.0
Adapter    "ws"           : 2.1.3    , installed 2.1.3

Would you like to upgrade admin from @6.2.6 to @6.2.10 now? [(y)es, (n)o]: n
No upgrade of "admin" desired.
klu@iobroker:~ $

**Comment by Apollon77** [comment]
Bitte Admin auf 6.2.10 updaten oder höher. gehts dann wieder?

**Comment by Klaus-Lucas** [comment]
Ja, damit keine Abstürze mehr. Anhand des Updatetextes für den Admin:
6.2.11(vor 2 Tagen)
• Das Eingabefeld Text in JSON-Konfiguration korrigiert
war das nicht zu vermuten.
Trotzdem bekomme ich keine aktuellen Daten mehr bzw. bei Neuanlage wird nur das Statusfeld angelegt.

Hier mal ein paar Screenshots von meinen S0-Adaptern.
Z_Strom_Bezug ist der einzige, der Werte übernimmt:

Z_Strom_Eingespeist und Z_Strom_Solar haben zwar Werte, aber kommen in der Queue nicht an. Laut Status im Adapter werden alle Zähler erkannt und alle Zähler haben Werte und zeigen den Status, dass sie zum Server eine Verbindung haben.

![Z_Strom_Bezug](https://user-images.githubusercontent.com/36620907/182024563-5419e78b-a693-4468-a062-a6dad48e23a3.jpg)

![Z_Eingespeist__Verbunden](https://user-images.githubusercontent.com/36620907/182024654-81f4684b-df0b-4fb6-be1f-5dafd4eb262c.jpg)

![Z_Eingespeist_Main](https://user-images.githubusercontent.com/36620907/182024672-8e2b93b3-4f8f-4287-ba12-ec6283c36750.jpg)

![Z_Eingespeist__Verbindung](https://user-images.githubusercontent.com/36620907/182024944-784e5b68-e580-4ccf-8744-ee550863167f.jpg)

![Z_Eingespeist_MQTT_enabled](https://user-images.githubusercontent.com/36620907/182024683-51395c61-028e-4f05-a948-511633c7f633.jpg)

![Z_Eingespeist_Werte](https://user-images.githubusercontent.com/36620907/182024691-edfaed07-a943-4815-8892-033b8e2e9a34.jpg)

![Z_Solar_Main](https://user-images.githubusercontent.com/36620907/182024706-116b109e-63c6-48d1-b6f2-488b33aca7f1.jpg)

Habe ich da einen Fehler in einer Konfig, den ich übersehen habe?
![MQTT_Adapter_S1](https://user-images.githubusercontent.com/36620907/182024955-305292cf-7691-4282-8d15-169a0d8378e9.jpg)

![MQTT_Adapter_S2](https://user-images.githubusercontent.com/36620907/182024957-97414ace-3916-47c0-a511-2fbc2bdbf808.jpg)

Hier das Log. Ab ca. 13:06 Uhr habe ich auf Silly umgestellt um alles zu sehen:
[Log.txt](https://github.com/ioBroker/ioBroker.mqtt/files/9228757/Log.txt)
