### ISSUE TITLE
Login wird nicht gespeichert in 3.0.6

### ISSUE THREAD

**Issue by maxxe88** [ioBroker/ioBroker.mqtt#313]
Es lassen sich keine Daten speichern in 3.0.6, bin wieder zurück auf 2.7.4. Da geht es.

**Comment by Apollon77** [comment]
Was genau wird nicht gespeichert? Welche Admin version? Mehr details bitte? Screenshots?

**Comment by maxxe88** [comment]
Entschuldigung, Es war Admin 5 und man konnte keine Daten speichern. Wenn ich z.b. Die Login Daten eingeben wollte konnte ich nicht auf Speichern gehen. Es ist einfach nichts passiert. Inzwischen hab ich auf Admin 6 gewechselt. Ich werde mal testen wie es jetzt ist.
