### ISSUE TITLE
mqtt-Adapter should not specify any data type except mixed when states are created

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.mqtt#318]
When the mqtt-Adapter creates a state it should neither analyse nor define a specific data-type. mqtt allows to change the date-type to any state at any time. If mixed allows to return any type - this is perfect. 

Data-Type checking should be disabled at all for mqtt-topics.

**Comment by Apollon77** [comment]
The adapter kind of does that already. On first data receive we try to detect the type and define it. As soon as any other value is received with a different type the object is adjusted to be type "mixed" which is the ioBroker term for "can be anything". is that not sufficient already? Yes you have one log line for each "update of object" case, but that should be it

**Comment by mickym2** [comment]
Yes this is sufficient. May be the person who posted the problem has not installed the newest version. https://forum.iobroker.net/topic/57778/mqtt-tasmota-datenpunkt-falscher-type

 So if already implemented this can be closed.
