### ISSUE TITLE
Auswahl der gesendeten Topics

### ISSUE THREAD

**Issue by Th301** [ioBroker/ioBroker.mqtt#320]
Moin zusammen,

vielleicht bin ich einfach blind oder so aber wie stelle ich denn im Server/Broker Mode ein, welche Adapter-Daten publiziert werden? Aktuell sendet der Broker ausnahmslos alles was er an Daten von sämtlichen Adaptern zur Verfügung hat, was bei einer Anbindung an Loxone doch irgendwie exorbitant viele Topics sind. Wie verhindere ich das?

**Comment by Apollon77** [comment]
An sich stellst Du in den settings ein was der adapter subscriben soll ... wenn du da "*" reinschreibst dann macht er alles, sonst dort eine Liste. siehe https://github.com/ioBroker/ioBroker.mqtt#server-settings ... dort unter "Mask to publish own states"

**Comment by Th301** [comment]
Moin, danke für die Rückmeldung. Ich war einfach zu doof beim ersten Versuch. Hat nun geklappt, danke! :)
