### ISSUE TITLE
Subscription problem with topic segment length ( /x/y/__too_long__/z) or '#' sign in object name

### ISSUE THREAD

**Issue by alexmyself** [ioBroker/ioBroker.mqtt#323]
Hello, i'm facing a strange problem regarding subscription on a particular topic:

Subscribing to
'shelly/0/shellyplus1pm_3c610572ace0_1/uptime' doesn't works
but subscribing to 
'shelly/0/+/uptime' works
No error is shown in the iobroker logs, neither in client (node+mqtt.js), but the client  never receives anything for the long form.

With same adapter all the followings (and many others) are ok:
'shelly/0/info'
'shelly/0/info/connection'
'shelly/0/+/connection'
'shelly/0/info/+'
'shelly/0/info/#'
'shelly/0/+/Relay0'
'shelly/0/+/Relay0/Switch'
'shelly/0/*'
'shelly/0/#'
so handling of wildcards and global typo seems out of the problem scope.
When concerned, subscriptions gives all messages of all topics and sub-topics, received topics names are corrects even those containing 'shellyplus1pm_3c610572ace0_1'.

Iobroker log messages about subscribes seems ok (regexes are "equals/similar", nothing is different when the particular segment 'shellyplus1pm_3c610572ace0_1' appears):
`
subscribes on "shelly/0/shellyplus1pm_3c610572ace0_1/uptime" with regex /mqtt\.0\.shelly\.0\.shellyplus1pm_3c610572ace0_1\.uptime/
subscribes on "shelly/0/shellyplus1pm_3c610572ace0_1/uptime" with regex /shelly\.0\.shellyplus1pm_3c610572ace0_1\.uptime/
`

It looks likes the length of the segment 'shellyplus1pm_3c610572ace0_1' is causing problems,
or maybe it is related to the presence of '#' in the object name, the path of the object is: 'shelly.0.shellyplus1pm#3c610572ace0#1' in the iobroker Objects view.

The conf 'Maximum topic name length' is actually set to 1000.
'Publish own states on connect' is on and delay is 2000.

I've tried subscriptions to many variations of topics 'paths' whose behave correctly, but anything starting with 'shelly/0/shellyplus1pm_3c610572ace0_1' simply never returns any message.

Using the '+' wildcard as a workaround is not an option as the segment causing the problem is the device identifier.

I'm using iobroker docker image, all adapters are up to date, mqtt one is the 4.0.7, admin is 6.2.22, shelly is 6.0.0.

**Comment by Apollon77** [comment]
Please enable debug log, then enableenhanced log in settings of adapter. Then create log and etell where you got partial lines from and when. With just such a "without any context line" noone can support

**Comment by alexmyself** [comment]
Hello,
sorry to not had provided enough things,
thanks to pointing me to the debug path.

I've made some tests via the javascript adapter and finally the problem is the presence of hash symbol in the iobroker object 'path': "0_userdata.0.ts#Every#Minute".
This path  ( 0_userdata/0/ts#Every#Minute )is not 'subscribe-able', trying to do so gives an error on the client, syntax is not ok as per mqtt standard.

The misleading part is that subscribe to "0_userdata/0/#" returns messages for even a topic named "0_userdata/0/ts_Every_Minute".. 


I suppose this hasn't to be fixed/handled here so I'll made a report at shelly adapter to ask if it's possible to use something else than '#' as separator.


Thanks to all involved in this mqtt adapter!

**Comment by Apollon77** [comment]
Closed because? :-)

**Comment by alexmyself** [comment]
https://github.com/iobroker-community-adapters/ioBroker.shelly/issues/668

Report done at shelly adapter to not use '#+' in object name.

**Comment by Apollon77** [comment]
aahhh ... and yes this is completely correct :-)

**Comment by alexmyself** [comment]
Response there has been that nothing will change as it would breaks existing scripts.
Not really a surprise, had to try :)

It has been suggested to use alias as a workaround, so i've dig this way and finally it's ok.

I share here a lib which makes aliases for either one item, item and parents, item and parents and children, all purged of mqtt wildcards.

To use:
-enable javascript adapter,
-paste the following code in a file in the iobroker scripts tab,
-add at the end of the file add whatever you want to clone, here i clone all my shelly devices adapter:
AliasMaker.makeAliasTree('shelly.*' )
-add 'alias.0.*' in mqtt adapter
-subscribe
-enjoy :)

`
/**
 * Lib providing methods to create aliases with components names modified to avoid usage of mqtt wildcards chars ( #+ --> _ ):
 * 
 * AliasMaker.makeAliasLeave( originalId, aliasId ) --> create an alias with 'empty' parents, optionnally with a different _id than the original.
 * AliasMaker.makeAliasLine( originalId ) --> same as makeAliasLeave() but alias' parents are fulfilled as their original counterpart.
 * AliasMaker.makeAliasTree( originalId ) --> same as makeAliasLine() but every elements found under the original are created too.
 * 
 * 
 * Examples:
 * AliasMaker.makeAliasLeave('system.adapter.shelly.0.shellyplus1pm#3c610572ace0#1.uptime');
 * AliasMaker.makeAliasLeave('system.adapter.shelly.0.shellyplus1pm#3c610572ace0#1.uptime', 'myUptime' );
 * AliasMaker.makeAliasLeave('shelly.0.shellyplus1pm#3c610572ace0#1.uptime');
 * AliasMaker.makeAliasLeave('shelly.0.shellyplus1pm#3c610572ace0#1.uptime', 'myUptime' );
 * 
 * AliasMaker.makeAliasLine('shelly.0.shellyplus1pm#3c610572ace0#1.uptime');
 * 
 * AliasMaker.makeAliasTree('shelly.0.shellyplus1pm#3c610572ace0#1' );
 * AliasMaker.makeAliasTree('shelly' );
 * AliasMaker.makeAliasTree('*.Relay0.*' );
 */
class AliasMaker{

    /**
     * Mirror the entire tree of the provided IObroker _id in alias.0, ids are modified to avoid usage of mqtt wildcards ( #+ --> _ ).
     * The id can contains * wilcards as described in the iobroker doc for $() selector idFilter.
     * @param { String } originalId - An IObroker _id
     */
    static makeAliasTree( originalId ){

        const todos = [];

        $(`state[id=${originalId}]`     ).each(function (id, i) { AliasMaker.#_hashSet(id, todos); });
        $(`channel[id=${originalId}]`   ).each(function (id, i) { AliasMaker.#_hashSet(id, todos); });
        $(`device[id=${originalId}]`    ).each(function (id, i) { AliasMaker.#_hashSet(id, todos); });

        const alternativeName = AliasMaker.#_alternativeName( originalId )

        $(`state[id=${alternativeName}]`    ).each(function (id, i) {AliasMaker.#_hashSet(id, todos); });
        $(`channel[id=${alternativeName}]`  ).each(function (id, i) { AliasMaker.#_hashSet(id, todos); });
        $(`device[id=${alternativeName}]`   ).each(function (id, i) { AliasMaker.#_hashSet(id, todos); });

        todos.forEach( AliasMaker.makeAliasLine );
    }


    /** 
     * Make alias for the provided originalId and all of it's ancestors. Every ancestors of the provided id will be renamed to avoid mqtt wildcards (#+ --> _). 
     * @param { String } originalId - An IObroker _id
    */
    static makeAliasLine( originalId ){

        const cleanId = AliasMaker.#_cleanOriginalId( originalId );
        const members = cleanId.split('.');
        
        members.forEach( (o)=>{
            const remainings    = members.length - ( members.indexOf(o) + 1 );
            const path          = originalId.replace(new RegExp(`(?<member>${o})(\.[^.]+){${remainings}}$`), "$<member>");

            AliasMaker.makeAliasLeave( path );
        });
    }

    /**
     * Make an alias in "alias.0" for the originalId provided. IObroker willl generates parents segments as simples folders if they do not exists. 
     * The originalId will have mqtt wildcards replaced: '#+' --> '_' unless an aliasId is provided, which will stay untouched.
     * @param { String } originalId - The _id of any IObroker thing.
     * @param { String } [aliasId] -  The _id of the created thing, this aliasId will prepended as: "alias.0." + aliasId.
     */
    static makeAliasLeave( originalId, aliasId ){
        
        if( AliasMaker.#_blacklist( originalId ) ){ return; }

        const original          = AliasMaker.#_getTheOriginalThing( originalId );
        const aliasIdToUse      = ( aliasId )? 'alias.0.'+ aliasId : 'alias.0.' + AliasMaker.#_cleanAliasId( AliasMaker.#_cleanOriginalId( original._id ) );

        //Check if an alias already exists.
        try{
            if( getObject( aliasIdToUse ) !== null ){
                return;
            }
        }
        catch( err ){ throw new Error( err ); }

        log( 'Creating alias: ' + aliasIdToUse + ' for original ' + originalId );

        const aliasObj={
            _id   : aliasIdToUse
            , type  : original.type
            , common: original.common
            , native:{}
        };
        
        aliasObj.common.alias = { id: original._id }
        
       // alias.common.type = original.common.type;

        setObject( aliasObj._id, aliasObj, AliasMaker.#_makeAliasError );
    }



    /** Add an element to an array of elements if the array do not already contains it.
     * @param { any } element - Item to add to the array if not already there.
     * @param { Array } elements - The array in which to store the element.
     */
    static #_hashSet( element, elements){
        if( elements.indexOf(element ) === -1 ){ elements.push(element); }
    }

    
    /**
     * Returns the IObroker object corresponding to the _id provided.
     * @param { String } anyIobrokerId - The _id of any IObroker thing.
     * @return { Object }
     */
    static #_getTheOriginalThing( anyIobrokerId ){

        const o = getObject( anyIobrokerId ); if( o && o !== null ) return o;

        const o2 = getObject( AliasMaker.#_alternativeName(anyIobrokerId) ); if( o2 && o2 !== null ) return o2;

        throw new Error('----------!! Impossible to get the object/whatever for id: ' + anyIobrokerId );
    }


    /**
     * True if originalId contains something to avoid (ex.: plugins).
     * @param { String } originalId - An IObroker _id
     * @return { Boolean } 
     */
    static #_blacklist( originalId ){
        return (
            originalId.endsWith('plugins')
            || originalId.startsWith('alias')
            || originalId.startsWith('system.adapter.alias')
        );
    }

    /**
     * Removes /^system\.adapter\./ from the provided string.
     * @param { String } id - A IObroker _id.
     * @return { String }
     */
    static #_cleanOriginalId( id ){
        return id.replace(/^system\.adapter\./,'');
    }

    /**
     * Replace mqtt wildcards '#+' with '_' from the provided string.
     */
    static #_cleanAliasId( id ){
        return id
            .replaceAll('#','_')
            .replaceAll('+','_')
        ;
    }

    /**
     * Add or remove 'system.adapter.' from the provided string, this helps at finding objects, sometimes a method find with a full path, sometimes with a short one.
     * @param { String } originalId - An IObroker _id
     * @return { String } The id with or without 'system.adapter.'
     */
    static #_alternativeName( originalId ){
        return (originalId.startsWith('system.adapter.'))? AliasMaker.#_cleanOriginalId( originalId ): 'system.adapter.'+originalId ;
    }

    /** Log error if the setObject fails at alias creation.
     * @param { String } err - The error, whatever it means..
     */
    static #_makeAliasError( err ){
        if( err ){ log('Cannot setObject for an alias: ' + err ); }
    }

}

//AliasMaker.makeAliasLeave('system.adapter.shelly.0.shellyplus1pm#3c610572ace0#1.uptime');
//AliasMaker.makeAliasLeave('system.adapter.shelly.0.shellyplus1pm#3c610572ace0#1.uptime', 'myUptime' );
//AliasMaker.makeAliasLeave('shelly.0.shellyplus1pm#3c610572ace0#1.uptime');
//AliasMaker.makeAliasLeave('shelly.0.shellyplus1pm#3c610572ace0#1.uptime', 'myUptime' );
//AliasMaker.makeAliasLine('shelly.0.shellyplus1pm#3c610572ace0#1.uptime');
//AliasMaker.makeAliasTree('shelly.0.shellyplus1pm#3c610572ace0#1' );
AliasMaker.makeAliasTree('shelly.*' );
//AliasMaker.makeAliasTree('*.Relay0.*' );





`
