### ISSUE TITLE
Server / client in different subnets 

### ISSUE THREAD

**Issue by Randy1st** [ioBroker/ioBroker.mqtt#331]
Running the mqtt adapter in an iobroker docker container 

Since I put my mqtt clients in a different vlan and ip range than my Iobroker server the clients can’t connect anymore… 

Firewall rules of my UniFi usg pro are correct 

Anything I could do or is this a Problem of this adapter or maybe of mqtt?

**Comment by Randy1st** [comment]
thank you Apollon77 
actually i cannot access any of my Mqtt clients by telnt if I use telnet [ip] [port] even the ones I have already reconnected sucessfully with iobroker after i put them in another vlan. e.g. my heating - it uses another special iobroker mqtt adapter

it works with my mqtt iobroker host too but with none of the clients
I have to confess that I don´t use telnet very often

**Comment by Randy1st** [comment]
Are you sure that there is no restriction like the adapter is only listening on the subnet of the iobroker installation?

**Comment by Apollon77** [comment]
Exactly this I asked you to check:

> Additionally check settings in mqtt adapter where exactly he listens to

So what is set as "Bind" setting in config? SHow ascreenshot? Maybe there is still the old IP in? Ideally choose 0.0.0.0 there to listen for anything. This I said above in my last post

**Comment by Randy1st** [comment]
And I answered already

as long as I understand what you mean 😃 
Here’s a screenshot 
![8724EDF2-F44E-45DC-B621-534DC678E2E4](https://user-images.githubusercontent.com/109476751/198832528-853f9b91-8dc0-419f-9a94-9f23341e550f.jpeg)

**Comment by Apollon77** [comment]
But with this the adapter will listen on 0.0.0.0, so all traffic that the "host" gets ... In fact check your docker config ... I can not help you there. sorry (no docker expert)

**Comment by Randy1st** [comment]
Since Iobroker sees and is connected to all the other clients (in the subnet of my mqtt clients) it's mqtt that makes the difference.
Yes, it might be that the docker container blocks something - I doubt it... 

Ok thanks anyway I will try to get the mqtt clients in the management subnet of Iobroker

**Comment by Randy1st** [comment]
Bought another device that works 
Seems to be a layer 8 problem .... 
sorry 
Adapter works

**Comment by Apollon77** [comment]
Thank you for the feedback!
