### ISSUE TITLE
MQTT Server does not start

### ISSUE THREAD

**Issue by cxt666** [ioBroker/ioBroker.mqtt#35]
mqtt.0 does not start; on the webui the instance remains yellow
On the OS side, a port is opened for websocket and mqtt socket only on tcpv6, not on v4. The issue occured after reininstalling iobroker on the same Raspi on a new SDcard.

**Versions**

```
iobroker version 1.4.2

Adapter    "admin"         : 3.5.10   , installed 3.5.10
Adapter    "cloud"         : 2.6.2    , installed 2.6.2
Adapter    "discovery"     : 1.2.4    , installed 1.2.4
Adapter    "flot"          : 1.9.1    , installed 1.9.1
Adapter    "history"       : 1.8.5    , installed 1.8.5
Adapter    "hm-rega"       : 2.0.0    , installed 2.0.0
Adapter    "hm-rpc"        : 1.8.0    , installed 1.8.0
Adapter    "javascript"    : 3.6.4    , installed 3.6.4
Controller "js-controller" : 1.4.2    , installed 1.4.2
Adapter    "luftdaten"     : 0.0.5    , installed 0.0.6
Adapter    "mobile"        : 0.4.11   , installed 0.4.11
Adapter    "mqtt"          : 2.0.3    , installed 2.0.4
Adapter    "rpi2"          : 0.3.2    , installed 0.3.2
Adapter    "simple-api"    : 2.0.0    , installed 2.0.0
Adapter    "socketio"      : 2.1.1    , installed 2.1.1
Adapter    "sonoff"        : 2.2.2    , installed 2.2.2
Adapter    "telegram"      : 1.2.4    , installed 1.3.6
Adapter    "tr-064"        : 0.4.14   , installed 0.4.18
Adapter    "vis"           : 1.1.7    , installed 1.1.7
Adapter    "web"           : 2.4.1    , installed 2.4.1
```

**Tried:**

- using ioBroker.sonoff --> starts successfully, but ONLY with IPv4 sockets
- restarting ioBroker
- rebooting the Raspi
- reinstalling ioBroker.mqtt

**ioBroker Log:**

```
   mqtt.0 | 2019-01-03 13:33:39.869 | info | Starting MQTT -WebSocket (Secure)' authenticated  server on port 1884
   mqtt.0 | 2019-01-03 13:33:39.868 | info | Starting MQTT  (Secure)' authenticated  server on port 1883
   mqtt.0 | 2019-01-03 13:33:38.699 | info | starting. Version 2.0.4 in /opt/iobroker/node_modules/iobroker.mqtt, node: v8.15.0
   mqtt.0 | 2019-01-03 13:33:38.541 | info | States connected to redis: 127.0.0.1:6379
```

**netstat --listen**

```
pi@ioBroker:~ $ netstat --listen
Aktive Internetverbindungen (Nur Server)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 ioBroker.fritz.bo:12001 0.0.0.0:*               LISTEN     
tcp        0      0 localhost:9001          0.0.0.0:*               LISTEN     
tcp        0      0 ioBroker.fritz.bo:12010 0.0.0.0:*               LISTEN     
tcp        0      0 localhost:6379          0.0.0.0:*               LISTEN     
tcp        0      0 ioBroker.fritz.bo:18701 0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN     
tcp6       0      0 localhost:6379          [::]:*                  LISTEN     
tcp6       0      0 [::]:tproxy             [::]:*                  LISTEN     
tcp6       0      0 [::]:8082               [::]:*                  LISTEN     
tcp6       0      0 [::]:8084               [::]:*                  LISTEN     
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN     
tcp6       0      0 [::]:1883               [::]:*                  LISTEN     
tcp6       0      0 [::]:1884               [::]:*                  LISTEN     
udp        0      0 0.0.0.0:bootpc          0.0.0.0:*                          
udp        0      0 0.0.0.0:34425           0.0.0.0:*                          
udp        0      0 0.0.0.0:mdns            0.0.0.0:*                          
udp6       0      0 [::]:dhcpv6-client      [::]:*                             
udp6       0      0 [::]:54827              [::]:*                             
udp6       0      0 [::]:mdns               [::]:*                             
raw6       0      0 [::]:ipv6-icmp          [::]:*                  7
```

Issue seems not to be connected to *MQTT Server/broker startet nicht #22*
How can I instruct iobroker.mqtt to also open a v4 port?

**Comment by berndmr** [comment]
`tcp6       0      0 [::]:1883` 
normally also listen on IPv4. Yellow means "no client connected".

`cat /proc/sys/net/ipv6/bindv6only` 
should be "0" on linux systems.
If it is "1", try 
`sysctl -w net.ipv6.bindv6only=0` 
then restart instance.

Shure you don´t have a client problem?

**Comment by berndmr** [comment]
try
`telnet IPv4ADRESS 1883`
if it shows 
`Connected to XXXXi.
Escape character is '^]'.`
then a server is correctly running and bind to the port.

Next step is trying an Desktop MQTT-Client and look wat it says. 

Mines working perfect on IPv4:
`tcp6       0      0 [::]:1883               [::]:*                  LISTEN  `

**Comment by cxt666** [comment]
connecting to iobroker:1883 works also for me - but it'll be on v6.

I looked up ports of the other adapters and it seems that all the port from ioBroker OR its adapters are fired up on only one stack - either v4 OR v6.

- iobroker.admin --> ::8081
- iobroker.web --> ::8082
- iobroker.?? --> ::8084
- iobroker.mqtt --> ::1883
- iobroker.sonoff --> 0.0.0.0:1883

Not sure now if I'd better carry this issue over to iobroker or node.js?

**Comment by berndmr** [comment]
I said to use the IPv4 Adress of the device in telnet! Not the DNS-Name. 

And again: `::1883` with `bindv6only = 0` means Dual-Stack IPv4 **and** IPv6. 

So from what I see, ioBroker and Node.js did not make an error here. 
It look same as on my side here, and I can connect IPv4 and IPv6.

**Comment by cxt666** [comment]
iobroker status returns errors now. Will close issue and reinstall iobroker from scratch
