### ISSUE TITLE
State has to be written with setBinaryState/Async, because its object is of type "file"

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.mqtt#359]
Version 4.0.7 in /opt/iobroker/node_modules/iobroker.mqtt, node: v16.19.1, js-controller: 4.0.24

Trying to get this to play nicely with [Frigate](https://frigate.video/), followed instructions in #115 and changed state of a topic to type file*

Now this warning appears in the log:

```
2023-04-24 15:53:52.091  - warn: mqtt.0 (28297) State to set for "mqtt.0.frigate.csw1.person.snapshot" has to be written with setBinaryState/Async, because its object is of type "file"
```

*IMHO, this 'change state to file' advice in #115 is a horrible hack and needs work :disappointed:

**Comment by Apollon77** [comment]
will be fixed by #343
