### ISSUE TITLE
Topics are not created correctly

### ISSUE THREAD

**Issue by DoImant** [ioBroker/ioBroker.mqtt#362]
If a data object is to be released for publishing via the gear icon, underscores in the ID path become spaces in the topic field.

Example: 
The ID "0_userdata.0.Var.air_pressure.diff_1std" becomes the topic "0 userdata.0.Var.airpressure.diff 1std". The underscores have to be entered manually in the topic input field afterwards.

**Comment by Apollon77** [comment]
Please provide a debug log

**Comment by DoImant** [comment]
I don't know how to create a debug log for this case. The plugin creates a topic that does not match the object path. It is then simply not published this object. To my knowledge nothing is logged. 

Maybe a screenshot helps. The (needed) underscores are missing. 

![wrong-topic](https://user-images.githubusercontent.com/43279394/235318582-8e5cfd0e-9572-4334-8645-1ca70127a430.jpg)

If they are added manually afterwards, everything works fine.

**Comment by Apollon77** [comment]
mqtt-client adapter !== mqtt ... ?! Wrong adapter for this issue?

**Comment by DoImant** [comment]
Why a wrong adapter? It works fine as long as there is no underscore in an object ID. 

But now it is the case that "**0_userdata.0**" is predefined for manual objects in ioBroker.  

The Mqtt-client adapter automatically converts the object ID into a topic string if an object is to be published for an MQTT broker.  However, if an object ID contains underscores, these are converted to a space. But this is wrong. You have to manually change the spaces back to underscores in the generated topic.  As far as I know, it is generally recommended not to use (white) spaces in a topic string. 

I can't imagine that this is an intended behavior of the adapter. 

Is my description so incomprehensible?

**Comment by Apollon77** [comment]
Your screenshot shows the settings of the "mqtt-client" adapter ... this here is the "mqtt" adapter ...

**Comment by DoImant** [comment]
Sh*&!. Now I get it... OK my fault. Sorry.

**Comment by Apollon77** [comment]
np, all fine :-) Most likely we read in other repo then again :-)

**Comment by DoImant** [comment]
Well, I found the right repo and saw that the same issue was already opened there in 2019. The problem is therefore known, so it probably makes little sense to address this again...

**Comment by Apollon77** [comment]
Thenn add a "thumbs up" to the issue to show that you would also be interested in a fix and maybe link here
