### ISSUE TITLE
no events if a field is configured as a file.

### ISSUE THREAD

**Issue by Waly-de** [ioBroker/ioBroker.mqtt#369]
**Describe the bug**  
when I change a state to "File", I cannot monitor changes:

on({id: /mqtt.2.app.device.property.HWXXXXXXXXXXXX/, change: 'any'}, function (obj) {
    log("EVENT!")
});

fires no events at all

**Versions:**  
 - Adapter version: 4.1.1
 - JS-Controller version: 4.0.24
 - Node version: v16.19.0
 - Operating system: linux

**Comment by Apollon77** [comment]
Yes correct. This will be adjusted as soon as we move from "binary states to real files and with js-controller 5, else not supported right now,sorry.

duplicate #343
