### ISSUE TITLE
After installing the latest admin adapter version i can't connect to the ui anymore (HomeAssistant)

### ISSUE THREAD

**Issue by Presl1983** [ioBroker/ioBroker.mqtt#383]
**Describe the bug**  
After installing the latest admin adapter (from 4.2.1 -> 6.8.0) version i can't connect to the ui anymore (HomeAssistant)

**To Reproduce**  
![image](https://github.com/ioBroker/ioBroker.mqtt/assets/142180290/85bd0507-dbac-449e-a22a-0a003e0d6a48)
i need to update because of mqtt broker

**Expected behavior**  
should be up and running after the update

**Versions:**  
 - Adapter version: 4.2.1
 - JS-Controller version: latest update
 - Operating system: Home Assistant

**Comment by Apollon77** [comment]
You also created admin issue. So I close here.
