### ISSUE TITLE
send identical message again via MQTT

### ISSUE THREAD

**Issue by DieWaldfee** [ioBroker/ioBroker.mqtt#412]
Hi together,

I have in my home automation some own programmed ESP32 - nice things by the way :-)
The communication is via MQTT. For example my pool or the garage is connectet into iobroker on this way.<br>
Now the thing is, that the MQTT-Adapter doesnt send a message, if the datapoint hat still the value. An example:
the picture shows an datapoint "command"
![grafik](https://github.com/ioBroker/ioBroker.mqtt/assets/66571311/ea6d3154-6d89-4efd-b89b-bdbb47edd98c)
in this DP the value "Tortrigger2" is written (a part of my solution, but later...)
If you send now "Tortrigger2" again the MQTT-adapter woun`t send it out again - i think a good choice for data reduction, but in my situation: nothing happens. My ESP listens to the "command"-message an acts on it. If it is not send out - i got a problem.<br>
if you send the messages manually via MQTT-Explorer or other MQTT tools my ESP32 code works find as expected.<br>
Trivial solution: build an action to "Tortrigger" and "Tortrigger2" in the ESP32 - check whats the value now via blockly and send the other message with your script on the iobroker.
...ok works. <br>
(The project will be soon on Github - another ESP32-Project is <a href="https://github.com/DieWaldfee/Heizstabsteuerung"> Heizstabsteuerung </a> with the same technic but for controlling an electrical heater to use your own solar electricity in your heating system at home - PCB, code etc. is there)
<p>
In the past i got an similar task with an shelly. solution there: just send rubbish an then send the command - ok, works too, but...
<p>
if you ask yourself: why do i want do do this? 
easy answer: (1) if you are unable to catch an reboot of the ESP32 or (2) if your iobroker reboots and the starting skript is unable to check the state of your ESP32 or (3) for a simple trigger.
<p>
Now to the solution: 
if possible - get an option to the datapoint to send every message even if it is equal. maybe on the gear behind the DP to check the otpion explicit for a single datapoint. this would reduce programming affort on skripts and in my case in the ESP32 code.

thanks - Die Waldfee :-)

**Comment by DieWaldfee** [comment]
Update: the "Garagentor"-project is now online: <a href="https://github.com/DieWaldfee/Garagensteuerung"> Link </a>

Die Waldfee :-)

**Comment by Marc-Berg** [comment]
Maybe I'm missing something, but there is a "publish only on change" option in the instance settings. Simply uncheck the box.

**Comment by DieWaldfee** [comment]
@Marc-Berg: i`ve missed that :-) thats exacly what i searched for. I just tested that. Thanks.
