### ISSUE TITLE
CCU-Jack all values habe this format {"ts":1711112812496,"v":false,"s":0}

### ISSUE THREAD

**Issue by FraatTailscale** [ioBroker/ioBroker.mqtt#438]
Hallo,
I'm trying to get data vrom CCU-Jack. All values have the same prefix, suffix {"ts":1711112812496,"v":false,"s":0}. 
Is there a way to the only the value v: ?

**Comment by Apollon77** [comment]
This souls like you need a small javascript that subscribed to the state where the data come in and pars e th json and then store the pure value in a new state.
