### ISSUE TITLE
Bug in Server mode when publishing Set topic

### ISSUE THREAD

**Issue by Vippis2000** [ioBroker/ioBroker.mqtt#442]
Hi,

I'm using MQTT Broker to communicate between AlsavoCtrl made by @strandborg and IOBroker. 

I'm experiencing a bug, that if a send payloads to AlsavoCtrl via "/homie/alsavo/controls/power/set" topic the message is not interpreted, ONLY once when restarting the instance.

Example. If set "/homie/alsavo/controls/power/set" to "false" my pool heat pump should be switched off. The message is only correctly understood when restarting the instance of MQTT broker.

Version 5.2.0

**Comment by Apollon77** [comment]
so, solved?

**Comment by Vippis2000** [comment]
> so, solved?

yes!
