### ISSUE TITLE
MQTT uses up all memory

### ISSUE THREAD

**Issue by mediaDS** [ioBroker/ioBroker.mqtt#47]
ioBroker Admin 3.6.0
js-Controller 1.4.2
MQTT Broker 2.0.4

ioBroker runs on a Odroid C2 with 2GB RAM. There are three MQTT clients who send their telemetry to the broker, 2 ESP8266 with MQTT client and 1 Raspberry Pi 3B+ with Mosquitto.

After a few hours the broker sucks up all memory - it grows from around 35.5MB after restart to about 920MB. I have to restart the adapter to get back to 35.5MB. Is this normal behauviour or a memory leak/bug?

Edit:

The data packets from each client are between 20-200 bytes long and are send every 120 seconds.

**Comment by Apollon77** [comment]
which nodejs version is used? nodejs < 8.12 had a memory leak that could cause this independent from the adapter

**Comment by mediaDS** [comment]
It's  Node.js: v8.15.1 and NPM: 6.4.1

**Comment by mediaDS** [comment]
Well, today I got lots of memory problems with ioBroker, it was reacting very sluggish and all was slowed down. The mqtt broker grabbed all memory. So this problem affects the whole system. Please fix it. If you need more information or specific log/debug files, please don't hesitate to ask.

The memory footprint goes from 35.7MB to arround 90MB after a few seconds and up to 900MB after 12 hours. Is the broker caching all the incoming data continously?

One client is my Anycubic 3D printer which sends a JSON blob with temperatures (~40 bytes), the second client is my heating controller EMS-ESP which is sending two rather big JSON blobs with boiler data every 2 minutes (2 x ~100 bytes), the third is my weather station which sends no JSON blob but only  a handful of single temperature/humidity/wind data values. The fourth client is just sending the SoC temperature of a Raspberry Pi every 2 minutes.

The data received from the clients does not explain a memory consumption of more than 900MB after 12 hours.

**Comment by Apollon77** [comment]
Please enable debug log but this can be many logs written then!
Then please let it run till it happens again ... do you maybe see differences in log to where everything was ok?

**Comment by mediaDS** [comment]
I'll enable the debug log then. But first I will try to use my mqtt clients one after the other just to rule out it is one of them who is causing the memory problem. Then I will re-enable them one-by-one and hope there is something useful in the logs. I'll keep you posted.

**Comment by Apollon77** [comment]
Thank you very much!

**Comment by mediaDS** [comment]
You are welcome :)

Well, this is weird - I disabled the MQTT client on the Pi which was transmitting just the SoC temperature. I used the mosquitto package for Raspbian. Now everything is ok again - the memory footprint of the MQTT broker stays at arround 80-90MB. 

After logging and step-by-step debugging I found the mosquitto client to be the trigger of the memory problem. I don't know how but I guess the problem is solved for now. Yay.

I will do further testing on a different controller during the next few days. But it seems your adpater is not the problem.

Thanks and kind regards,
Dieter

**Comment by Apollon77** [comment]
Thank you for the update. Should we close this issue then?! But in fact it would be interesting what caused it.

**Comment by mediaDS** [comment]
Yes, you may close it for now. I will keep you posted about my investigation of this issue - I never ever had any problems with the mosquitto client software.

Your adapter runs fine as of this morning - using a stable memory footprint of about 93.3MB.

Have a nice day,
Dieter

**Comment by Apollon77** [comment]
Great! Thank you

**Comment by mediaDS** [comment]
As a reference: This is the script I used for the latest mosquitto client package for Raspbian:

```
        cpu=$(</sys/class/thermal/thermal_zone0/temp)
        cpu=$(echo "$cpu/1000" | bc -l)
        mosquitto_pub -h Casper -p 1883 -t controller/$HOSTNAME/cpu/temperature -m $cpu
        sleep 120
```
It definately triggers the huge memory footprint. I tested "sleep" with 30 and 120. MAybe you have an idea.

**Comment by Apollon77** [comment]
is the "mosquitto_pub" process end after publishing that one message? Not that more and more connections are created or such?!

**Comment by mediaDS** [comment]
Hmm, this is what I am trying to find out right now. I'll keep you updated.

**Comment by Apollon77** [comment]
other option could indeed be the adapter when it comes to many connections ... maybe the cleanup of the classes after a connection has ended (if the tool stops after sending that one item) is not working properly

**Comment by mediaDS** [comment]
Hmm, it says on the website

`mosquitto_pub is a simple MQTT version 3.1.1 client that will publish a single message on a topic and exit.
`

And it does exactly that. Only one single process sending the data and exiting afterwards. So, it seems it is not the mosquitto client. I'll let it run a while (until tomorrow) to see if the adapter grabs all the memory again. I will keep you posted.

**Comment by Apollon77** [comment]
maybe also turn adater into debug loglevel (Instances -> Expert mode -> column Logstufe) and check the logs ... would be interesting to see

**Comment by mediaDS** [comment]
This is weird, everything is working now and the memory footprint stays stable at 99MB. I did not change anything. 
I think we can close this now - your adpater seems to work as it should. I will keep an eye on it over the next days. If there is any change I will let you know. 

Keep up the good work and have a nice weekend,
Dieter
