### ISSUE TITLE
Binary payload corrupt. (Valetudo PNG)

### ISSUE THREAD

**Issue by desq42** [ioBroker/ioBroker.mqtt#48]
https://github.com/Hypfer/Valetudo/issues/131

> "Theres definitely something wrong there. PNGs always start with 0x89 0x50 0x4e 0x47. Yours starts with 0xef"

As @Hypfer mentions mosquitto 1.4.10 handels the binary payload correct.

**Comment by robotastic-io** [comment]
I can confirm this issue. As mentioned here https://github.com/rand256/valetudo/issues/230 valetudo-mapper works fine with mosquito but hast issues with iobroker.mqtt
