### ISSUE TITLE
mqtt verstümmelte Datensätze Prüfsumme

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.mqtt#50]
der ioBroker empfängt manchmal verstümmelte Datensätze.
Im Topic steht z.B. "mqtt.0.haus.kell1_]" statt "keller".
In den Daten steht statt der Temperatur "atus/letzter FehlerR" usw..

Bei mqtt ist ja eine Prüfsumme z.B. MD5 vorgesehen bzw. möglich.
Wie kann man die im Broker bzw. im ESP8266 PubSubClient.cpp aktivieren?

**Comment by Zwer2k** [comment]
Hab das selbe Problem. Fehler tritt bei zwei Clients auf die auch PubSubClient verwenden. Bei einem verwende ich ESPEasy der zweite ist selbst geschrieben. Blöderweise lassen sich die Einträge nicht mehr aus der Objekt-Übersicht löschen, da die Einträge Sonderzeichen enthalte (Beispiel: /Gartenha0"/Gartenhaus/InnerP).
