### ISSUE TITLE
Gibt es einen Timeout, sodass ein Sender die Verbindung zum MQTT-Adapter verliert?!

### ISSUE THREAD

**Issue by m50434** [ioBroker/ioBroker.mqtt#56]
Folgendes Szenario:
Ich habe einen ESP8266, der eine Verbindung zum MQTT-Adapter im IOBroker aufbaut.
Dies funktioniert auch problemlos.

Drücke ich einen Knopf (der ESP8266 ist entsprechend verkabelt), sowird eine (entprellte) Methode aufgerufen, die einmalig eine Nachricht (mit client.publish("...")) an den MQTT-Server sendet.
Diese Nachricht wird auch problemlos empfangen und ich kann sie in IO-Broker sehen.
Blöderweise verliert der ESP8266 jedoch sehr schnell (und wirklich reproduzierbar regelmäßig) die Verbindung zum MQTT-Server, sodass er sich dann automatisch reconnected.

Das verückte ist, dass ich dieses Verhalten unterbinden kann, in dem ich dauern (in 2 Sekunden-Abständen) eine Nachricht an den MQTT-Server schicken kann. Dann ist es auch egal, wann ich den Knop drücke: Die Nachricht kommt ebenfalls an. Das läuft hier jetzt bei mir ohne Verbindungsabruch seit ca. 6 Stunden durch.

Lasse ich allerdings dieses ständige Senden in 2-Sekunden-Abständen weg, so verliert der ESP8266 innerhalb von 5 Minuten sofort mindestens einmal die Verbindung (und braucht dann manchmal auch ewig, bis er sich wieder verbunden hat). Im logfile des IOBroker steht dann übrigens einfach nur "mqtt.0 Client [ESP8266Client-4bf0] connection closed: closed" und (leider) keine Fehlermeldung oder sowas.

Ich habe im ESP8266 auch keinen deepsleep oder sowas programmiert, daher verstehe ich überhaupt nicht, warum er ständig die Verbindung sofort verliert.

Meine Frage ist, ob es von Seiten des MQTT-Adapters vielleicht irgendwie einen Timeout gibt, zu dem der Server die Verbindung schließt, wenn er eine bestimmte Zeit lang keine Nachricht erhalten hat?!

**Comment by Marsx79** [comment]
Same problem here. Any solution for this?

**Comment by Apollon77** [comment]
Bringt debug log ggf mehr Infos?
