### ISSUE TITLE
commands are not transmitted

### ISSUE THREAD

**Issue by t1m02k16** [ioBroker/ioBroker.mqtt#60]
after my update to 1.5.11 mqtt does not react anymore. The adapter connects perfectly, but switching process are not transmitted. Does anyone have an idea or the same problem?

**Comment by jangatzke** [comment]
I have the same problem with the current version. I configured some sonoff devicrd with ESP easy for Christmas. Everthing was working perfectly. Now I tried to use the sonoffs for party lights and the do not switch any more. I can see the successfull connect in the log, but commands are not transmited. Changed nothing but the version of the mqtt adapter.

**Comment by pedrr** [comment]
Same here for me with version 2.0.4

**Comment by Apollon77** [comment]
How you control them? Please show code. Or do you try via admin?

**Comment by jangatzke** [comment]
Sorry, I migrated to Tasmota and the sonoff adapter and I have already cleaned my iobroker from the mqtt stuff. Switching via admin did not work either.
