### ISSUE TITLE
2.1.0 Error

### ISSUE THREAD

**Issue by vr6syncro** [ioBroker/ioBroker.mqtt#61]
Ich bekomme folgenden Fehler. Adapter wird aber wie es aussieht weiterhin ausgeführt. 

host.ioBroker | 2019-06-06 18:01:20.714 | error | instance system.adapter.mqtt.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2019-06-06 18:01:20.714 | error | by controller[0]: at Connection.emit (events.js:211:7)
Caught | 2019-06-06 18:01:20.714 | error | by controller[0]: at emitOne (events.js:116:13)
Caught | 2019-06-06 18:01:20.714 | error | by controller[0]: at Object.onceWrapper (events.js:315:30)
Caught | 2019-06-06 18:01:20.714 | error | by controller[0]: at Connection.<anonymous> (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt-connection/connection.js:53:12)
Caught | 2019-06-06 18:01:20.714 | error | by controller[0]: at Connection.emit (events.js:211:7)
Caught | 2019-06-06 18:01:20.714 | error | by controller[0]: at emitOne (events.js:116:13)
Caught | 2019-06-06 18:01:20.714 | error | by controller[0]: at Connection.emitPacket (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt-connection/connection.js:10:8)
Caught | 2019-06-06 18:01:20.714 | error | by controller[0]: at Connection.emit (events.js:211:7)
Caught | 2019-06-06 18:01:20.714 | error | by controller[0]: at emitOne (events.js:116:13)
Caught | 2019-06-06 18:01:20.714 | error | by controller[0]: at Connection.client.on.packet (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:803:34)
Caught | 2019-06-06 18:01:20.714 | error | by controller[0]: TypeError: Cannot read property 'find' of undefined
mqtt.0 | 2019-06-06 18:01:20.686 | info | terminating
mqtt.0 | 2019-06-06 18:01:20.184 | error | at Connection.emit (events.js:211:7)
mqtt.0 | 2019-06-06 18:01:20.184 | error | at emitOne (events.js:116:13)
mqtt.0 | 2019-06-06 18:01:20.184 | error | at Object.onceWrapper (events.js:315:30)
mqtt.0 | 2019-06-06 18:01:20.184 | error | at Connection.<anonymous> (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt-connection/connection.js:53:12)
mqtt.0 | 2019-06-06 18:01:20.184 | error | at Connection.emit (events.js:211:7)
mqtt.0 | 2019-06-06 18:01:20.184 | error | at emitOne (events.js:116:13)
mqtt.0 | 2019-06-06 18:01:20.184 | error | at Connection.emitPacket (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt-connection/connection.js:10:8)
mqtt.0 | 2019-06-06 18:01:20.184 | error | at Connection.emit (events.js:211:7)
mqtt.0 | 2019-06-06 18:01:20.184 | error | at emitOne (events.js:116:13)
mqtt.0 | 2019-06-06 18:01:20.184 | error | at Connection.client.on.packet (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:803:34)
mqtt.0 | 2019-06-06 18:01:20.184 | error | TypeError: Cannot read property 'find' of undefined
mqtt.0 | 2019-06-06 18:01:20.184 | error | uncaught exception: Cannot read property 'find' of undefined

**Comment by Zefau** [comment]
In Zeile
https://github.com/ioBroker/ioBroker.mqtt/blob/bad0b0d08833627df608beb33140e8d40520abd1/lib/server.js#L803
ist `client._messages` nicht definiert. Wofür genau nutzt du den MQTT Adapter?

**Comment by vr6syncro** [comment]
ich denke der Fehler trat auf als ich einen Wemos mit Espeasy angeschlossen hatte.

Scheit aber seit einiger Zeit nun sauber zu laufen.

**Comment by Apollon77** [comment]
We should try to prevent the error in any case

**Comment by Apollon77** [comment]
done in 2.1.4
