### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by hartwigm** [ioBroker/ioBroker.mqtt#62]
Ich nutzte mehrere Iobroker in einem Netzwerk. 
Diese tauschen die Daten über mqtt mit einem übergeordneten System. 

Wenn ich auf iobroker1 den mqtt.1 installiere funktioniert alles

Wenn ich nun auf der iobroker2 ebenfalls eine Instanz des mqtt installiere bekomme ich in der 2.04 und 2.10 Abbruchsfehler.

Installiere ich aber einen 2te Instanz also den mqtt.2 und lösche danach den mqtt.1 geht alles.

Aktuell bin ich bei iobroker4 und muss damit auch 4 mqtt Instanzen installieren, dass es funktioniert. 

Gibt es hier eine andere Lösung`?

**Comment by Apollon77** [comment]
Was meinst du mit Abbruch Fehler in der 2.04 und 2.10? Welche Fehler genau?
Was ist wo wir exakt installiert und wie konfiguriert? Logs? Bitte mal auf Debug log stellen. 

An sich sollten sich getrennte iobroker die sauber mit MQTT Clients bzw Server eingestellt sind keineswegs beeinflussen. 

Andere frage: warum nutzt du kein multihost?
