### ISSUE TITLE
Websocket-Verbindung mit PAHO (mqttws31.js) crasht Adapter Version 2.1.0

### ISSUE THREAD

**Issue by blumfisch** [ioBroker/ioBroker.mqtt#63]
Eine Verbindung über Javascript-Websocket per PAHO von einer Webseite aus: 

`client = new Paho.MQTT.Client("192.168.178.101", Number(1884), "/ws", "LABHTML");
`
crasht den Adapter ab Version 2.1.0 mit folgenden Fehlermeldungen:

iobroker:

mqtt.0	2019-07-16 19:13:20.566	info	Starting MQTT -WebSocket' server on port 1884
mqtt.0	2019-07-16 19:13:20.564	info	Starting MQTT ' server on port 1883
mqtt.0	2019-07-16 19:13:19.588	info	starting. Version 2.1.0 in /opt/iobroker/node_modules/iobroker.mqtt, node: v8.16.0
host.ioBroker-RasPi	2019-07-16 19:13:18.220	info	instance system.adapter.mqtt.0 started with pid 2957
host.ioBroker-RasPi	2019-07-16 19:12:48.208	info	Restart adapter system.adapter.mqtt.0 because enabled
host.ioBroker-RasPi	2019-07-16 19:12:48.208	error	instance system.adapter.mqtt.0 terminated with code 0 (OK)
host.ioBroker-RasPi	2019-07-16 19:12:48.207	error	Caught by controller[0]: at Connection.emit (events.js:211:7)
host.ioBroker-RasPi	2019-07-16 19:12:48.207	error	Caught by controller[0]: at emitOne (events.js:116:13)
host.ioBroker-RasPi	2019-07-16 19:12:48.207	error	Caught by controller[0]: at Object.onceWrapper (events.js:315:30)
host.ioBroker-RasPi	2019-07-16 19:12:48.207	error	Caught by controller[0]: at Connection.<anonymous> (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt-connection/connection.js:53:12)
host.ioBroker-RasPi	2019-07-16 19:12:48.206	error	Caught by controller[0]: at Connection.emit (events.js:211:7)
host.ioBroker-RasPi	2019-07-16 19:12:48.206	error	Caught by controller[0]: at emitOne (events.js:116:13)
host.ioBroker-RasPi	2019-07-16 19:12:48.206	error	Caught by controller[0]: at Connection.emitPacket (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt-connection/connection.js:10:8)
host.ioBroker-RasPi	2019-07-16 19:12:48.206	error	Caught by controller[0]: at Connection.emit (events.js:211:7)
host.ioBroker-RasPi	2019-07-16 19:12:48.205	error	Caught by controller[0]: at emitOne (events.js:116:13)
host.ioBroker-RasPi	2019-07-16 19:12:48.204	error	Caught by controller[0]: at Connection.client.on.options (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:750:30)
host.ioBroker-RasPi	2019-07-16 19:12:48.199	error	Caught by controller[0]: TypeError: stream.setTimeout is not a function
mqtt.0	2019-07-16 19:12:47.641	error	TypeError: stream.setTimeout is not a function at Connection.client.on.options (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:750:30) at emitOne (events.js:116:13) at Connection.e
mqtt.0	2019-07-16 19:12:47.640	error	uncaught exception: stream.setTimeout is not a function
mqtt.0	2019-07-16 19:12:47.639	info	Client [MQTTTEST] connected with secret 1563297167353_5931
mqtt.0	2019-07-16 19:12:20.580	info	Starting MQTT -WebSocket' server on port 1884
mqtt.0	2019-07-16 19:12:20.578	info	Starting MQTT ' server on port 1883
mqtt.0	2019-07-16 19:12:19.496	info	starting. Version 2.1.0 in /opt/iobroker/node_modules/iobroker.mqtt, node: v8.16.0
host.ioBroker-RasPi	2019-07-16 19:12:18.236	info	instance system.adapter.mqtt.0 started with pid 1758

Fehlermeldung des Browsers:

`onConnectionLost:AMQJS0008I Socket closed.` 

Per pubsubclient auf einem ESP8266 läuft alles probelmlos.

Mit den MQTT-Adaptern Version 1.5 - 2.04 funktioniert ebenfalls alles reibungslos.

Nur mit Version 2.1.0 scheint es bei paho.js/mqttws311.js  und Websockets zum Absturz des Adapters zu kommen.

TEST: In das fiddle-Beispiel (http://jsfiddle.net/gLBsu/3/) oben lokale MQTT-Broker IP eingeben und auf Run und dann den Button "1. CONNECT" drücken. iobroker mit 2.1.0 MQTT Broker meldet im Log obigen Fehler und verwährt Verbindung.

Mehr Infos und Verifikation hier: https://forum.iobroker.net/topic/23791/mqtt-1-5-funktioniert-bei-mir-nicht-mehr

Wäre für Hilfe dankbar.

Hoffe, ich habe keine wichtigen Infos ausgelassen.

**Comment by sgc-fireball** [comment]
Same with https://www.npmjs.com/package/mqtt (build with webpack).

host.raspberrypi | 2020-06-12 21:35:47.839 | info | instance system.adapter.mqtt.0 terminated with code 0 (NO_ERROR)
-- | -- | -- | --
host.raspberrypi | 2020-06-12 21:35:47.839 | error | Caught by controller[0]: at Connection.Readable.push (/opt/iobroker/node_modules/readable-stream/lib/_stream_readable.js:245:10)
host.raspberrypi | 2020-06-12 21:35:47.838 | error | Caught by controller[0]: at readableAddChunk (/opt/iobroker/node_modules/readable-stream/lib/_stream_readable.js:278:11)
host.raspberrypi | 2020-06-12 21:35:47.838 | error | Caught by controller[0]: at addChunk (/opt/iobroker/node_modules/readable-stream/lib/_stream_readable.js:291:12)
host.raspberrypi | 2020-06-12 21:35:47.838 | error | Caught by controller[0]: at Connection.emit (events.js:198:13)
host.raspberrypi | 2020-06-12 21:35:47.837 | error | Caught by controller[0]: at Object.onceWrapper (events.js:286:20)
host.raspberrypi | 2020-06-12 21:35:47.837 | error | Caught by controller[0]: at Connection.<anonymous> (/opt/iobroker/node_modules/mqtt-connection/connection.js:53:12)
host.raspberrypi | 2020-06-12 21:35:47.837 | error | Caught by controller[0]: at Connection.emit (events.js:198:13)
host.raspberrypi | 2020-06-12 21:35:47.837 | error | Caught by controller[0]: at Connection.emitPacket (/opt/iobroker/node_modules/mqtt-connection/connection.js:10:8)
host.raspberrypi | 2020-06-12 21:35:47.836 | error | Caught by controller[0]: at Connection.emit (events.js:198:13)
host.raspberrypi | 2020-06-12 21:35:47.836 | error | Caught by controller[0]: at Connection.client.on.options (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:759:28)
host.raspberrypi | 2020-06-12 21:35:47.835 | error | Caught by controller[0]: TypeError: stream.setTimeout is not a function
mqtt.0 | 2020-06-12 21:35:47.287 | info | (26065) Terminated (NO_ERROR): Without reason
mqtt.0 | 2020-06-12 21:35:47.286 | info | (26065) terminating
mqtt.0 | 2020-06-12 21:35:46.780 | error | (26065) TypeError: stream.setTimeout is not a function at Connection.client.on.options (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:759:28) at Connection.emit (events.js:198:13)
mqtt.0 | 2020-06-12 21:35:46.780 | error | (26065) uncaught exception: stream.setTimeout is not a function
mqtt.0 | 2020-06-12 21:35:46.619 | info | (26065) Client [63ad31c6-758d-4190-9ac9-f7eefcbd76bf] connected with secret 1591990545618_3076
mqtt.0 | 2020-06-12 21:35:38.439 | info | (26065) Starting MQTT-WebSocket authenticated server on 192.168.2.83:1884
