### ISSUE TITLE
MQTT binary data, how to get this

### ISSUE THREAD

**Issue by helmut64** [ioBroker/ioBroker.mqtt#64]
I am new to IOBrocker and have a question how to access the binary data of the MQTT message within a javascript. My understanding is that obj.state.val is a string but my incoming message is a binary block of 4 bytes.

Any ideas?
Thank you.

**Comment by helmut64** [comment]
I believe this is still a valid point MQTT does not require ASCII nor JASON only format, binary data should work as well.

**Comment by thomas725** [comment]
I'm very much interested in this feature as well. There should be some way to configure MQTT topics to interpret the payload as something else than a string and allow access to that. (like numbers or binary data instead of interpreting everything as a string)

**Comment by helmut64** [comment]
For our use case we forward LoRa messages to MQTT. Our LoRa messages are binary to save transmission time which means x times less energy for our radio node. IOB should really allow a blob of binary data within MQTT.

**Comment by helmut64** [comment]
It is still an issue, binary data within MQTT is normal and IOB accept this problem and enhance it to support binary data.

**Comment by helmut64** [comment]
The Problem still exists, it is necessary to fix this.

**Comment by Apollon77** [comment]
I would merge this with #115 . Please support by showing an enhanced log hoe that binary data is received ... see https://github.com/ioBroker/ioBroker.mqtt/issues/115#issuecomment-832033438
