### ISSUE TITLE
Adapter tries to send topic conntaining '#' with Alexa2 enabled

### ISSUE THREAD

**Issue by KoffeinKaio** [ioBroker/ioBroker.mqtt#65]
Hey,

I recently had to debug my mqtt client because it spammed the Broker and keept crashing.

As soon as I enable sending data of the Alexa adapter to mqtt it crashed and restarts in a loop.

Output from vernemq:
```
vernemq     | 09:07:30.204 [warning] stopped connected session, due to unexpected frame type {error,'no_#_allowed_in_word'}
vernemq     | 09:07:30.204 [warning] session stopped abnormally due to '{error,unexpected_message,{error,'no_#_allowed_in_word'}}'
```
Alexa got some objects named "#trigger" and so on.

A fix would prop. be just to filter those out. That again would probably destroy the ability to control stuff.

**Comment by Apollon77** [comment]
is "#" officially forbidden in MQTT standard or is vernemq not allowing it?

**Comment by KoffeinKaio** [comment]
'#' is a wildcard for subscribing to all topics mqtt-broker-wide, so I strongly think its forbidden to use inside a topic as name.

It will also cause a disconnect on eclipse-mosquitto and the iobroker-mqtt-broker adapter.

**Comment by Apollon77** [comment]
seems the same rul applies for "+" (but this could be a forbidden character already in iobroker for object ids.
