### ISSUE TITLE
MQTT client Passwort Issue

### ISSUE THREAD

**Issue by murf3ry** [ioBroker/ioBroker.mqtt#67]
I have found a Bug that I can not solve myself. If I use the MQTT client with a "#" in my password, the connection will not work. This does not happen with the MQTT server" Only with the MQTT client!

Error Log:

2019-10-10 13:51:21.446 | error | instance system.adapter.mqtt.2 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2019-10-10 13:51:21.446 | error | by controller[0]: at addChunk (_stream_readable.js:288:12) code: 5 }
Caught | 2019-10-10 13:51:21.446 | error | by controller[0]: at Socket.emit (events.js:198:13)
Caught | 2019-10-10 13:51:21.446 | error | by controller[0]: at Socket.ondata (_stream_readable.js:709:20)
Caught | 2019-10-10 13:51:21.446 | error | by controller[0]: at Writable.write (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
Caught | 2019-10-10 13:51:21.446 | error | by controller[0]: at writeOrBuffer (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
Caught | 2019-10-10 13:51:21.446 | error | by controller[0]: at doWrite (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
Caught | 2019-10-10 13:51:21.446 | error | by controller[0]: at Writable.writable._write (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:302:5)
Caught | 2019-10-10 13:51:21.446 | error | by controller[0]: at work (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:292:12)
Caught | 2019-10-10 13:51:21.446 | error | by controller[0]: at MqttClient._handlePacket (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:350:12)
Caught | 2019-10-10 13:51:21.446 | error | by controller[0]: at MqttClient._handleConnack (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:920:15)
Caught | 2019-10-10 13:51:21.446 | error | by controller[0]: { Error: Connection refused: Not authorized

**Comment by Apollon77** [comment]
basically "#" is a reserved character by MTT protocol ... no idea if this is the reason ...?

**Comment by murf3ry** [comment]
I thought so too. Then I tried it with a mosquitto client and it worked with "#" in my password. In my opinion, the iobroker MQTT Client has a bug.

**Comment by wisky3** [comment]
basically "#" is not reserved, # is. Mosquitto is can handle passw with "#"
