### ISSUE TITLE
Can't send command to channel xiaomi socket

### ISSUE THREAD

**Issue by bogdaan2001** [ioBroker/ioBroker.mqtt#70]
Hello I connected the xiaomi outlet through mqtt-client, but I can not control it through the script. Please tell me how to do it.
I try to execute code hrough a JavaScript script
`sendTo("mqtt.0", "sendMessage2Client", {topic: "zigbee2mqtt/0x00158d0003934947", message:" OFF"});`
and it does not work or I try to do the same thing through blockly, which also does not work

`sendTo("mqtt.0", "sendMessage2Client", {topic: "zigbee2mqtt/0x00158d0003934947", message: "OFF"});`

<img width="529" alt="Снимок экрана 2019-12-18 в 00 44 04" src="https://user-images.githubusercontent.com/50640169/71036887-98441680-212f-11ea-9846-67f26776de1f.png">
<img width="1022" alt="Снимок экрана 2019-12-18 в 00 44 25" src="https://user-images.githubusercontent.com/50640169/71036894-a134e800-212f-11ea-907c-fd45de2aff77.png">

when i send command ( ON or OFF ) via "mqtt explorer" the socket change status correctly....
how can I achieve the same result from mqtt-client ???

<img width="1012" alt="Снимок экрана 2019-12-18 в 00 52 06" src="https://user-images.githubusercontent.com/50640169/71037453-b9f1cd80-2130-11ea-9473-e3f972254577.png">

**Comment by bogdaan2001** [comment]
can anyone help with the MQTT broker settings to send messages to the channel ???

<img width="1201" alt="Снимок экрана 2019-12-19 в 10 54 48" src="https://user-images.githubusercontent.com/50640169/71155179-46de7900-224e-11ea-9f97-36f89039da6a.png">
<img width="1199" alt="Снимок экрана 2019-12-19 в 10 55 06" src="https://user-images.githubusercontent.com/50640169/71155180-480fa600-224e-11ea-9fc5-0ca934017d62.png">
<img width="1199" alt="Снимок экрана 2019-12-19 в 10 55 18" src="https://user-images.githubusercontent.com/50640169/71155187-4940d300-224e-11ea-82a3-603a77c838df.png">
<img width="1200" alt="Снимок экрана 2019-12-19 в 10 56 07" src="https://user-images.githubusercontent.com/50640169/71155193-4c3bc380-224e-11ea-9d9d-0da84fcd5874.png">

**Comment by bogdaan2001** [comment]
???????????

**Comment by robotastic-io** [comment]
It seems you are using a different topic _zigbee2mqtt/0x00158d0003934947_ instead of _zigbee2mqtt/0x00158d0003934947/set_ when looking at your script and mqtt-explorer?
