### ISSUE TITLE
Last-Will funktioniert nicht

### ISSUE THREAD

**Issue by Harry-58** [ioBroker/ioBroker.mqtt#74]
Ich habe den Adapter "MQTT Broker/Client" in der aktuellen Version (2.0.4) installiert (auf einem RasPi4). 
Als Typ ist "Server/broker" eingestellt.
Es funktioniert auch alles, ich kann senden und empfangen.
Was aber nicht funktioniert ist "Last-Will".
Alle meine Clients setzten ein "Last-Will".
Wenn jetzt ein Client ausfällt, müsste der Server diesen Last-Will publishen, was er aber nicht tut.
Wenn ich die Clients mit einem anderen Server "Mosquitto", den ich auf einem anderen Raspi installiert habe, verbinde, werden die "Last-Will" wie erwartet beim Ausfall eines Clients gesendet.
Die Clients sind also richtig parametriert und es kann nur am MQTT-Adapter liegen.

**Comment by capitaenz** [comment]
@GermanBluefox @Harry-58 
Ist dieser Fehler mit der Version 2.1.3 behoben, oder ist noch immer der Patch notwendig?
[https://forum.iobroker.net/topic/14657/mqtt-adapter-macht-probleme/36](https://forum.iobroker.net/topic/14657/mqtt-adapter-macht-probleme/36)

**Comment by Harry-58** [comment]
Kann ich leider nicht mehr beantworten. Ich benutze nur noch die Clientversion.
Als Broker/Server benutzte ich nur noch Mosquitto.
