### ISSUE TITLE
Fehler "Allocation failed - JavaScript heap out of memory" seit einem der letzten Systemupdates

### ISSUE THREAD

**Issue by Pittini** [ioBroker/ioBroker.mqtt#78]
Seit einiger Zeit tritt nachfolgender Fehler auf. Dieser tritt erst auf (aber nicht immer und sofort) seit ich etliche Systemadapter inkl. js upgedatet habe. Mir sagt die Meldung nix, aber dass muss es ja auch nicht ;)

`

host.Iobroker | 2020-02-23 11:44:45.608 | info | instance system.adapter.mqtt.0 started with pid 9767
-- | -- | -- | --
host.Iobroker | 2020-02-23 11:44:15.583 | info | Restart adapter system.adapter.mqtt.0 because enabled
host.Iobroker | 2020-02-23 11:44:15.583 | info | instance system.adapter.mqtt.0 terminated with code NaN ()
host.Iobroker | 2020-02-23 11:44:15.582 | warn | instance system.adapter.mqtt.0 terminated due to SIGABRT
host.Iobroker | 2020-02-23 11:44:15.582 | error | Caught by controller[10]: 12: 0x29e8802078a1
host.Iobroker | 2020-02-23 11:44:15.582 | error | Caught by controller[10]: 11: 0x913649 [io.mqtt.0]
host.Iobroker | 2020-02-23 11:44:15.582 | error | Caught by controller[9]: 10: 0xb0b710 v8::String::Utf8Length() const [io.mqtt.0]
host.Iobroker | 2020-02-23 11:44:15.582 | error | Caught by controller[8]: 9: 0xafdd44 v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [io.mqtt.0]
host.Iobroker | 2020-02-23 11:44:15.582 | error | Caught by controller[7]: 8: 0x101d733 v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [io.mqtt.0]
host.Iobroker | 2020-02-23 11:44:15.582 | error | Caught by controller[6]: 7: 0xed3eab v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [io.mqtt.0]
host.Iobroker | 2020-02-23 11:44:15.582 | error | Caught by controller[5]: 6: 0xf042ff v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [io.mqtt.0]
host.Iobroker | 2020-02-23 11:44:15.582 | error | Caught by controller[4]: 5: 0xef4ae2 [io.mqtt.0]
host.Iobroker | 2020-02-23 11:44:15.582 | error | Caught by controller[3]: 4: 0xb005d4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [io.mqtt.0]
host.Iobroker | 2020-02-23 11:44:15.582 | error | Caught by controller[2]: 3: 0xb0039e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [io.mqtt.0]
host.Iobroker | 2020-02-23 11:44:15.582 | error | Caught by controller[1]: 2: 0x8fa0dc [io.mqtt.0]
host.Iobroker | 2020-02-23 11:44:15.582 | error | Caught by controller[1]: 1: 0x8fa090 node::Abort() [io.mqtt.0]
host.Iobroker | 2020-02-23 11:44:15.582 | error | Caught by controller[0]: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

`

**Comment by Apollon77** [comment]
Die Meldung heisst faktisch "Out of memory". Entweder der Prozess hat mehr als den erlaubten RAM benötigt oder der RAM istgenerell knapp bei dir ... Da wäre jetzt mehr Infos zum System und anzahl Adaptern und so nötig.

**Comment by Pittini** [comment]
Fehler ist gestern nochmal aufgetreten. Heute habe ich ausstehende updates gemacht (socket.io, Admin, Script Engine und Webserver) bisher blieb alles ruhig, werde das mal weiter beobachten aber denke fast dasses weg ist.
System läuft in VM unter Proxmox auf nem Nuc. Sollte kein Engpass sein denk ich. Hier die Systemdaten:
Betriebssystem linux
os linux 
Architektur x64
CPUs 4
Geschwindigkeit 2399 MHz
Modell Common KVM processor
RAM 7.61 GB
System Betriebszeit 03:58:51
Node.js v10.18.1 (Es gibt eine neuere Version: v10.19.0)
NPM 6.13.4
Festplatte Größe 7.01 GB
Festplatte frei 3.38 GB
Anzahl der Adapter 325
Betriebszeit 03:58:14
Aktive Instanzen 26
Hostname Iobroker

**Comment by Pittini** [comment]
@Apollon77 Zu früh gefreut, heute kam die Meldung wieder. Hier der relevante Teil vom Log

`

mqtt.0 | 2020-02-26 11:11:30.432 | info | (17570) Client [Mainframe] subscribes on "iotlink/workgroup/mainframe/#" with regex /^mqtt\.0\.iotlink\.workgroup\.mainframe\..*/
-- | -- | -- | --
mqtt.0 | 2020-02-26 11:11:30.432 | info | (17570) Client [Mainframe] subscribes on "iotlink/workgroup/mainframe/#" with regex /^iotlink\.workgroup\.mainframe\..*/
mqtt.0 | 2020-02-26 11:11:29.425 | info | (17570) Client [Mainframe] connected with secret 1582711889424_5982
mqtt.0 | 2020-02-26 11:11:27.604 | info | (17570) Client [ESP8266Client-bf64] subscribes on topic "Gaswaage/Isleckalarm"
mqtt.0 | 2020-02-26 11:11:27.562 | info | (17570) Client [ESP8266Client-bf64] subscribes on topic "Gaswaage/onoff"
mqtt.0 | 2020-02-26 11:11:27.562 | info | (17570) Client [ESP8266Client-bf64] subscribes on topic "Gaswaage/Gewicht"
mqtt.0 | 2020-02-26 11:11:27.562 | info | (17570) Client [ESP8266Client-bf64] subscribes on topic "Gaswaage/Lecksensorwert"
mqtt.0 | 2020-02-26 11:11:27.498 | info | (17570) Client [ESP8266Client-bf64] subscribes on topic "Gaswaage/Restgasprozent"
mqtt.0 | 2020-02-26 11:11:27.461 | info | (17570) Client [ESP8266Client-bf64] connected with secret 1582711887457_6058
mqtt.0 | 2020-02-26 11:11:25.313 | info | (17570) Starting MQTT ' authenticated server on port 1885
mqtt.0 | 2020-02-26 11:11:23.627 | info | (17570) starting. Version 2.1.1 in /opt/iobroker/node_modules/iobroker.mqtt, node: v10.18.1
host.Iobroker | 2020-02-26 11:11:22.425 | info | instance system.adapter.mqtt.0 started with pid 17570
host.Iobroker | 2020-02-26 11:10:52.410 | info | Restart adapter system.adapter.mqtt.0 because enabled
host.Iobroker | 2020-02-26 11:10:52.410 | info | instance system.adapter.mqtt.0 terminated with code NaN ()
host.Iobroker | 2020-02-26 11:10:52.410 | warn | instance system.adapter.mqtt.0 terminated due to SIGABRT
host.Iobroker | 2020-02-26 11:10:52.410 | error | Caught by controller[9]: 18: 0x213207c5bf7d
host.Iobroker | 2020-02-26 11:10:52.410 | error | Caught by controller[9]: 17: 0xbd4ec1 v8::internal::Builtin_JsonStringify(int, v8::internal::Object**, v8::internal::Isolate*) [io.mqtt.0]
host.Iobroker | 2020-02-26 11:10:52.410 | error | Caught by controller[8]: 16: 0xfce599 v8::internal::JsonStringifier::Stringify(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::interna
host.Iobroker | 2020-02-26 11:10:52.410 | error | Caught by controller[8]: 15: 0xfcd83d v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8:
host.Iobroker | 2020-02-26 11:10:52.410 | error | Caught by controller[8]: 14: 0xfc872b v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::
host.Iobroker | 2020-02-26 11:10:52.410 | error | Caught by controller[8]: 13: 0xfc7f11 v8::internal::JsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [io.mqtt.0]
host.Iobroker | 2020-02-26 11:10:52.410 | error | Caught by controller[8]: 12: 0xfc82de v8::internal::JsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [io.mqtt.0]
host.Iobroker | 2020-02-26 11:10:52.410 | error | Caught by controller[7]: 11: 0x12040f0 v8::internal::IncrementalStringBuilder::Extend() [io.mqtt.0]
host.Iobroker | 2020-02-26 11:10:52.410 | error | Caught by controller[6]: 10: 0xed3eab v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [io.mqtt.0]
host.Iobroker | 2020-02-26 11:10:52.409 | error | Caught by controller[5]: 9: 0xf04261 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [io.mqtt.0]
host.Iobroker | 2020-02-26 11:10:52.409 | error | Caught by controller[4]: 8: 0xf015f4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [io.mqtt.0]
host.Iobroker | 2020-02-26 11:10:52.409 | error | Caught by controller[3]: 7: 0xf00cc2 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [io.mqtt.0]
host.Iobroker | 2020-02-26 11:10:52.409 | error | Caught by controller[2]: 6: 0xef4be8 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [io.mqtt.0]
host.Iobroker | 2020-02-26 11:10:52.409 | error | Caught by controller[1]: 5: 0xef4ae2 [io.mqtt.0]
host.Iobroker | 2020-02-26 11:10:52.409 | error | Caught by controller[0]: 4: 0xb005d4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [io.mqtt.0]
host.Iobroker | 2020-02-26 11:10:52.409 | error | Caught by controller[0]: 3: 0xb0039e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [io.mqtt.0]
host.Iobroker | 2020-02-26 11:10:52.409 | error | Caught by controller[0]: 2: 0x8fa0dc [io.mqtt.0]
host.Iobroker | 2020-02-26 11:10:52.408 | error | Caught by controller[0]: 1: 0x8fa090 node::Abort() [io.mqtt.0]
host.Iobroker | 2020-02-26 11:10:52.408 | error | Caught by controller[0]: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

`

**Comment by Pittini** [comment]
Ich konnte das Problem inzwischen etwas eingrenzen. Es scheint mit [iotlink](https://gitlab.com/iotlink/iotlink/-/wikis/Configuration) und Qos zusammenzuhängen. iotlink hat standarteinstellung Qos=1. Damit werden die Fehler "provoziert". Stell ich Qos=0 is Ruhe. Wie da die genauen Zusammenhänge sind erschliesst sich mir jedoch nicht, spielen die Pingpong bis der Speicher ausgeht?
