### ISSUE TITLE
MQTT Adapter crashes when client tries to connect

### ISSUE THREAD

**Issue by bjoernbusch** [ioBroker/ioBroker.mqtt#82]
I have tried the adapter in version 2.0.4 and 2.1.1 and both crash when a websocket client tries to connect:

<img width="1062" alt="Screenshot 2020-03-29 at 13 52 13" src="https://user-images.githubusercontent.com/15795611/77848378-8b21d380-71c4-11ea-8a56-20f1ff87ce0e.png">

Regular Mqtt client connection is ok. Is there any cache or something that I need to clean or something that I need to initialize or what's going wrong? Any ideas are appreciated, I can deliver additional information if needed.

Thanks!

**Comment by Apollon77** [comment]
duplicate zu #22?

**Comment by bjoernbusch** [comment]
Ja, ist ein duplicate und ich habe den Code jetzt soweit geflickt, dass ich an 3 Stellen beim Aufruf des client die _messages auf null prüfe und dann funktioniert es wieder. Nachdem es das Problem seit ca. 2 Jahren schon gibt, fände ich es toll, wenn jemand der den Code wirklich versteht, dass beurteilen / fixen könnte.
