### ISSUE TITLE
[gelöst] kein Weiterleiten bei manchen Objekten

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.mqtt#85]
mqtt broker/client 2.1.1

Ein Rasenroboter mit mqtt erzeugt im ioBroker entsprechende topics und schreibt darin Daten.
Diese Daten können z.B. im VIS weiterverwendet werden.
Diese Daten werden aber nicht an einen ESP8266 (Arduino,PubSubClient) weitergegeben, alle anderen topics schon.

Erst wenn ich mit dem Windows Tool MQTTBox einen Wert in diesem topic "publishe", dann erscheint der auch sofort im ESP8266.

Was kann denn da die Ursache sein, dass manche Einträge nicht weiterverteilt werden?

Hoffentlich weiß da jemand eine Abhilfe, damit ich mir das lästige  Pollen sparen kann.

Vielen Dank

**Comment by GermanBluefox** [comment]
Ich kann vermuten, dass die Verbindung mit ESP8266 nicht so stabil ist (was auch berichtet wurde).
Da konnte helfen, dass ESP mit QoS 1 subscribed oder iobroker immer alle Werte mit QoS1 sendet

**Comment by Hans-Zwiesel** [comment]
Hallo GermanBluefox,
vielen Dank für die Hilfe.

Ich habe inzwischen den Fehler herausgefunden:
Es war der Name des topic im Rasenroboter.
Ich hatte es mit „mqtt.0.haus.outdoor.usw“ angegeben, ioBroker hat daraufhin mit diesem seltsamen Verhalten reagiert.
Richtig ist topic „haus/outdoor/usw“ dann macht ioBroker was er soll.
Eine richtige Falle.
