### ISSUE TITLE
automatisch erzeugte objekte können nicht gelöscht werden

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.mqtt#87]
mqtt Vers. 2.1.1
Irgend ein Client erzeugt das Objekt:   mqtt.0.hau10
Wenn ich versuche, dieses Objekt zu löschen, erhalte ich den Fehler:

"Das Objekt "mqtt.0.hau10�-haus" existiert nicht. Seite aktualisieren."

Wie kann ich diese Objekte löschen?
`$('hau10*.*').each(function (id) {
  log("ID: "+id)
  deleteState(id);
});`
funktioniert auch nicht.

**Comment by capitaenz** [comment]
@Hans-Zwiesel 
Leider kein Einzelfall:
[https://forum.iobroker.net/topic/16193/kann-im-mqtt-objekte-nicht-löschen/15](https://forum.iobroker.net/topic/16193/kann-im-mqtt-objekte-nicht-löschen/15)

**Comment by Apollon77** [comment]
BTW: Welcher js-controller ist im Einsatz?

**Comment by Hans-Zwiesel** [comment]
4.6.17
VG
Hans Stöckl

**Comment by capitaenz** [comment]
Zwar schon im Forum geschrieben, aber wegen der Übersicht:

Version 3.1.6

Wobei die Fehlerhaften Einträge schon mit einer der Versionen vorher entstanden sind.

**Comment by Apollon77** [comment]
Also wer es nachstellen kann ... nehmt mal die GitHub version ... (Versionsnummer ist die gleiche). Passiert es da noch? Geht sonst noch alles? "Ungültige IDs" werden jetzt geloggt

**Comment by GreaseMonkey88** [comment]
Unfortunately the problem still exist in version 2.3.5.

**Comment by Apollon77** [comment]
means that even with a 2.3.5 you got such objects created? Or were they created with an older version?

**Comment by GreaseMonkey88** [comment]
I´m pretty sure these objects were created with an older version. Ok, bad previous comment from my side...

But how can I delete these objects?

**Comment by Apollon77** [comment]
When I remember correctly this was discussed in the above linked Forum thread ... you need tomanually edit the objects.json file (sorry)

**Comment by aschenk** [comment]
I discovered two issues with your adapter (version 2.3.5), where the conversion from MQTT topic into iobroker id is not working correctly:

1. "ws300/Küche/temperature"

It seems the German umlaut is not allowed. Could you maybe convert it to "ue"?

2. "fronius/0/powerflow/P_Grid"

Here the "0" seems to be problematic. Do you have an idea how to handle this?

Best regards,
André
