### ISSUE TITLE
Gesetztes Passwort auslesen?

### ISSUE THREAD

**Issue by Parodontitis** [ioBroker/ioBroker.mqtt#89]
Moin, seit mehr als zwei Jahren läuft bei mir ein ESP, der mit dem IoBroker über mqtt kommuniziert. Jetzt weiß ich das Passwort nicht mehr! 😵 Ich möchte das Passwort nicht unbedingt neu setzen, weil ich dann den ESP neu konfigurieren müsste. Gibt es eine Möglichkeit das gesetzte Passwort irgendwie auszulesen?

Danke.

**Comment by Apollon77** [comment]
Naja in der Konfiguration des Adapters ist es generell ausgefüllt. Schau mal in den developer tools ob du ggf das Passwort Feld sichtbar machen kannst.

**Comment by Parodontitis** [comment]
> Naja in der Konfiguration des Adapters ist es generell ausgefüllt. Schau mal in den developer tools ob du ggf das Passwort Feld sichtbar machen kannst.

Das war die Lösung. Danke!

**Comment by Apollon77** [comment]
Bitte gern

**Comment by luell76** [comment]
Moin! Kann mir jemand sagen wie ich in den Developer Tools schauen kann? Ich habe ein identisches Problem mit dem nicht mehr bekannten Passwort.

Vielen Dank!

**Comment by stefanhoelscher** [comment]
Hallo Apollon99, ich habe das gleiche Problem wie mein Vorredner. Ich habe das Password in meiner Safari Passwortdatei überschrieben und komme nicht mehr in meinen iobroker rein. wenn ich hier was über developer Tools lese verstehe ich nur noch Bahnhof. Ich kann mir vorstellen das es für euch Profis sicherlich sehr müssig ist sich mit mir zu befassen, mit mir, einem der noch ganz am Anfang steht und noch kaum was weiß. Der braucht eine Schritt für Schritt Anleitung für "Doofe". 
Ich würde mich sehr freuen, wenn ihr Zeit finden würdet, es mal einfach für Anfänger zu erklären.
Vielen Dank im voraus für die Mühen

**Comment by Apollon77** [comment]
Dann schlagfe ich vor ich dazu am besten mal im Forum zu melden, da gibt es mehr die hier helfen können
