### ISSUE TITLE
Messages deleted after xx retries

### ISSUE THREAD

**Issue by valbuz** [ioBroker/ioBroker.mqtt#90]
Ich habe auf beiden meinen System mit ioBroker und MQTT immer wieder folgedne LOG-Einträge von Div. Client's:

(6526) Client [ZW_Boiler_Switch_70_70] Message 2393 deleted after 11 retries

Diese Fehler sind mir bis anhin nicht aufgefallen.

**Comment by RalfEngelberth** [comment]
Hallo, ich habe diese Fehlermeldung seit 2 Tagen.
(21717) Client [DVES_4FDF11] Message undefined deleted after 51658 retries
Das DVES_4FDF11 ist ein Sonoff-Gerät welches ich vor 2 Tagen gelöscht habe.

**Comment by RalfEngelberth** [comment]
Hat es eigentlich einen Sinn, hier was rein zu schreiben.
Es tut sich hier nix.
Auch im IoBroker-Forum wird darüber diskutiert.
Leider nur mit dem Ergebnis, diesen Adapter nicht zu verwenden.
Das ist schade.
Ich habe z.Z. ca. 30 Sonoff-Geräte über den mqtt im IoBroker eingebunden.
Wenn ich diese alle jetzt ändern muss, ist das echt viel Arbeit.

Was mache ich jetzt?
Warten?

**Comment by valbuz** [comment]
Bei mir hat sich das Problem durch verbesserte WLAN Abdeckung erledigt(bis jetzt).
Aber ja, auch ohne Antwort hier.....

**Comment by Apollon77** [comment]
Ja es macht Sinn hier zu schreiben und ich frag jetzt mal ehrlich ... Der Issue ist 8, IN WORTEN ACHT, Tage alt ... Was ist Eure Erwartung? Überlegt mal bitte gaaaaaaanz genau was Ihr hier schreibt.

Der Adapter hat über 9000 Installationen und der Fehler wurde bisher 2x hier und ein mal im Forum reportet ... Frage hier war wieviel denn so rausgesendet wird und so.

Und überlegt mal bitte was ein Entwickler mit den Infos die hier stehen anfangen soll. Könntet Ihr mit den Infos irgendetwas anstellen?

**Comment by ldittmar81** [comment]
Leute... Beim Github funktioniert das so: man stellt ein Fehler fest und beschreibt diesen so genau wie nur möglich, damit ein Entwickler es reproduzieren kann. Dazu zählen benutzte Version, Mode Version, Betriebssystem, js-controller usw... alles mögliche halt.

Wenn dann der Entwickler eine Frage hat, wird er diese hier stellen. Sollte alles klar sein, wird der Fehler gefixt und das Issue geschlossen... Ohne große Kommentare... Einfach zu gemacht.

Wie lange dauert so ein fix: ich denke 99,99% der ioBroker Entwickler haben ein Leben außerhalb der virtuelle Welt. Familie, Kinder, Jobs, private Probleme usw... Wir sind halt Menschen und machen das alles ohne ein Cent zu verdienen. Wir arbeiten also für die ganze Community, weil uns das am Herzen liegt. Also... Viele werden abends oder nur am Wochenende Zeit haben. Einige haben auch gleich mehrere Adapter und müssen sich manchmal teilen und es ist nunmal so, dass ein Fehler nicht von heute auf morgen gefixt werden kann.

Es ist aber wichtig, dass Fehler gemeldet werden, denn nur wenn ein Fehler bekannt ist und dokumentiert wurde, kann es gefixt werden. Nichts desto trotz ist Github kein Diskussionsforum, also... Laß dem Entwickler einfach Zeit, beschreibt den Fehler sehr genau und wenn Diskussionen notwendig sind, dann diese im Forum, Facebook, Telegram usw... führen.

**Comment by valbuz** [comment]
Hallo

Ich habe mich vermutlich etwas durch das Forum blenden lassen. Dort wird immer wieder von fehlenden Updates und eben keine Rückmeldungen diskutiert. Mein Post sollte nicht so rüberkommen!
Bei der heutigen schnell-lebigen Zeit wird halt eben immer gleich eine Rückmeldung erwartet :-(
Sorry und trotzdem gute Zeit Allen.
pat

**Comment by GermanBluefox** [comment]
Das ist kein Telegramm-Kanal. Ich möchte noch Mal erwähnen, wie Open Source funktioniert: die Benutzung ist auf eigener Gefahr und am besten man löst die Probleme mit einem pull requests, d.h selbst.

**Comment by GermanBluefox** [comment]
Und was ist bei der Meldung "ZW_Boiler_Switch_70_70] Message 2393 deleted after 11 retries" nicht klar??
Der Adapter hat versucht 11 Mal die Meldung an das Gerät ZW_Boiler_Switch_70_70 zu beliefern und das Gerät hat keine Bestätigung gesendet. Entweder ist Gerät Schrott/ Tot oder WLAN hat miserable Qualität. Das ist auf jeden Fall kein Fehler von Adapter, sondern der Hinweis auf den Fehler vom Anwender.

**Comment by Apollon77** [comment]
Bitte mit 2.1.4 retesten
