### ISSUE TITLE
manchmal keine Daten zum Client - mqtt Neustart notwendig

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.mqtt#91]
mqtt v2.1.3
Node.js v10.19.0

Es sind mehrere esp8266 Clients mit PubSubClient im System. Fehler tritt sporadisch bei jedem
Client auf. So ungefähr 1-2mal / Woche. So wie es jeder Entwickler gerne hat.

Ein Client sendet einen Wert zum Broker. Der Broker verteilt diesen Wert an die Clients, die
diesen Wert anfordern.
Das funktioniert auch tagelang. Aber ohne etwas verändert zu haben, kommen die Werte manchmal
nicht mehr auf den Empfangs-Clients an - sie werden nur im entsprechendem mqtt Objekt
aktualisiert.

Wenn ich den mqtt Adapter neu starte, dann funktioniert wieder alles.

P.S.
Ist echt nervig - weil mein Rasenmäher Roboter dann immer das Rolltor der Garage rammt -
ich musste es schon zweimal ausrichten.

**Comment by QuoxelNet** [comment]
Das Problem kenne ich auch... anfangs habe ich Werte innerhalb des ioBroker via MQTT synchronisiert. Aber irgendwann funktioniert das nicht mehr, manches wird aktualisiert, manches nicht. Ich fände es auch super, wenn das Problem behoben werden könnte...

**Comment by Hans-Zwiesel** [comment]
> 
> 
> Das Problem kenne ich auch... anfangs habe ich Werte innerhalb des ioBroker via MQTT synchronisiert. Aber irgendwann funktioniert das nicht mehr, manches wird aktualisiert, manches nicht. Ich fände es auch super, wenn das Problem behoben werden könnte...

**Comment by Hans-Zwiesel** [comment]
Ich habe jetzt eine Diagnose eingebaut:
Der Broker sendet alle 15min. eine unterschiedliche Zahl an jeden Client.
Die Clients negieren die Zahl und sendet sie wieder zurück.
Der Broker überprüft, ob die negierte Zahl innerhalb von 3sec. zurückkommt, die Clients prüfen,
ob alle 15min. eine neue Zahl empfangen wird.

Es ist noch zu früh, um eine sichere Diagnose zu stellen, aber bisher hat nur der Broker
einen Alarm bei unterschiedlichen Clients ausgelöst.
Ich habe inzwischen das unzuverlässige FritzBox Wlan im Verdacht.

**Comment by 9Mad-Max5** [comment]
Gab es nun einen finalen Grund?
