### ISSUE TITLE
Server/broker Problem bei messageId > 65535

### ISSUE THREAD

**Issue by NorbGH** [ioBroker/ioBroker.mqtt#93]
Versionen:
ioBroker.mqtt: 2.1.2/2.1.3 verwendet als Server/broker
node.js: v12.16.3
MQTT.js: v4.0.0

Ich habe den Effekt bereits hier kurz erläutert:
[https://forum.iobroker.net/topic/27158/mqtt-broker-bricht-nach-einer-weile-ab/3](https://forum.iobroker.net/topic/27158/mqtt-broker-bricht-nach-einer-weile-ab/3)

Problem:
Sobald der Server versucht eine Nachricht mit messageId über 65535 zu senden erscheint folgende Meldung:
`2020-06-18 15:21:00.894  - mqtt.0 (3704) Client [Clientname] connection closed: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received undefined`

Das gleiche passiert anschließend bei jedem Verbindungsversuch des Clients:
`2020-06-18 15:21:04.191  - mqtt.0 (3704) Client [Clientname] connected with secret 1592486461131_7906`
`2020-06-18 15:21:04.304  - mqtt.0 (3704) Client [Clientname] connection closed: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received undefined`

In diesem Zusammenhang tauchen im Anschluss auch Meldungen dieser Art auf:
`2020-06-18 15:22:25.670  - mqtt.0 (3704) Client [Clientname] Message 65634 deleted after 23 retries`

Ursache sind meiner Meinung nach folgende Zeilen in der server.js:
`messageId++;`
`messageId &= 0xFFFFFFFF;`
Die messadeId muss zwischen 1 und 65535 liegen, was durch die 32Bit-Maskierung nicht gewärleistet ist.

Auch die Probleme #31 und #74 könnten hierauf zurückzuführen sein.

MfG

**Comment by Apollon77** [comment]
Welche Zeilen in der server.js sind es denn genau? ;-) oder ists nur eine Zeile mit messageId++? ;-)

**Comment by NorbGH** [comment]
Ähm...
Ja, die besagten Zeilen findet man in der server.js je nur einmal und zwar bei Zeile 218 bzw. 219.

Die Zeile 219 habe ich bei mir ersetz durch:
`if (messageId > 65535) {messageId = 1;}`

Seitdem läuft alles problemlos, auch nach längerer Laufzeit.

**Comment by Apollon77** [comment]
Cooless FInding, schaue das ich zeitnah ein release mache!

**Comment by Apollon77** [comment]
Try 2.1.4 please
