### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by f-israel** [ioBroker/ioBroker.mqtt#95]
` Cannot read property (10613) TypeError: Cannot read property 'toString' of undefined
    at state2string (/opt/iobroker/node_modules/iobroker.mqtt/lib/common.js:30:77)
    at getMqttMessage (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:195:39)
    at /opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:170:17
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2870:21
    at /opt/iobroker/node_modules/iobroker.js-controller/node_modules/iobroker.objects-redis/index.js:1:93703
    at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
    at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)' of undefined`'

Taucht direkt beim Subscribe nach "publishOnSubscribe send all known states" auf. Nach gewisser Zeit (oder Fehlern?) wird der Adapter terminiert.
Ich vermute, dass es irgendein State bzw. Statename ist, den der Adapter nicht verträgt; konnte aber bisher noch nicht tracen, welcher es ist. Meldung taucht ca. 20-40 Mal instant auf.

Es wäre eventuell besser, wenn so ein Fehler einen Error bzw. eine Warning auswirft und die States einfach weglässt.

 - Adapter version: aktueller Master (2.1.4)
 - JS-Controller version: 3.1.4
 - Node version: 12.18.1
 - Operating system: debian
- Testclient: MQTT Explorer

Sobald ich den Übertäter finde, gebe ich die Info noch rein.

**Comment by FrankRenp** [comment]
Ich habe das gleiche Problem, nachdem ich den ioBroker umgezogen habe (mit BackitUp von Raspberry auf NUC VM) - dabei hat sich die IP-Adresse geändert. Nach Entfernung und Neuinstallation des MQTT Adapter gleiches Verhalten. 
(Die anderen Adapter laufen einwandrei.)

MQTT Adapter 2.1.2
JS-Controller: 3.1.4
Node: 10.21.0
Debian Buster

**Comment by fastback2000** [comment]
I have the same problem and go back to version 2.1.1 on production system.
All higher versions have this problem but in the moment I have no idea for the reason.

MQTT Adapter 2.1.2 an higher
JS-Controller: 4.6.14
Node: 10.20.1
NPM: 6.14.4

**Comment by Apollon77** [comment]
test 2.1.5 please

**Comment by fastback2000** [comment]
great - it works - many thx
