### ISSUE TITLE
TypeError: val.replace is not a function at MqttClient.stringToVal

### ISSUE THREAD

**Issue by QuoxelNet** [ioBroker/ioBroker.mqtt#96]
**Describe the bug**  
Beim Starten des Adapters tritt dieser Fehler auf und sorgt dafür, dass er gleich wieder beendet wird.

**To Reproduce**  
Kann derzeit noch nicht sagen, welche Einstellung das Problem verursacht.

**Expected behavior**  
Start des Adapters und problemloser Betrieb...

**Screenshots & Logfiles**  

mqtt-client.0 | 2020-07-02 12:02:30.221 | info | (13235) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
mqtt-client.0 | 2020-07-02 12:02:30.221 | info | (13235) terminating
mqtt-client.0 | 2020-07-02 12:02:29.940 | error | (13235) TypeError: val.replace is not a function     at MqttClient.stringToVal (/opt/iobroker/node_modules/iobroker.mqtt-client/main.js:306:14)     at getForeignState (/opt/iobroker/node_modules/iobro
mqtt-client.0 | 2020-07-02 12:02:29.939 | error | (13235) uncaught exception: val.replace is not a function
mqtt-client.0 | 2020-07-02 12:02:29.939 | error | (13235) TypeError: val.replace is not a function     at MqttClient.stringToVal (/opt/iobroker/node_modules/iobroker.mqtt-client/main.js:306:14)     at getForeignState (/opt/iobroker/node_modules/iobro
mqtt-client.0 | 2020-07-02 12:02:29.939 | error | (13235) uncaught exception: val.replace is not a function
mqtt-client.0 | 2020-07-02 12:02:29.939 | error | (13235) TypeError: val.replace is not a function     at MqttClient.stringToVal (/opt/iobroker/node_modules/iobroker.mqtt-client/main.js:306:14)     at getForeignState (/opt/iobroker/node_modules/iobro
mqtt-client.0 | 2020-07-02 12:02:29.939 | error | (13235) uncaught exception: val.replace is not a function
mqtt-client.0 | 2020-07-02 12:02:29.938 | error | (13235) TypeError: val.replace is not a function     at MqttClient.stringToVal (/opt/iobroker/node_modules/iobroker.mqtt-client/main.js:306:14)     at getForeignState (/opt/iobroker/node_modules/iobro
mqtt-client.0 | 2020-07-02 12:02:29.938 | error | (13235) uncaught exception: val.replace is not a function
mqtt-client.0 | 2020-07-02 12:02:29.937 | info | (13235) cleaned everything up...
mqtt-client.0 | 2020-07-02 12:02:29.937 | error | (13235) TypeError: val.replace is not a function     at MqttClient.stringToVal (/opt/iobroker/node_modules/iobroker.mqtt-client/main.js:306:14)     at getForeignState (/opt/iobroker/node_modules/iobro
mqtt-client.0 | 2020-07-02 12:02:29.937 | error | (13235) uncaught exception: val.replace is not a function
mqtt-client.0 | 2020-07-02 12:02:29.792 | info | (13235) connected to broker

**Versions:**  
 - Adapter version: 1.3.1
 - JS-Controller version: 3.1.6
 - Node version: v10.21.0
 - Operating system: Ubuntu Server 18.10

**Additional context**

**Comment by QuoxelNet** [comment]
Das Problem könnte behoben werden, indem in main.js, Zeile 308 folgender Code geschrieben wird:

if (val === Object) val = val.replace(',', '.');

Wenn der Wert in "val" eine primitive Zahl ist, kann die Methode "replace" nicht darauf ausgeführt werden...

**Comment by Apollon77** [comment]
Der Code wird so nicht tun aber ok :-) Frage ist ja warum er überhaupt in "stringToVal" landet ... und btw ... falscher Adapter!!
--> mqtt-client! https://github.com/Pmant/ioBroker.mqtt-client/issues bitte dort neu anlegen!
