### ISSUE TITLE
Objects don't refresh

### ISSUE THREAD

**Issue by Dragon0501** [ioBroker/ioBroker.mqtt#97]
The objects appear in the adapter, but the objects or the states doesn't change. I have the same problem with more then one connected clients.
![Screenshot 2020-07-02 at 20 41 34](https://user-images.githubusercontent.com/59663011/86397879-f5a34d80-bca4-11ea-836d-2758dbd917d6.png)
![Screenshot 2020-07-02 at 20 41 46](https://user-images.githubusercontent.com/59663011/86397887-f936d480-bca4-11ea-9346-0b3c74264de0.png)

**Comment by Dragon0501** [comment]
Is the adapter wrong configurated?

**Comment by Apollon77** [comment]
Please provide debug log
